import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import ts from 'typescript';
import {build} from 'esbuild';
await build({entryPoints:['worker/community.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/community-test.mjs'});
const {community}=await import('../.sites-runtime/community-test.mjs');
function setup(){
 const sql=new DatabaseSync(':memory:');
 for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
 const DB={prepare(statement){function bound(params=[]){return {
  bind(...values){return bound(values);},
  async first(){return sql.prepare(statement).get(...params)||null;},
  async all(){return {results:sql.prepare(statement).all(...params)};},
  async run(){return sql.prepare(statement).run(...params);}
 };}return bound();}};
 return {DB,COMMUNITY_MODERATOR_EMAIL:'owner@example.com'};
}
async function req(env,path,method='GET',data,who='fan',origin='https://test.example'){const headers={'origin':origin,'content-type':'application/json'};if(who){headers['oai-authenticated-user-id']=who;headers['oai-authenticated-user-email']=who+'@example.com';}const response=await community(new Request('https://test.example/api/community/'+path,{method,headers,body:data?JSON.stringify(data):undefined}),env);return {status:response.status,body:await response.json()};}
const post={displayName:'Fan One',title:'A first discussion',body:'I love the sound.',board:'music'};
test('public reads, authenticated writes, owner controls and durable comments',async()=>{const env=setup();assert.equal((await req(env,'posts','POST',post,null)).status,401);assert.equal((await req(env,'posts','POST',post,'fan','https://evil.example')).status,403);const made=await req(env,'posts','POST',post);assert.equal(made.status,201);const id=made.body.id;let feed=await req(env,'posts','GET',undefined,null);assert.equal(feed.body.posts.length,1);assert.equal(feed.body.posts[0].displayName,'Fan One');assert.ok(!JSON.stringify(feed.body).includes('fan@example.com'));assert.equal((await req(env,'posts/'+id,'DELETE',{},'other')).status,403);assert.equal((await req(env,'posts/'+id+'/comments','POST',{displayName:'Second listener',body:'A reply'},'other')).status,201);assert.equal((await req(env,'posts/'+id)).body.comments.length,1);assert.equal((await req(env,'posts/'+id+'/report','POST',{reason:'Review this'},'other')).status,200);assert.equal((await req(env,'reports','GET',undefined,'other')).status,403);assert.equal((await req(env,'reports','GET',undefined,'owner')).body.reports.length,1);assert.equal((await req(env,'posts/'+id,'DELETE',{},'owner')).status,200);assert.equal((await req(env,'posts')).body.posts.length,0);});
test('announcements restricted, one current poll vote, bounded posting',async()=>{const env=setup();assert.equal((await req(env,'posts','POST',{...post,board:'announcements'})).status,403);assert.equal((await req(env,'posts','POST',{...post,board:'announcements'},'owner')).status,201);await req(env,'poll','POST',{choice:'Ambient worlds'});await req(env,'poll','POST',{choice:'Collaborations'});const poll=await req(env,'poll');assert.equal(poll.body.choice,'Collaborations');assert.equal(poll.body.counts.reduce((s,r)=>s+r.count,0),1);assert.equal((await req(env,'poll','POST',{choice:'Invented'})).status,400);for(let i=0;i<3;i++)assert.equal((await req(env,'posts','POST',post)).status,201);assert.equal((await req(env,'posts','POST',post)).status,429);});
await build({entryPoints:['worker/forms.ts'],bundle:true,platform:'node',format:'esm',outfile:'.sites-runtime/forms-test.mjs'});
const {forms}=await import('../.sites-runtime/forms-test.mjs');
function formRequest(path,method='POST',data,owner=false){const headers={origin:'https://test.example','cf-connecting-ip':'192.0.2.1'};if(owner){headers['oai-authenticated-user-id']='owner';headers['oai-authenticated-user-email']='owner@example.com';}if(data&&!(data instanceof FormData))headers['content-type']='application/json';return new Request('https://test.example'+path,{method,headers,body:data instanceof FormData?data:data?JSON.stringify(data):undefined});}
test('native forms save consented entries and protect the owner inbox',async()=>{const env=setup();let r=await forms(formRequest('/api/forms/signup','POST',{email:'fan@example.com',consent:false}),env);assert.equal(r.status,400);for(let i=0;i<2;i++){r=await forms(formRequest('/api/forms/signup','POST',{email:'fan@example.com',name:'Fan',consent:true}),env);assert.equal(r.status,201);}assert.equal((await forms(formRequest('/api/inbox','GET'),env)).status,410);const entries=(await env.DB.prepare('SELECT * FROM site_requests').all()).results;assert.equal(entries.length,1);assert.equal(entries[0].kind,'signup');r=await forms(formRequest('/api/forms/submission','POST',{email:'artist@example.com',name:'Artist',title:'Demo',genre:'Ambient',link:'javascript:bad',consent:true}),env);assert.equal(r.status,400);});
test('private upload survives notification failure and legacy inbox cannot disclose it',async()=>{const env=setup(),files=new Map();env.BUCKET={async put(k,stream){files.set(k,await new Response(stream).arrayBuffer());},async get(k){return files.has(k)?{body:files.get(k)}:null;},async delete(k){files.delete(k);}};const fd=new FormData();for(const [k,v]of Object.entries({name:'Artist',email:'artist@example.com',title:'Demo',genre:'Ambient',consent:'on'}))fd.set(k,v);fd.set('audio',new File(['audio bytes'],'demo.mp3',{type:'audio/mpeg'}));const r=await forms(formRequest('/api/forms/submission','POST',fd),env);assert.equal(r.status,201);assert.equal(files.size,1);const result=await r.json();assert.ok(result.reference);assert.equal((await forms(formRequest('/api/inbox/'+result.reference+'/file','GET',null,true),env)).status,410);});
