import { chromium } from '/home/user/media-runtime/node_modules/playwright/index.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';
const root=process.cwd()+'/public';const server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://local').pathname);if(!path.extname(p))p+='/index.html';if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');fs.createReadStream(p).pipe(res);}).listen(8789);
const browser=await chromium.launch({executablePath:'/ms-playwright/chromium-1228/chrome-linux64/chrome',args:['--no-sandbox']});const page=await browser.newPage();
try{for(const [quality,platform,visualizer,mode]of [['1080','youtube','wave','art'],['720','tiktok','bars','podcast'],['144','reels','spectrum','podcast'],['2160','youtube','off','podcast']]){
await page.goto('http://127.0.0.1:8789/art-track/');await page.locator('[name=source]').setInputFiles('/home/user/tone.wav');await page.locator('[name=mode][value='+mode+']').check();if(mode==='art')await page.locator('[name=artwork]').setInputFiles('/home/user/art.png');await page.locator('[name=quality]').selectOption(quality);await page.locator('[name=platform]').selectOption(platform);await page.locator('[name=visualizer]').selectOption(visualizer);await page.locator('form button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('dialog[open]')||document.querySelector('[data-health]').textContent.startsWith('Error.'),null,{timeout:240000});console.log(quality,platform,visualizer,await page.locator('[data-health]').textContent());if(await page.locator('dialog[open]').count()){const d=page.waitForEvent('download');await page.locator('dialog a').click();await(await d).saveAs('/home/user/video-'+quality+'-'+platform+'.mp4');}}
for(const format of ['mp3','wav','flac','m4a','ogg','opus','aiff','aac','alac','wv']){
await page.goto('http://127.0.0.1:8789/audio-converter/');await page.locator('[name=source]').setInputFiles('/home/user/tone.wav');await page.locator('[name=preset][value=custom]').check();await page.locator('[name=format]').selectOption(format);await page.locator('[data-convert]').click();await page.waitForFunction(()=>document.querySelector('dialog[open]')||document.querySelector('[data-engine-state]').textContent.startsWith('Error.'),null,{timeout:120000});console.log('FORMAT',format,await page.locator('[data-engine-state]').textContent());}
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8789/art-track/');console.log('MOBILE_OVERFLOW',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await page.locator('[name=source]').setInputFiles({name:'broken.mp3',mimeType:'audio/mpeg',buffer:Buffer.from('not an audio file')});await page.locator('[data-inspect]').click();await page.waitForFunction(()=>document.querySelector('[data-health]').textContent.startsWith('Error.'),null,{timeout:120000});console.log('CORRUPT_FILE',await page.locator('[data-health]').textContent());
}finally{await browser.close();server.close();}
