import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {build} from 'esbuild';
await build({entryPoints:['worker/platform/api.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.sites-runtime/platform-test.mjs'});
const {platformApi,openapi}=await import('../.sites-runtime/platform-test.mjs');
const sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),v=>v.toString(16).padStart(2,'0')).join('');
test('app configuration reports actual processor readiness and keeps unsupported web push off',async()=>{
 const {env,sql}=setup();const owner=await seed(sql);const key='e'.repeat(64);
 assert.equal((await call(env,'/v1/app/config')).body.data.features.server_media_jobs,false);
 assert.equal((await call(env,'/v1/integrations/media_worker','PUT',{environment:'production',secret_config:{worker_key:key},public_config:{}},owner.token)).status,200);
 assert.equal((await call(env,'/v1/app/config')).body.data.features.server_media_jobs,false);
 assert.equal((await call(env,'/v1/worker/jobs/claim','POST',{},key)).status,200);
 assert.equal((await call(env,'/v1/app/config')).body.data.features.server_media_jobs,true);
 sql.prepare("UPDATE platform_settings SET value='0' WHERE key='media_worker_seen'").run();
 assert.equal((await call(env,'/v1/app/config')).body.data.features.server_media_jobs,false);
 sql.prepare("INSERT INTO platform_settings(key,value) VALUES('app_config',?)").run(JSON.stringify({features:{server_media_jobs:true,web_push:true}}));
 const flags=(await call(env,'/v1/app/config')).body.data.features;
 assert.equal(flags.server_media_jobs,false);assert.equal(flags.web_push,false);
});
function setup(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const DB={prepare(statement){const bound=(params=[])=>({bind(...v){return bound(v);},async first(){return sql.prepare(statement).get(...params)||null;},async all(){return {results:sql.prepare(statement).all(...params)};},async run(){return {meta:sql.prepare(statement).run(...params)};}});return bound();},async batch(statements){sql.exec('BEGIN');try{const values=[];for(const s of statements)values.push(await s.all());sql.exec('COMMIT');return values;}catch(e){sql.exec('ROLLBACK');throw e;}}};const env={DB,BUCKET:{},PORTAL_AUTH_SECRET:'test-only-auth-secret-at-least-thirty-two-characters',PLATFORM_VAULT_KEY:'a'.repeat(64)};return {sql,env};}
async function seed(sql,user='owner',role='owner',kind='owner'){const now=Date.now(),token='bb_'+crypto.randomUUID(),refresh='bbr_'+crypto.randomUUID();sql.prepare('INSERT INTO label_user(id,name,email,email_verified,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(user,user,user==='owner'?'business@mrblindbandit.net':user+'@example.test',1,now,now);sql.prepare('INSERT INTO label_members(id,role,status,artist_name,notes,created_at) VALUES(?,?,?,?,?,?)').run(user,role,'active','','',now);sql.prepare('INSERT INTO label_session(id,user_id,token,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?)').run('source-'+user,user,crypto.randomUUID(),now+3600000,now,now);sql.prepare('INSERT INTO platform_sessions(id,user_id,token_hash,refresh_hash,kind,provider,source_session,device_name,platform,app_version,created_at,last_used_at,verified_at,expires_at,refresh_expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('session-'+user,user,await sha(token),await sha(refresh),kind,'label','source-'+user,'Test device','ios','1.3',now,now,now,now+900000,now+3600000);sql.prepare("INSERT INTO platform_settings(key,value) VALUES('owner_mobile_enabled','true') ON CONFLICT(key) DO NOTHING").run();return {token,refresh};}
async function call(env,path,method='GET',data,token,extra={}){const request=new Request('https://mrblindbandit.net'+path,{method,headers:{origin:'https://mrblindbandit.net','cf-connecting-ip':'192.0.2.1',...(token?{authorization:'Bearer '+token}:{}),...(data?{'content-type':'application/json'}:{}),...extra},body:data?JSON.stringify(data):undefined});const response=await platformApi(request,env);return {status:response.status,body:await response.json(),headers:response.headers};}
test('health, exact documentation, safe errors, and CORS',async()=>{const {env}=setup();const h=await call(env,'/v1/system/health');assert.equal(h.status,200);assert.equal(h.body.data.status,'ok');assert.equal(h.headers.get('x-request-id'),h.body.meta.request_id);assert.ok(openapi().paths['/v1/owner/bootstrap'].post.requestBody);assert.ok(openapi().paths['/v1/tools/jobs'].post);assert.equal((await call(env,'/v1/system/health','GET',undefined,undefined,{origin:'https://evil.example'})).status,403);const unknown=await call(env,'/v1/nope');assert.equal(unknown.status,404);assert.ok(!JSON.stringify(unknown.body).includes('stack'));});
test('authentication, owner enforcement, disabled users, and upstream revocation',async()=>{const {env,sql}=setup();const own=await seed(sql);const client=await seed(sql,'client','client','user');assert.equal((await call(env,'/v1/integrations','GET',undefined,client.token)).status,403);assert.equal((await call(env,'/v1/integrations','GET',undefined,own.token)).status,200);sql.prepare("UPDATE platform_sessions SET kind='user' WHERE user_id='owner'").run();assert.equal((await call(env,'/v1/integrations','GET',undefined,own.token)).status,403);sql.prepare("UPDATE label_members SET status='suspended' WHERE id='client'").run();assert.equal((await call(env,'/v1/me','GET',undefined,client.token)).status,403);sql.prepare("DELETE FROM label_session WHERE user_id='owner'").run();assert.equal((await call(env,'/v1/me','GET',undefined,own.token)).status,401);});
test('rotation consumes refresh tokens exactly once and invalidates old access',async()=>{const {env,sql}=setup();const a=await seed(sql,'client','client','user');const r=await call(env,'/v1/auth/refresh','POST',{refresh_token:a.refresh});assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await call(env,'/v1/auth/refresh','POST',{refresh_token:a.refresh})).status,401);assert.equal((await call(env,'/v1/me','GET',undefined,a.token)).status,401);assert.equal((await call(env,'/v1/me','GET',undefined,r.body.data.access_token)).status,200);});
test('master credentials are hashed, owner bootstrap can be killed, and recent verification is required',async()=>{const {env,sql}=setup();const a=await seed(sql);const master='c'.repeat(64);assert.equal((await call(env,'/v1/owner/configure','POST',{master_secret:master,enabled:true,confirmation:'ROTATE OWNER ACCESS'},a.token)).status,200);const value=sql.prepare("SELECT value FROM platform_settings WHERE key='owner_master_digest'").get().value;assert.ok(!value.includes(master));const data={master_secret:master,device_name:'My phone',platform:'ios',app_version:'1.3'};const boot=await call(env,'/v1/owner/bootstrap','POST',data);assert.equal(boot.status,200,JSON.stringify(boot.body));assert.equal((await call(env,'/v1/owner/status','GET',undefined,boot.body.data.access_token)).status,200);sql.prepare("UPDATE platform_sessions SET verified_at=0 WHERE provider='owner'").run();assert.equal((await call(env,'/v1/owner/disable','POST',{confirmation:'DISABLE MOBILE OWNER ACCESS'},boot.body.data.access_token)).status,403);assert.equal((await call(env,'/v1/owner/reauthenticate','POST',{master_secret:master},boot.body.data.access_token)).status,200);assert.equal((await call(env,'/v1/owner/disable','POST',{confirmation:'DISABLE MOBILE OWNER ACCESS'},boot.body.data.access_token)).status,200);assert.equal((await call(env,'/v1/me','GET',undefined,boot.body.data.access_token)).status,401);assert.equal((await call(env,'/v1/owner/bootstrap','POST',data)).status,403);});
test('vault ciphertext, no secret readback, independent environments, delete and replace',async()=>{const {env,sql}=setup();const a=await seed(sql);const secret='not-a-real-provider-credential';const d={environment:'staging',secret_config:{api_key:secret},public_config:{}};assert.equal((await call(env,'/v1/integrations/resend','PUT',d,a.token)).status,200);const row=sql.prepare('SELECT * FROM platform_integrations').get();assert.ok(!row.secret_config.includes(secret));assert.ok(!JSON.stringify((await call(env,'/v1/integrations','GET',undefined,a.token)).body).includes(secret));assert.equal((await call(env,'/v1/integrations/resend','POST',d,a.token)).status,405);assert.equal((await call(env,'/v1/integrations/resend','DELETE',{environment:'staging',confirmation:'DELETE CREDENTIALS'},a.token)).status,200);assert.equal(sql.prepare('SELECT secret_config FROM platform_integrations').get().secret_config,'');assert.equal((await call(env,'/v1/integrations/resend','PUT',d,a.token)).status,200);const fetched=[];const old=globalThis.fetch;globalThis.fetch=async(url,options)=>{fetched.push({url,options});return Response.json({data:[]});};try{assert.equal((await call(env,'/v1/integrations/resend/test','POST',{environment:'staging'},a.token)).body.data.status,'connected');assert.equal(fetched[0].url,'https://api.resend.com/domains');assert.equal((await call(env,'/v1/integrations/resend/test','POST',{environment:'production'},a.token)).status,409);}finally{globalThis.fetch=old;}});
test('device and notification ownership plus token encryption',async()=>{const {env,sql}=setup();const owner=await seed(sql);const client=await seed(sql,'client','client','user');const other=await seed(sql,'other','client','user');const token='d'.repeat(64);const device=await call(env,'/v1/push/register','POST',{installation_id:'my-installation',platform:'ios',token,app_version:'1.3',language:'en'},client.token);assert.equal(device.status,200);assert.ok(!sql.prepare('SELECT token_cipher FROM platform_devices').get().token_cipher.includes(token));assert.ok(!JSON.stringify((await call(env,'/v1/push/devices','GET',undefined,client.token)).body).includes(token));assert.equal((await call(env,'/v1/push/devices/'+device.body.data.id,'DELETE',undefined,other.token)).status,404);const n=await call(env,'/v1/admin/notifications','POST',{user_id:'client',title:'Release update',body:'Ready to review',category:'release',deep_link:'/portal/'},owner.token);assert.equal(n.status,200);assert.equal((await call(env,'/v1/notifications/'+n.body.data.id+'/read','POST',{},other.token)).status,404);assert.equal((await call(env,'/v1/notifications/unread-count','GET',undefined,client.token)).body.data.count,1);assert.equal((await call(env,'/v1/notifications/'+n.body.data.id+'/read','POST',{},client.token)).status,200);assert.equal((await call(env,'/v1/notifications/unread-count','GET',undefined,client.token)).body.data.count,0);});
test('malformed requests, unknown fields, CSRF and rate limits fail closed',async()=>{const {env,sql}=setup();const a=await seed(sql);assert.equal((await call(env,'/v1/me','PATCH',{name:'Good',role:'owner'},a.token)).status,400);assert.equal((await call(env,'/v1/me','PATCH',{name:'x'.repeat(70000)},a.token)).status,413);assert.equal((await call(env,'/v1/me','PATCH',{name:'Good'},a.token,{origin:'https://evil.test'})).status,403);assert.equal((await call(env,'/v1/favorites','POST',{title:'Bad',url:'https://evil.test'},a.token)).status,400);assert.equal((await call(env,'/v1/notifications?limit=100000','GET',undefined,a.token)).status,400);let last;for(let i=0;i<22;i++)last=await call(env,'/v1/auth/refresh','POST',{refresh_token:'invalid'});assert.equal(last.status,429);});

test('native refresh works without Origin but cookie-only writes fail closed',async()=>{const {env,sql}=setup();const a=await seed(sql,'native','client','user');const request=new Request('https://mrblindbandit.net/v1/auth/refresh',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refresh_token:a.refresh})});assert.equal((await platformApi(request,env)).status,200);const cookieRequest=new Request('https://mrblindbandit.net/v1/auth/refresh',{method:'POST',headers:{'content-type':'application/json',cookie:'session=x'},body:JSON.stringify({refresh_token:a.refresh})});assert.equal((await platformApi(cookieRequest,env)).status,403);});

test('media completion keeps committed object if audit logging fails',async()=>{
 await build({entryPoints:['worker/platform/media.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.sites-runtime/media-test.mjs'});
 const {workerOutput}=await import('../.sites-runtime/media-test.mjs');
 const {env,sql}=setup();const owner=await seed(sql);const key='b'.repeat(64),lease='test-lease';
 assert.equal((await call(env,'/v1/integrations/media_worker','PUT',{environment:'production',secret_config:{worker_key:key},public_config:{}},owner.token)).status,200);
 sql.prepare("INSERT INTO platform_jobs(id,user_id,media_id,tool,options,status,idempotency_key,input_digest,lease_hash,lease_expires_at,created_at,updated_at) VALUES('job','owner','input','audio-converter','{}','processing','unique-key','digest',?,?,?,?)").run(await sha(lease),Date.now()+60000,Date.now(),Date.now());
 const bytes=new TextEncoder().encode('RIFF0000WAVE0000');let deleted=false;
 env.BUCKET={async put(){},async head(){return {size:bytes.length};},async get(){return {arrayBuffer:async()=>bytes.buffer};},async delete(){deleted=true;}};
 sql.exec("CREATE TRIGGER audit_failure BEFORE INSERT ON platform_audit WHEN NEW.action='media.completed' BEGIN SELECT RAISE(ABORT,'test audit unavailable'); END;");
 const req=new Request('https://mrblindbandit.net/v1/worker/jobs/job/output',{method:'PUT',headers:{authorization:'Bearer '+key,'x-job-lease':lease,'content-type':'audio/wav','content-length':String(bytes.length)},body:bytes});
 await assert.rejects(workerOutput(req,env,'job','request-id'));
 assert.equal(deleted,false);assert.equal(sql.prepare("SELECT status FROM platform_jobs WHERE id='job'").get().status,'completed');assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM platform_notifications').get().n,1);
});
