import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
// Separate identity store: label credentials never grant access to the fan forum.
export const labelUser=sqliteTable('label_user',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),emailVerified:integer('email_verified',{mode:'boolean'}).notNull().default(false),image:text('image'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()});
export const labelSession=sqliteTable('label_session',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>labelUser.id,{onDelete:'cascade'}),token:text('token').notNull().unique(),expiresAt:integer('expires_at',{mode:'timestamp_ms'}).notNull(),ipAddress:text('ip_address'),userAgent:text('user_agent'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},t=>[index('label_session_user').on(t.userId)]);
export const labelAccount=sqliteTable('label_account',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>labelUser.id,{onDelete:'cascade'}),accountId:text('account_id').notNull(),providerId:text('provider_id').notNull(),password:text('password'),accessToken:text('access_token'),refreshToken:text('refresh_token'),idToken:text('id_token'),accessTokenExpiresAt:integer('access_token_expires_at',{mode:'timestamp_ms'}),refreshTokenExpiresAt:integer('refresh_token_expires_at',{mode:'timestamp_ms'}),scope:text('scope'),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},t=>[index('label_account_user').on(t.userId),uniqueIndex('label_account_provider').on(t.providerId,t.accountId)]);
export const labelVerification=sqliteTable('label_verification',{id:text('id').primaryKey(),identifier:text('identifier').notNull(),value:text('value').notNull(),expiresAt:integer('expires_at',{mode:'timestamp_ms'}).notNull(),createdAt:integer('created_at',{mode:'timestamp_ms'}).notNull(),updatedAt:integer('updated_at',{mode:'timestamp_ms'}).notNull()},t=>[index('label_verification_identifier').on(t.identifier)]);
export const labelMembers=sqliteTable('label_members',{id:text('id').primaryKey().references(()=>labelUser.id,{onDelete:'cascade'}),role:text('role').notNull().default('client'),status:text('status').notNull().default('active'),artistName:text('artist_name').notNull().default(''),notes:text('notes').notNull().default(''),createdAt:integer('created_at').notNull()});
export const labelEarnings=sqliteTable('label_earnings',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>labelMembers.id),description:text('description').notNull(),source:text('source').notNull(),period:text('period').notNull(),currency:text('currency').notNull(),amount:integer('amount').notNull(),status:text('status').notNull().default('reported'),reference:text('reference').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()},t=>[index('label_earnings_client').on(t.clientId,t.createdAt)]);
export const labelContracts=sqliteTable('label_contracts',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>labelMembers.id),title:text('title').notNull(),storageKey:text('storage_key').notNull(),fileName:text('file_name').notNull(),status:text('status').notNull().default('shared'),reviewedAt:integer('reviewed_at'),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()},t=>[index('label_contracts_client').on(t.clientId,t.createdAt)]);
export const labelMessages=sqliteTable('label_messages',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>labelMembers.id),senderId:text('sender_id').notNull().references(()=>labelMembers.id),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('label_messages_thread').on(t.clientId,t.createdAt)]);
export const labelTasks=sqliteTable('label_tasks',{id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>labelMembers.id),title:text('title').notNull(),details:text('details').notNull().default(''),dueDate:text('due_date').notNull().default(''),status:text('status').notNull().default('open'),createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()},t=>[index('label_tasks_client').on(t.clientId,t.createdAt)]);
export const labelAudit=sqliteTable('label_audit',{id:text('id').primaryKey(),actorId:text('actor_id').notNull(),action:text('action').notNull(),targetId:text('target_id').notNull(),createdAt:integer('created_at').notNull()},t=>[index('label_audit_created').on(t.createdAt)]);
export const labelMail=sqliteTable('label_mail',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),providerId:text('provider_id'),createdAt:integer('created_at').notNull()});
export const labelSettings=sqliteTable('label_settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const labelWorkspaceRecords=sqliteTable('label_workspace_records',{id:text('id').primaryKey(),module:text('module').notNull(),title:text('title').notNull(),status:text('status').notNull(),owner:text('owner').notNull().default(''),dueDate:text('due_date').notNull().default(''),details:text('details').notNull(),checklist:text('checklist').notNull(),archived:integer('archived').notNull().default(0),revision:integer('revision').notNull().default(1),createdBy:text('created_by').notNull(),updatedBy:text('updated_by').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('label_workspace_module').on(t.module,t.archived,t.updatedAt)]);
