"""Final build: connected forms, community profile and owner inbox."""
from universe import *

def field(label,name,type='text',required=True,maxlen=200):
    return '<label>'+label+'<input name="'+name+'" type="'+type+'" maxlength="'+str(maxlen)+'"'+(' required' if required else '')+'></label>'
def consent(text):return '<label class="consent"><input type="checkbox" name="consent" required><span>'+text+'</span></label>'
def form_end(label):return '<input type="hidden" name="website" value=""><button class="button" type="submit">'+label+'</button><p role="status" aria-live="polite"></p><p class="small">Your form is saved privately for the site owner. <a href="/privacy/">Privacy information</a></p></form>'

submission='<form class="brief-form native-form" data-native-form="submission">'+field('Artist or stage name','name',maxlen=120)+field('Contact email','email','email',maxlen=254)+field('Track or project title','title',maxlen=160)+field('Genre','genre',maxlen=100)+field('Listening link (optional if you upload audio)','link','url',False,1500)+'<label>Audio file (optional)<input type="file" name="audio" accept=".mp3,.wav,audio/mpeg,audio/wav"></label><p class="small">MP3 or WAV, up to 10 MB. Provide a listening link or an audio file. Files are private to the site owner.</p><label>Message or private listening-link password (optional)<textarea name="message" rows="5" maxlength="3000"></textarea></label>'+consent('I own or have permission to share this music and allow Blindbandit Records to review it and contact me about this submission.')+form_end('Submit music')
layout('/submit/','Submit music','Send music directly to Blindbandit Records for consideration.',intro('BLINDBANDIT RECORDS / MUSIC SUBMISSIONS','LET US HEAR<br><span>YOUR WORLD.</span>','Share a listening link or audio file and tell us about your music.')+section('<div class="submission-layout">'+submission+'<aside class="side-note"><h3>Before you send</h3><p>Check your listening link and include its password if needed. A submission does not transfer ownership or guarantee a reply, release, or signing.</p><a href="/submission-guide/">Submission guide</a><a href="/submission-faq/">Common questions</a><p>If the form is unavailable, email business@mrblindbandit.net with a listening link.</p></aside></div>'))

signup='<form class="brief-form native-form" data-native-form="signup">'+field('Email address','email','email',maxlen=254)+field('First name (optional)','name','text',False,120)+'<label>What interests you?<select name="interests"><option>Artist and label updates</option><option>New music</option><option>Blindbandit Records</option><option>Videos and creative work</option></select></label>'+consent('I agree to receive occasional email updates from Mr. Blindbandit and Blindbandit Records.')+form_end('Join the mailing list')
layout('/signup/','Join the mailing list','Register for occasional artist and label updates.',intro('MUSIC / LABEL / CREATIVE UPDATES','KEEP THE<br><span>CONNECTION.</span>','Sign up for occasional updates from Mr. Blindbandit and Blindbandit Records.')+section('<div class="submission-layout">'+signup+'<aside class="side-note"><h3>Mailing list or community?</h3><p>This form registers your interest in email updates. To post in the fan community, create a community profile using ChatGPT sign-in.</p><a href="/community/account/">Create your community profile</a><p>To request removal from the mailing list, email business@mrblindbandit.net.</p></aside></div>'))

inquiry='<form class="brief-form native-form" data-native-form="inquiry">'+field('Your name or organization','name',maxlen=120)+field('Contact email','email','email',maxlen=254)+'<label>Inquiry type<select name="category">'+''.join('<option>'+x+'</option>' for x in ['Feature collaboration','Production','Interview','Performance or appearance','Music licensing','Sponsorship or brand partnership'])+'</select></label><label>Project details<textarea name="message" rows="7" maxlength="4000" required></textarea></label>'+field('Relevant link (optional)','reference','url',False,1500)+consent('I agree to be contacted about this inquiry. This does not sign me up for marketing emails.')+form_end('Send inquiry')
layout('/contact/forms/','Professional inquiries','Send a feature, production, interview, performance, licensing or sponsorship inquiry.',intro('FEATURES / PRODUCTION / PRESS','LET’S MAKE<br><span>A CONNECTION.</span>','Send your project details directly to the artist’s private inquiry inbox.')+section('<div class="submission-layout">'+inquiry+'<aside class="side-note"><h3>Make the request clear</h3><p>Include the project, role, timing, and budget range. For interviews, name the outlet. For performances, include the location and date. For music licensing, identify the track and intended use.</p><p>Availability and terms are confirmed individually.</p><a href="/submit/">Send a music submission</a><a href="/project-brief/">Build a detailed brief</a></aside></div>'))

publish('/community/account/','Community account','SIGN IN / PROFILE','YOUR COMMUNITY<br><span>STARTS HERE.</span>','Sign in securely with Clerk, choose a public display name, and join the conversation.',community_surface('account'))
publish('/community/dashboard/','My community dashboard','YOUR POSTS / YOUR COMMENTS','YOUR PLACE<br><span>IN THE COMMUNITY.</span>','Find your discussions, replies, and profile in one place.',community_surface('dashboard'))
publish('/owner/inbox/','Owner inbox','PRIVATE / SITE OWNER','YOUR CREATIVE<br><span>INBOX.</span>','Music submissions, mailing-list signups, and professional inquiries.',section('<div data-owner-inbox><p role="status">Loading the owner inbox…</p></div>'))

privacy=section(prose('PUBLIC COMMUNITY AND SIGN-IN',['Community posts and comments are public and show the display name you choose. ChatGPT sign-in provides a site-specific user identity for posting, commenting, voting, and managing your contributions. Your sign-in email is not displayed beside your posts.','Profiles, posts, comments, poll votes, and reports are stored for this website. Reports are visible to the site owner. Public posts may be hidden by their author or the owner; contact the owner for other data-removal requests.'])+prose('MUSIC SUBMISSIONS AND INQUIRIES',['The site collects the contact information, project details, listening links, and optional audio files you choose to submit. They are saved to a private inbox accessible to the site owner for reviewing the work and responding to the request. They are not posted to the fan community.','Submission consent allows review and contact about that request. It does not enroll you in the mailing list or transfer ownership of your music. Audio uploads are limited to MP3 or WAV files up to 10 MB.'])+prose('MAILING-LIST SIGNUPS',['The signup form collects your email, optional first name, interests, and consent for occasional artist and label updates. Entries are stored for the site owner. No automated email campaign is triggered by this website. To request removal, email business@mrblindbandit.net.'])+prose('PREFERENCES AND EXTERNAL SERVICES',['Text size, contrast, and motion preferences are saved in your browser on this device. The project brief builder prepares text locally until you choose to send it through your email app.','Spotify, Apple Music, and YouTube provide external media interfaces; PayPal and Wise process payments on their own sites. Those providers apply their own terms and privacy practices. The site’s active submission, signup, and inquiry forms now save directly to the site rather than loading Jotform.'])+prose('OPERATIONS AND REQUESTS',['The site uses rate limits to reduce repeated submissions. A hashed network identifier may be stored for that purpose; raw network addresses are not stored in the application database by the form code.','To ask about data, correct a submission, request mailing-list removal, or report a privacy concern, contact business@mrblindbandit.net. Include only the information needed to identify your request.']))
layout('/privacy/','Privacy & community information','How community accounts, forms, uploads, and preferences are used.',intro('PRIVACY / CONTACT','YOUR DETAILS.<br><span>A CLEAR PURPOSE.</span>','Information about the site’s community, forms, and external services.')+privacy)

for p in D.rglob('index.html'):
    s=p.read_text()
    if '/community.js' not in s:s=s.replace('<script src="/app.js" defer></script>','<script src="/app.js" defer></script><script src="/community.js" defer></script>')
    s=s.replace('<script src="/community.js" defer></script>','<script src="/community.js" defer></script><script src="/clerk-community.js" defer></script><script src="/forms.js" defer></script>')
    if p==D/'explore/index.html':s=s.replace('<div class="directory-grid">','<div class="directory-grid"><section class="directory-group"><h2>Your account</h2><a data-directory-item href="/community/account/">Community profile</a><a data-directory-item href="/community/dashboard/">My dashboard</a></section>')
    s=s.replace('Use a streaming or private listening link in the form. Include any password needed to access it.','Use a streaming link or upload an MP3 or WAV up to 10 MB. Include a password if your listening link requires one.')
    s=s.replace('The player loads from YouTube when you press play.','The player loads from YouTube when you press play.')
    if 'data-owner-inbox' in s or 'data-community="moderation"' in s:s=s.replace('<meta name="description"','<meta name="robots" content="noindex"><meta name="description"',1)
    p.write_text(s)
# Form entry points for each professional inquiry section.
for route in ['studio','booking','licensing','partnerships','press']:
 p=D/route/'index.html';s=p.read_text();p.write_text(s.replace('</main>',section(button('Open the professional inquiry form','/contact/forms/'))+'</main>'))
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://mrblindbandit.net'+u+'</loc></url>' for _,u in pages if u not in ['/community/moderation/','owner/inbox/','/owner/inbox/'])+'</urlset>')
(ROOT/'data/pages.json').write_text(json.dumps([{'title':n,'path':u} for n,u in pages],indent=2))
print('Connected website:',len(pages),'pages; native forms; community profile and dashboard; private owner inbox')
