"""Ten accessible, browser-local everyday utilities plus public discovery sections."""
import html

TOOLS = [
  ('daily-planner','Daily planner','Organize today around three priorities, appointments, and notes.', '''<label>Date<input name="date" type="date" required></label><label class="tool-wide">Three priorities<textarea name="priorities" rows="4" placeholder="One priority per line" maxlength="1000"></textarea></label><label class="tool-wide">Appointments and time blocks<textarea name="schedule" rows="5" maxlength="1500"></textarea></label><label class="tool-wide">Notes<textarea name="notes" rows="4" maxlength="1500"></textarea></label>'''),
  ('time-zone-planner','Time-zone planner','Compare a date and time across common music-business locations.', '''<label>Date and time<input name="datetime" type="datetime-local" required></label><label>Starting time zone<select name="zone"><option value="Asia/Manila">Philippines — Manila</option><option value="America/New_York">United States — New York</option><option value="America/Los_Angeles">United States — Los Angeles</option><option value="Europe/London">United Kingdom — London</option><option value="UTC">UTC</option></select></label>'''),
  ('tip-calculator','Tip and bill calculator','Calculate a tip and split a bill without sending financial information anywhere.', '''<label>Bill amount<input name="amount" type="number" min="0" step="0.01" required></label><label>Tip percentage<input name="tip" type="number" min="0" max="100" step="0.1" value="15" required></label><label>Number of people<input name="people" type="number" min="1" step="1" value="1" required></label>'''),
  ('percentage-calculator','Percentage calculator','Calculate a percentage, a percentage change, or a sale discount.', '''<label>Calculation<select name="mode"><option value="of">Percentage of a number</option><option value="change">Percentage change</option><option value="discount">Price after discount</option></select></label><label>First value<input name="a" type="number" step="any" required></label><label>Second value<input name="b" type="number" step="any" required></label>'''),
  ('unit-converter','Unit converter','Convert common length, weight, and temperature measurements.', '''<label>Measurement<select name="kind"><option value="km-mi">Kilometers to miles</option><option value="mi-km">Miles to kilometers</option><option value="kg-lb">Kilograms to pounds</option><option value="lb-kg">Pounds to kilograms</option><option value="c-f">Celsius to Fahrenheit</option><option value="f-c">Fahrenheit to Celsius</option></select></label><label>Value<input name="value" type="number" step="any" required></label>'''),
  ('date-calculator','Date calculator','Count days between two dates or find a date before or after another date.', '''<label>Calculation<select name="mode"><option value="between">Days between dates</option><option value="offset">Add or subtract days</option></select></label><label>Starting date<input name="start" type="date" required></label><label>Ending date or number of days<input name="end" required placeholder="YYYY-MM-DD or 30"></label>'''),
  ('password-generator','Password generator','Generate a strong random password locally with your device’s secure random generator.', '''<label>Length<input name="length" type="number" min="12" max="64" value="20" required></label><fieldset class="tool-wide tool-checklist"><legend>Character options</legend><label><input name="upper" type="checkbox" checked> Uppercase letters</label><label><input name="numbers" type="checkbox" checked> Numbers</label><label><input name="symbols" type="checkbox" checked> Symbols</label></fieldset>'''),
  ('text-toolkit','Text toolkit','Count words and characters, clean spacing, or change capitalization.', '''<label class="tool-wide">Text<textarea name="text" rows="9" maxlength="20000" required></textarea></label><label>Action<select name="action"><option value="count">Count words and characters</option><option value="spaces">Clean repeated spacing</option><option value="lower">Lowercase</option><option value="upper">Uppercase</option><option value="title">Title case</option></select></label>'''),
  ('file-name-cleaner','File-name cleaner','Turn a working title into a safer, easier-to-share file name.', '''<label class="tool-wide">Original file name<input name="filename" maxlength="240" required placeholder="My Final Mix (Version 2).wav"></label><label>Style<select name="style"><option value="hyphen">lowercase-with-hyphens</option><option value="underscore">lowercase_with_underscores</option></select></label>'''),
  ('checklist-maker','Checklist maker','Create, check, save, print, and download a reusable checklist.', '''<label>Checklist title<input name="title" maxlength="120" required></label><label class="tool-wide">Items<textarea name="items" rows="9" maxlength="5000" required placeholder="One item per line"></textarea></label>''')
]

def _cards():
    return '<div class="everyday-grid">'+''.join('<a href="/tools/'+slug+'/"><span>UTILITY</span><h3>'+html.escape(title)+'</h3><p>'+html.escape(description)+'</p><strong>Open tool ↗</strong></a>' for slug,title,description,_ in TOOLS)+'</div>'

def add_everyday_tools(output, layout, pages):
    for slug,title,description,fields in TOOLS:
        actions='<button class="button" type="submit">Run tool</button><button type="reset">Clear</button>'
        if slug in ('daily-planner','checklist-maker'): actions='<button class="button" type="submit">Build and save</button><button type="button" data-tool-download disabled>Download</button><button type="button" data-tool-print disabled>Print</button><button type="reset">Clear</button>'
        elif slug in ('password-generator','text-toolkit','file-name-cleaner'): actions='<button class="button" type="submit">Run tool</button><button type="button" data-tool-copy disabled>Copy result</button><button type="reset">Clear</button>'
        body='<section class="page-intro shell"><p class="eyebrow">MR. BLINDBANDIT / EVERYDAY UTILITIES</p><h1>'+html.escape(title)+'</h1><p class="lede">'+html.escape(description)+'</p></section><section class="shell section tool-shell"><h2>Use the tool</h2><form class="tool-form" data-everyday-tool="'+slug+'"><div class="tool-grid">'+fields+'</div><div class="tool-actions">'+actions+'</div><output class="tool-result" aria-live="polite"></output></form><p class="small tool-privacy">This tool runs on your device. Information entered here is not submitted to Blindbandit Records.</p></section><section class="shell section"><h2>More practical resources</h2><p>Use these utilities for planning and everyday calculations, then explore the artist and label resources when you are ready.</p><a class="text-link" href="/resources/">Browse all resources ↗</a></section><script src="/everyday-tools.js" defer></script>'
        path='/tools/'+slug+'/'
        layout(path,title,description,body)
        page=output/'tools'/slug/'index.html'
        source=page.read_text().replace('<body>','<body class="public-modern">',1).replace('<link rel="stylesheet" href="/styles.css">','<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/public-modern.css">',1)
        page.write_text(source)
        if not any(existing==path for _,existing in pages): pages.append((title,path))

    section='<section class="shell section everyday-hub"><div class="section-heading"><div><p class="eyebrow">EVERYDAY UTILITY DESK</p><h2>Useful tools, ready when you are.</h2></div><a class="text-link" href="/explore/">Explore the whole site ↗</a></div><p class="lede">Private, accessible tools for planning, calculating, converting, writing, and staying organized. They run in your browser.</p>'+_cards()+'</section>'
    for route in ('resources',''):
        page=output/route/'index.html' if route else output/'index.html'
        if page.exists():
            source=page.read_text()
            source=source.replace('</main>',section+'</main>',1)
            page.write_text(source)
