"""Build the complete artist and label website. Run python scripts/expand.py."""
from build import *
from urllib.parse import quote

FORMS=json.loads((ROOT/'data/forms.json').read_text())
pages=[('Home','/'),('Music','/music/'),('Collaborators','/collaborators/'),('Story','/story/'),('Videos','/videos/'),('Connect','/connect/'),('Support','/support/'),('Press','/press/')]
def publish(route,title,kicker,headline,description,content):
    layout(route,title,description,intro(kicker,headline,description)+content)
    pages.append((title,route))
def tiles(items):
    return '<div class="portal-grid">'+''.join(f'<a href="{u}"><span>{k}</span><h3>{t}</h3><p>{d}</p><b aria-hidden="true">↗</b></a>' for k,t,d,u in items)+'</div>'
def section(body):return '<section class="shell section">'+body+'</section>'
def prose(title,paras):return '<div class="editorial-block"><h2>'+title+'</h2>'+''.join('<p>'+p+'</p>' for p in paras)+'</div>'
def email(subject):return 'mailto:business@mrblindbandit.net?subject='+quote(subject)
def form(kind,title):
    url=FORMS[kind]['url']
    return '<div class="form-shell"><iframe class="hosted-form" src="'+esc(url)+'" title="'+title+'" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe><p>Having trouble with the form? <a class="text-link" href="'+esc(url)+'">Open '+title+' in a new page ↗</a></p><p class="small">Forms are hosted by Jotform. <a href="/privacy/">How your information is used</a></p></div>'

label=section('<div class="label-masthead"><div class="label-seal" aria-hidden="true">BB<span>RECORDS</span></div><div><p class="eyebrow">Founded by Mr. Blindbandit</p><h2>INDEPENDENT<br><span>BY DESIGN.</span></h2><p class="lede">A home for the music and creative world of Mr. Blindbandit.</p><div class="actions">'+button('Submit your music','/submit/')+button('About the label','/label/about/')+'</div></div></div>')
label+=section(tiles([('THE LABEL','Our story','Meet the founder and the creative identity behind Blindbandit Records.','/label/about/'),('THE SOUND','Release catalog','Explore albums, EPs, and singles from the artist behind the label.','/music/'),('YOUR MUSIC','Submissions','Share a listening link and introduce your project.','/submit/')]))
label+=section(prose('A CREATIVE POINT OF VIEW',['Blindbandit Records brings together Kaeleb Heck’s work as an independent recording artist, producer, and storyteller. It is part of a creative practice that crosses ambient, cinematic, electronic, dreamcore, and hip-hop sounds.','The label hub is a starting point for listeners and artists: explore the music, learn about the founder, or send a project for consideration. For production, press, and other professional inquiries, use the dedicated contact pages.'])+tiles([('CREATE','Studio inquiries','Start a conversation about a sound or a project.','/studio/'),('CONNECT','Creative partnerships','Share an idea for a joint project.','/partnerships/'),('FOLLOW','Label updates','Register for occasional artist and label news.','/signup/')]))
publish('/label/','Blindbandit Records','THE RECORD LABEL','BLINDBANDIT<br><span>RECORDS.</span>','Blind-owned. Creator-driven. An independent creative identity founded by Mr. Blindbandit.',label)

publish('/label/about/','About the label','BLINDBANDIT RECORDS / ABOUT','THE LABEL.<br><span>THE PERSPECTIVE.</span>','Music and independent creation, connected by a distinct point of view.',section('<div class="editorial-layout"><div>'+prose('FOUNDED BY AN ARTIST',['Blindbandit Records was founded by Mr. Blindbandit, the artist and producer also known as Kaeleb Heck. His work across music, video, and digital storytelling shapes the label’s creative identity.','With Virginia roots and a home in the Philippines, his public creative world connects places, sounds, and people. The music reflects a willingness to move between atmospheric projects and beat-driven releases.'])+prose('SPACE FOR CONNECTION',['Accessible technology and screen readers are part of the founder’s own creative process. That experience sits alongside a focus on independent work and collaboration.','Artists can introduce their music through the submission form. A submission starts a conversation; it is not an offer of a record deal or a commitment to distribute or promote a release.'])+'</div><aside class="side-note"><h3>Explore the label</h3><a href="/label/artists/">Founder &amp; creative connections</a><a href="/submit/">Submit music</a><a href="/submission-guide/">Submission guide</a><a href="/studio/">Studio inquiries</a></aside></div>'))

publish('/label/artists/','Founder & creative connections','THE PEOPLE','ARTIST-LED.<br><span>CONNECTED.</span>','Meet the founder, then discover the artists connected through shared music.',section('<div class="feature"><img src="/assets/artist.jpg" alt="Mr. Blindbandit, founder of Blindbandit Records" width="531" height="640" loading="lazy"><div><p class="eyebrow">Founder / artist / producer</p><h2>MR.<br>BLINDBANDIT</h2><p>Kaeleb Heck is the creative force behind Blindbandit Records. Explore his music, story, and professional contact information.</p>'+button('Meet the founder','/story/')+'</div></div>'+prose('CREATIVE CONNECTIONS',['UUu Tang Maskman, Yxngfery, Pablo Jackson Hairston, R3NJ1, true_explores, and Trukidchris appear in the site’s collaboration features through credited shared work. Those credits describe collaborations, not label membership.'])+button('Explore the collaborators','/collaborators/')))

publish('/submit/','Submit music','BLINDBANDIT RECORDS / MUSIC SUBMISSIONS','LET US HEAR<br><span>YOUR WORLD.</span>','Share a listening link and tell us about your music.',section('<div class="submission-layout"><div>'+form('submission','Music submission form')+'</div><aside class="side-note"><h3>Before you send</h3><ul><li>Use a working streaming or private listening link.</li><li>Include a password if the link needs one.</li><li>Share music you own or have permission to submit.</li><li>Use an email where you can be reached.</li></ul><p>Submissions are for consideration. A response, release, or signing is not guaranteed.</p><a href="/submission-guide/">Read the submission guide</a><a href="/submission-faq/">Submission questions</a></aside></div>'))

publish('/submission-guide/','Submission guide','FOR ARTISTS','MAKE YOUR<br><span>INTRODUCTION.</span>','A clear submission makes it easier to understand your music and your project.',section('<div class="steps">'+''.join(f'<article><span>0{i}</span><div><h2>{t}</h2><p>{d}</p></div></article>' for i,t,d in [(1,'Choose the music','Send a track or a focused project that represents the sound you want to share. A short selection is easier to navigate than an unorganized folder.'),(2,'Check the link','Open your link in a signed-out window before submitting. If it requires a password, include it. Avoid links that expire before someone can listen.'),(3,'Introduce yourself','Use your artist name, a contact email, and a short explanation of the project. Mention whether it is released or unreleased, and name your collaborators.'),(4,'Say what you are looking for','Tell us whether you are introducing your music, proposing a collaboration, or seeking a conversation about a release. Keep the request specific.'),(5,'Send once, clearly','Complete the music submission form. Keep a copy of the links and details you sent. Use the contact email if a material detail needs correcting.')])+'</div><div class="actions">'+button('Submit your music','/submit/')+button('Submission FAQ','/submission-faq/')+'</div>'))

def faq(items):return '<div class="faq">'+''.join('<details><summary>'+q+'</summary><p>'+a+'</p></details>' for q,a in items)+'</div>'
publish('/submission-faq/','Submission FAQ','FOR ARTISTS / QUESTIONS','BEFORE YOU<br><span>HIT SEND.</span>','Answers to common questions about sharing music with Blindbandit Records.',section(faq([('Does submitting mean I am signed?','No. Submitting music asks for consideration. Any future collaboration or release would require a separate discussion and agreement.'),('Should I upload a music file?','Use a streaming or private listening link in the form. Include any password needed to access it.'),('Can I send unreleased music?','You can provide an accessible private listening link. Share only material you own or are authorized to submit.'),('Will everyone receive a response?','A response or review timeline is not guaranteed. Make sure your contact email and listening link are correct.'),('Does the form sign me up for marketing?','No. Music submissions and the mailing-list signup are separate. Join the mailing list only if you want artist and label updates.'),('How do I correct a submission?','Email business@mrblindbandit.net with your artist name, track title, and the correction. Avoid sending account passwords; only include a listening-link password when necessary.')])+button('Open the submission form','/submit/')))

publish('/signup/','Join the mailing list','STAY CONNECTED','GET CLOSER<br><span>TO THE SOUND.</span>','Register for occasional music, label, and creative updates from Mr. Blindbandit.',section('<div class="submission-layout">'+form('signup','Mailing list signup')+'<aside class="side-note"><h3>Your connection to the artist</h3><p>Choose the updates you are interested in: releases, the label, or videos and creative work.</p><p>Signup is optional. To request removal, contact business@mrblindbandit.net.</p><a href="/community/">Other ways to stay involved</a><a href="/privacy/">Privacy information</a></aside></div>'))

publish('/community/','Community','LISTENERS / CREATORS / CONNECTIONS','PART OF<br><span>THE WORLD.</span>','Follow the music, discover another artist, or share a track with someone who will connect with it.',section(tiles([('KEEP IN TOUCH','Join the mailing list','Register your interest in music and label updates.','/signup/'),('FOLLOW ALONG','Official channels','Find the artist’s verified links in one place.','/connect/'),('SHOW SUPPORT','Support the artist','Send optional support with PayPal or Wise.','/support/')])+prose('START WITH THE MUSIC',['A saved track, a shared release, and a thoughtful comment all help create a connection around independent music. Explore the catalog and send a favorite to someone who might enjoy it.','For artists, the submission form offers a dedicated way to introduce a project. For listeners, the collaborators page opens doors into other creative worlds.'])+button('Discover a starting point','/discover/')))

publish('/discover/','Start listening','A GUIDE TO THE CATALOG','FIND YOUR<br><span>FIRST PLAY.</span>','Choose a way into the Mr. Blindbandit catalog.',section(tiles([('LONGER LISTENING','Albums','Spend time with a full project: weightless, Time flies, and more.','/music/albums/'),('A QUICK INTRODUCTION','Singles','Explore individual releases and alternate versions.','/music/singles/'),('A FOCUSED PROJECT','EPs','Discover cry forever, Clairvoyant Castle, and other EPs.','/music/eps/')])+heading('First stops','THREE PLACES TO BEGIN.')+'<div class="records">'+cards([next(r for r in own if r['id']==id) for id in ['1819243218','1886385443','6768636613']])+'</div>'+prose('FOLLOW THE CONNECTIONS',['Start with Sapphire castles, explore the weightless album, or try the cry forever EP. Then visit Collaborators for shared releases and UUu Tang Maskman’s music. These are starting points for discovery, rather than a ranking of the catalog.'])+button('Explore collaborations','/collaborators/')))

for slug,kind,title,desc in [('albums','Album','FULL PROJECTS.','Explore the albums in the Mr. Blindbandit catalog, with official artwork and listening links.'),('singles','Single','ONE TRACK.<br>MANY WORLDS.','Individual releases, featured artists, and alternate versions across the catalog.'),('eps','EP','SMALL WORLDS.<br>DEEP LISTENING.','Focused projects from the Mr. Blindbandit EP catalog.')]:
    selected=[r for r in own if r['type']==kind]
    publish('/music/'+slug+'/',kind+'s','THE CATALOG / '+kind.upper(),title,desc,section('<p class="eyebrow">'+str(len(selected))+' releases in this collection</p><div class="records">'+cards(selected)+'</div><div class="actions">'+button('Browse all releases','/music/')+button('Listening guide','/discover/')+'</div>'))

publish('/studio/','Studio & production','MR. BLINDBANDIT / CREATIVE INQUIRIES','LET’S TALK<br><span>ABOUT SOUND.</span>','Have a production idea or a project in mind? Start with a clear creative brief.',section(tiles([('01 / THE IDEA','Describe the project','Tell us what you are making, the sound you have in mind, and how the music will be used.','/project-brief/'),('02 / THE CONTEXT','Share references','Include links to your work and reference tracks, with a note explaining what you like about them.','/project-brief/'),('03 / THE DETAILS','Define the scope','Mention deliverables, timing, and any budget range you want to discuss.','/project-brief/')])+prose('A CONVERSATION COMES FIRST',['Mr. Blindbandit’s creative work spans production, recording, and digital storytelling. A studio inquiry is an invitation to discuss a project; availability, scope, and any terms are confirmed individually.','For music you have already created and want to submit for consideration, use the label’s dedicated submission form.'])+'<div class="actions">'+button('Prepare a project brief','/project-brief/')+button('Email a studio inquiry',email('Studio / production inquiry'))+'</div>'))

publish('/project-brief/','Project brief builder','FOR CREATIVE PARTNERS','GIVE YOUR<br><span>IDEA SHAPE.</span>','Build a concise project brief, then copy it or open it in your email app.',section('''<div class="submission-layout"><form id="brief-form" class="brief-form"><label>Your name or project<input name="name" required maxlength="120"></label><label>Project type<select name="type"><option>Music production</option><option>Creative collaboration</option><option>Video or brand project</option><option>Interview or appearance</option></select></label><label>What are you making?<textarea name="idea" required maxlength="1800" rows="5"></textarea></label><label>Reference link (optional)<input name="reference" type="url" placeholder="https://"></label><label>Timeline (optional)<input name="timeline" maxlength="120"></label><label>Budget range (optional)<input name="budget" maxlength="120"></label><button class="button" type="submit">Prepare my brief</button><p class="small">This tool prepares text on your device. It does not send your inquiry.</p></form><aside class="side-note"><h3>Your prepared brief</h3><textarea id="brief-output" aria-label="Prepared project brief" readonly rows="14" placeholder="Complete the form to prepare your brief."></textarea><div class="actions"><button id="copy-brief" hidden>Copy brief</button><a id="email-brief" class="button" hidden>Open email app</a></div><p id="brief-status" role="status"></p></aside></div>'''))

publish('/licensing/','Music use inquiries','FILM / VIDEO / BRANDS','MUSIC FOR<br><span>YOUR PROJECT.</span>','Ask about using a specific Mr. Blindbandit track in your production.',section(prose('TELL US ABOUT THE USE',['Include the exact track title and version, a description of your production, where it will appear, and your proposed timeline. If possible, include how much of the track you need and whether the project includes advertising.','Music-use requests are handled individually. A link on this site, a stream, or a submission is not permission to use a recording. Ownership and approvals may involve collaborators or other rights holders.'])+tiles([('THE MUSIC','Choose the recording','Find the exact title and version in the catalog.','/music/'),('THE PROJECT','Prepare your brief','Describe the use, scope, platforms, and timing.','/project-brief/'),('THE CONVERSATION','Contact the artist','Send your request for review.','/connect/')])+'<div class="actions">'+button('Email a music-use inquiry',email('Music use / licensing inquiry'))+'</div>'))

publish('/booking/','Booking & interviews','APPEARANCES / PRESS / CONVERSATIONS','START THE<br><span>CONVERSATION.</span>','For interviews, appearances, and booking inquiries, share the details of your event or project.',section('<div class="editorial-layout"><div>'+prose('WHAT TO INCLUDE',['Introduce your organization, publication, or event. Include the proposed date, location or remote format, audience, and the role you have in mind for Mr. Blindbandit.','For interviews, mention the topic, expected length, recording format, and publication plans. For appearances, include timing, practical requirements, and a budget range where available.','Availability and arrangements are confirmed directly. No appearance or tour dates are announced on this page.'])+button('Email a booking inquiry',email('Booking / interview inquiry'))+'</div><aside class="side-note"><h3>Useful materials</h3><a href="/press/">Artist biography</a><a href="/press/artist-bio.txt" download>Download the short bio</a><a href="/story/">Read the full story</a><a href="/videos/">Watch featured videos</a></aside></div>'))

publish('/partnerships/','Creative partnerships','ARTISTS / CREATORS / BRANDS','BUILD SOMETHING<br><span>TOGETHER.</span>','Introduce an idea for a collaboration, creative project, or brand conversation.',section(prose('MAKE THE CONNECTION CLEAR',['Tell us who you are, what you want to create, and why the project connects with Mr. Blindbandit’s music or perspective. Include links that help explain your work.','A useful proposal identifies the creative role, intended audience, deliverables, and timeline. If there is a budget or a specific platform involved, include that context.','Partnership inquiries are considered individually. This page does not promise endorsement, promotional reach, or a particular commercial arrangement.'])+tiles([('MUSIC','A shared sound','Explore credited collaborations before introducing your idea.','/collaborators/'),('CREATIVE','A clear brief','Prepare your project details with the brief builder.','/project-brief/'),('CONTACT','Send your proposal','Reach the artist through the business contact.','/connect/')])+button('Email a partnership idea',email('Creative partnership proposal'))))

publish('/faq/','Frequently asked questions','HELP / QUICK ANSWERS','FIND YOUR<br><span>ANSWER.</span>','A quick guide to the artist, label, music, and ways to get involved.',section(faq([('Who is Mr. Blindbandit?','Kaeleb Heck is the artist and producer known as Mr. Blindbandit, and founder of Blindbandit Records. Read the Story page for more.'),('Where do I submit music?','Use the Submit page. It contains a music-submission form with listening-link and contact fields.'),('Can I join a mailing list?','Yes. The Join page collects optional signup consent for occasional artist and label updates.'),('Where can I hear full releases?','Use official Apple Music links on release cards or follow the Spotify and YouTube links. Platform playback rules and availability apply.'),('Are the collaborators signed to the label?','The collaborator features identify shared music and credited work. They do not indicate a label signing.'),('How can I support the artist?','The Support page includes the owner-provided Wise payment link and PayPal handle @internethorror.'),('How do I request an interview or a music license?','Use Booking for interviews and appearances, or Music use inquiries for licensing conversations. Both provide information to include in your email.'),('Can I pause the animations?','Yes. Use the Pause motion button in the footer. Audio and video players load only when you choose to use them.')])) )

publish('/privacy/','Privacy & form information','INFORMATION / CONTACT','YOUR DETAILS.<br><span>A CLEAR PURPOSE.</span>','How this website’s forms and external services are used.',section(prose('MUSIC SUBMISSIONS',['The music-submission form asks for your artist details, contact email, listening link, and project information. Those details are submitted through Jotform to the site owner for reviewing the music and contacting you about your submission. A music submission does not also register you for marketing updates.'])+prose('MAILING LIST',['The signup form collects your email, optional name and interests, and consent to receive occasional artist and label updates. To request removal or ask about information you submitted, email business@mrblindbandit.net.'])+prose('EXTERNAL SERVICES',['Jotform hosts the forms and stores submitted responses in the owner’s account. Spotify, Apple Music, and YouTube supply the requested music and video players. PayPal and Wise process payments on their own sites. These services may process technical information when their content loads; their own privacy terms apply.','The project brief builder prepares text in your browser. It does not send the information until you choose an external email action and send the message yourself.'])+prose('QUESTIONS OR CORRECTIONS',['Contact business@mrblindbandit.net to ask about a submission, correct information, or request removal from the mailing list. Do not include financial credentials or account passwords in a message or music submission.'])+'<div class="actions">'+button('Contact the artist','/connect/')+'</div>'))

groups=[('Listen',[('Music','/music/'),('Start listening','/discover/'),('Albums','/music/albums/'),('Singles','/music/singles/'),('EPs','/music/eps/'),('Videos','/videos/'),('Collaborators','/collaborators/')]),('Blindbandit Records',[('Label home','/label/'),('About the label','/label/about/'),('Founder & connections','/label/artists/'),('Submit music','/submit/'),('Submission guide','/submission-guide/'),('Submission FAQ','/submission-faq/')]),('Work together',[('Studio','/studio/'),('Project brief builder','/project-brief/'),('Music use inquiries','/licensing/'),('Booking & interviews','/booking/'),('Creative partnerships','/partnerships/'),('Press information','/press/')]),('Stay connected',[('Artist story','/story/'),('Community','/community/'),('Join the mailing list','/signup/'),('Support','/support/'),('Contact & socials','/connect/'),('FAQ','/faq/'),('Privacy','/privacy/')])]
publish('/explore/','Explore the website','THE COMPLETE DIRECTORY','YOUR WAY<br><span>INTO THE WORLD.</span>','Music, the label, and everything you need to connect with Mr. Blindbandit.',section('<label class="directory-search">Find a page<input type="search" id="directory-search" placeholder="Try submissions, music, booking…"></label><p id="directory-status" role="status"></p><div class="directory-grid">'+''.join('<section class="directory-group"><h2>'+title+'</h2>'+''.join('<a data-directory-item href="'+url+'">'+name+' <span aria-hidden="true">↗</span></a>' for name,url in items)+'</section>' for title,items in groups)+'</div>'))

# Extend the homepage and catalog without replacing their original content.
p=D/'index.html';s=p.read_text();addition=section(heading('More than the music','WELCOME TO<br>BLINDBANDIT RECORDS.')+tiles([('THE LABEL','Independent by design','Explore Blindbandit Records and the artist behind it.','/label/'),('FOR ARTISTS','Send your music','Introduce your project through the music submission form.','/submit/'),('FOR LISTENERS','Stay in the loop','Join the mailing list for occasional artist and label updates.','/signup/')]))
p.write_text(s.replace('</main>',addition+'</main>'))
p=D/'music/index.html';s=p.read_text();p.write_text(s.replace('<section class="shell catalog-section">','<div class="shell collection-nav">'+''.join('<a href="'+u+'">'+n+'</a>' for n,u in [('Listening guide','/discover/'),('Albums','/music/albums/'),('Singles','/music/singles/'),('EPs','/music/eps/')])+'</div><section class="shell catalog-section">'))
# Shared cross-section navigation and accurate canonical URLs.
for p in D.rglob('index.html'):
    s=p.read_text().replace('</header>','</header><div class="utility-nav shell"><a href="/label/">Blindbandit Records</a><a href="/submit/">Submit music</a><a href="/signup/">Join the mailing list</a><a href="/explore/">All pages</a></div>')
    p.write_text(s)
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://mrblindbandit.net'+url+'</loc></url>' for _,url in pages)+'</urlset>')
(ROOT/'data/pages.json').write_text(json.dumps([{'title':n,'path':u} for n,u in pages],indent=2))
print('Complete website:',len(pages),'pages')
