"""Structured public policies, child-safety standards, advertising disclosures, and contact directory."""
import html, re

EFFECTIVE='September 13, 2026'
ADDRESS='Purok 6-A, Mabuhay, Barangay Capungagan, Davao del Norte 8113, Philippines'
EMAILS={
 'Business':'business@mrblindbandit.net','Management':'management@mrblindbandit.net','Press and media':'press@mrblindbandit.net','Bookings and appearances':'bookings@mrblindbandit.net','Music submissions':'submissions@mrblindbandit.net','Licensing and sync':'licensing@mrblindbandit.net','Partnerships and sponsorships':'partnerships@mrblindbandit.net','Visitor support':'support@mrblindbandit.net','Accessibility':'accessibility@mrblindbandit.net','Privacy and data rights':'privacy@mrblindbandit.net','Security reports':'security@mrblindbandit.net','Legal notices':'legal@mrblindbandit.net','Copyright reports':'copyright@mrblindbandit.net','Child safety':'safety@mrblindbandit.net','Advertising':'advertising@mrblindbandit.net','Account notifications':'accounts@mrblindbandit.com'
}
def mail(key):
    address=EMAILS[key]
    return f'<a href="mailto:{address}">{address}</a>'

def policy_body(title,description,sections):
    toc=''.join(f'<a href="#policy-{i}">{html.escape(name)}</a>' for i,(name,_) in enumerate(sections,1))
    content=''.join(f'<section id="policy-{i}"><span class="policy-index">{i:02}</span><h2>{html.escape(name)}</h2><div class="legal-copy">{copy}</div></section>' for i,(name,copy) in enumerate(sections,1))
    links='<nav class="legal-crosslinks" aria-label="Legal and trust documents"><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/copyright/">Copyright</a><a href="/cookies/">Cookies</a><a href="/safety/">Child safety</a><a href="/advertising-disclosure/">Advertising</a><a href="/contact/">Contact directory</a></nav>'
    return f'<section class="shell policy-intro"><p class="eyebrow">INFORMATION / TRUST / ACCOUNTABILITY</p><h1>{html.escape(title)}</h1><p class="lede">{html.escape(description)}</p><p class="policy-date">Effective and last updated {EFFECTIVE}</p>{links}</section><div class="shell policy-layout"><aside><nav aria-label="On this page">{toc}</nav><a class="text-link" href="mailto:{EMAILS["Legal notices"]}">Contact the operator</a></aside><article>{content}<section class="legal-notice"><h2>Professional review notice</h2><p>These public documents explain current website practices and user expectations. They are not a substitute for advice from a lawyer or regulator about a particular person, contract, jurisdiction, or dispute. Applicable rights that cannot lawfully be waived remain available.</p></section></article></div>'

def add_legal_expansion(output,layout,pages):
    privacy=[
      ('Purpose and scope','<p>This Privacy Policy explains how the official Mr. Blindbandit website and Blindbandit Records public services collect, use, disclose, retain, and protect information. It covers public pages, contact and submission forms, the fan community, newsletters, browser utilities, and public-facing account entry points. A separate notice applies inside the invitation-only label portal.</p>'),
      ('Operator and contact',f'<p>The website is operated by Kaeleb Savon Heck, professionally known as Mr. Blindbandit, in connection with Blindbandit Records. Postal contact: {ADDRESS}. Philippine telephone: <a href="tel:+639626954905">+63 962 695 4905</a>. United States telephone: <a href="tel:+15409269791">+1 540 926 9791</a>. Privacy inquiries and rights requests should be sent to {mail("Privacy and data rights")}.</p>'),
      ('Information categories','<p>Depending on the feature used, information may include names, artist or organization names, email addresses, telephone numbers voluntarily supplied in a message, account identifiers, display names, posts, comments, votes, music metadata, project descriptions, listening links, uploaded files, support correspondence, consent choices, browser preferences, timestamps, security logs, IP addresses, user-agent information, and records necessary to answer or document a request.</p>'),
      ('Sources of information','<p>Information comes directly from visitors, invited account administrators, service providers involved in authentication or form delivery, and ordinary technical requests made by browsers. The site may also receive public professional information included in a link a visitor chooses to submit. The operator does not ask visitors to provide data obtained unlawfully or private information about another person without authorization.</p>'),
      ('Music submissions and uploads','<p>Demo and project submissions may include contact details, project metadata, permission confirmations, listening links, messages, and optional audio files. These materials are used to receive, secure, organize, evaluate, and respond to the submission. Submitting music does not transfer ownership, create a confidential relationship, guarantee review, or enroll the sender in unrelated marketing.</p>'),
      ('Professional inquiries and bookings','<p>Booking, licensing, press, collaboration, sponsorship, and partnership inquiries are used to understand the proposed project, evaluate availability, communicate terms, prevent fraud, and maintain necessary business records. A message is not acceptance of a booking, license, endorsement, or agreement.</p>'),
      ('Audio converter and browser utilities','<p>The audio converter processes the selected audio or video file in browser memory and does not upload that media to Blindbandit Records. When conversion begins, the browser downloads an FFmpeg WebAssembly engine from jsDelivr, which may receive IP address, browser, timing, and security information associated with that download. Other planners and calculators operate locally unless a page clearly states otherwise. Local-storage entries remain on the device until cleared by the visitor or browser.</p>'),
      ('Community contributions','<p>Community posts, comments, display names, and posting times are intended to be public and may be copied, quoted, or indexed. Reports, moderation notes, and sign-in identifiers are restricted to authorized processing. Do not post home addresses, private telephone numbers, passwords, government identifiers, financial credentials, intimate information, or another person’s personal information without permission.</p>'),
      ('Accounts and authentication','<p>Clerk and configured identity providers support account authentication. They may process identifiers, email addresses, profile details, device information, login events, cookies, multi-factor settings, and fraud signals under their own notices and the site’s configuration. Community identity and the invitation-only label portal have different permissions. Passwords and secret authentication keys must never be sent by ordinary email.</p>'),
      ('Purposes of processing','<p>Information is used to provide requested features; review submissions; respond to messages; maintain accounts and community conversations; administer label relationships; deliver notices; document permissions and consent; secure the service; detect abuse; comply with law; resolve disputes; enforce terms; improve accessibility and reliability; and operate advertising on eligible public pages.</p>'),
      ('Processing grounds','<p>Depending on the law and context, processing may rely on consent, steps requested before entering an agreement, performance of an agreement, compliance with legal obligations, protection of vital interests, and legitimate interests such as operating, securing, documenting, and improving the service. Where consent is the applicable basis, it may be withdrawn for future processing without affecting earlier lawful processing.</p>'),
      ('Service providers','<p>Relevant providers may include Sites and Cloudflare-backed hosting, databases and storage; Clerk and connected identity providers; Resend for requested transactional messages; form providers; Spotify, Apple Music, YouTube and other media services; jsDelivr for the optional conversion engine; PayPal and Wise for off-site payments; and Google for advertising. Providers process information according to their role, contracts, settings, and independent policies.</p>'),
      ('Advertising technologies','<p>Google AdSense code appears on eligible public pages. Google and advertising partners may use cookies, web beacons, IP addresses, device information, ad requests, and interactions to deliver, limit, personalize where permitted, measure, and protect advertising. No private portal page is intended to carry AdSense code. Read the <a href="/advertising-disclosure/">Advertising Disclosure</a> and <a href="https://policies.google.com/technologies/partner-sites">Google’s partner-sites explanation</a>.</p>'),
      ('Advertising choices and sensitive data','<p>The site does not intentionally send form contents, private messages, uploaded audio, label records, or account passwords to Google for ad targeting. Visitors may manage Google personalization through <a href="https://myadcenter.google.com/">My Ad Center</a> and may use consent controls where displayed. Personalized advertising must not be based on activity known to involve children under 13 or on sensitive categories prohibited by Google policy.</p>'),
      ('Cookies, storage, and embedded media','<p>Essential cookies may maintain authentication and security. Browser storage may remember accessibility, privacy, planner, or checklist preferences. Media providers may set or read identifiers when a player is loaded. Advertising providers may use cookies and related technologies subject to applicable consent requirements. The <a href="/cookies/">Cookies and Embedded Media Notice</a> provides more detail.</p>'),
      ('No general sale promise','<p>The operator does not sell music submissions, private messages, or label-portal records for money. Some privacy laws define “sale,” “sharing,” or targeted advertising broadly enough to include certain advertising technology. Where applicable, use the displayed consent or opt-out mechanism and contact the privacy address for additional requests. Requests are evaluated according to the visitor’s location and applicable law.</p>'),
      ('Retention framework','<p>Information is kept only as long as reasonably needed for its stated purpose, security, disputes, contracts, accounting, legal compliance, or documented operational needs. Unsuccessful or inactive inquiries may be deleted or de-identified when no longer needed. Account, contract, payment, audit, moderation, or legal records may require longer retention. Provider backups can persist for limited periods after deletion.</p>'),
      ('Security safeguards','<p>Safeguards include HTTPS, access controls, role restrictions, private routes, credential hashing or provider-managed authentication, session controls, rate limits, audit records, and restricted file delivery. Security is a shared responsibility: use unique credentials, enable multi-factor authentication where offered, sign out from shared devices, and report suspicious activity to '+mail('Security reports')+'. No internet service can guarantee absolute security.</p>'),
      ('International processing','<p>The operator is based in the Philippines and serves an international audience. Providers and recipients may process information in other countries, including the United States. Privacy protections and government-access rules can differ. Appropriate contractual, provider, consent, necessity, or legal mechanisms may be used where required.</p>'),
      ('Individual rights','<p>Depending on applicable law, a person may have rights to information, access, correction, deletion, restriction, objection, portability, withdrawal of consent, and complaint to a supervisory authority. A request should identify the relevant account, form, post, or transaction without attaching unnecessary identity documents. Reasonable verification may be required before disclosing or changing records.</p>'),
      ('Automated decisions','<p>The site does not currently make legal or similarly significant decisions about visitors solely through automated profiling. Spam controls, rate limits, security checks, and platform moderation signals may automatically restrict a request or session; visitors may contact support if they believe a legitimate action was blocked.</p>'),
      ('Children’s privacy','<p>The service is a general-audience music website and is not directed to children under 13. Children under 13 must not create accounts, publish community content, join the mailing list, or submit personal information. The operator does not knowingly use children’s activity for personalized advertising. A parent or guardian who believes a child supplied information should contact '+mail('Child safety')+' and '+mail('Privacy and data rights')+'. See the <a href="/safety/">Child Safety Policy</a>.</p>'),
      ('Incident response','<p>Suspected unauthorized access is assessed based on the information involved, likely harm, available evidence, and applicable notification duties. Visitors should report concerns privately and should not post exposed personal information in the community. Where required, affected people or authorities will receive appropriate notice.</p>'),
      ('Changes and prior versions','<p>This policy may change when services, providers, law, or operational practices change. The effective date identifies the current public version. Material changes may receive additional notice where appropriate. Continued use after an update does not replace consent where consent is legally required.</p>'),
      ('Questions and escalation','<p>Start with '+mail('Privacy and data rights')+'. Legal notices may be sent to '+mail('Legal notices')+', accessibility matters to '+mail('Accessibility')+', and security reports to '+mail('Security reports')+'. If a role address cannot receive a message, use '+mail('Business')+' as the fallback.</p>')
    ]
    copyright=[
      ('Ownership and attribution','<p>Music, sound recordings, compositions, artwork, photographs, video, writing, logos, code, and website materials may be protected by copyright, trademark, publicity, contract, or other rights. Rights belong to their respective owners. Credits and links identify creative relationships and do not imply that Blindbandit Records owns every referenced work.</p>'),
      ('Permitted personal use','<p>Visitors may access the site for lawful personal use and may share ordinary links to official public pages. Access does not grant a license to reproduce, distribute, sample, remix, synchronize, monetize, train a model on, sell, impersonate, or commercially exploit protected material.</p>'),
      ('Audio converter responsibility','<p>The audio converter is a format utility, not a downloading or circumvention service. Users must have the right to possess and convert the selected file. The tool must not be used to bypass digital rights management, copy protected streaming media, remove ownership information unlawfully, or facilitate infringement.</p>'),
      ('Music and composition rights','<p>A sound recording and its underlying composition can have different owners and permission requirements. A master-use license does not automatically provide publishing, mechanical, synchronization, sample, trademark, performer, or publicity rights. Confirm all necessary permissions in writing.</p>'),
      ('Submission rights','<p>Submitters retain ownership of their material and provide a limited permission to receive, store, secure, review, and respond to the submission. Submission alone does not create a license for public release, a transfer, a signing, a work-for-hire relationship, or a promise of confidentiality.</p>'),
      ('Community content','<p>Community participants must publish only content they created or are permitted to share. By posting, a participant permits the site to host, display, format, moderate, and technically reproduce the contribution for operating the community. This limited permission ends prospectively when content is removed, subject to necessary records and copies already made by others.</p>'),
      ('Permission requests','<p>For samples, sync, commercial use, media, artwork, brand, or press-image permission, email '+mail('Licensing and sync')+'. Identify the exact work, proposed use, media, audience, territory, term, release date, and budget. Silence is not consent.</p>'),
      ('Copyright reports','<p>Send a detailed report to '+mail('Copyright reports')+'. Include identification of the protected work, the exact URL, contact information, the basis for ownership or authorization, the disputed use, supporting references, and a good-faith statement. Do not include unrelated confidential information.</p>'),
      ('Review and preservation','<p>The operator may preserve relevant records, request clarification, temporarily restrict content, notify the contributor, restore content, or remove access after review. Complaint information may be shared as reasonably necessary to evaluate the dispute. Knowingly false notices can create liability.</p>'),
      ('Counter-information','<p>A person whose material was restricted may respond with the exact URL, identification of the removed material, the basis for permission or lawful use, contact details, and any legally required statements. This general process is not a claim that a statutory DMCA agent has been registered.</p>'),
      ('Repeat abuse','<p>Accounts or contributors associated with repeated, substantiated infringement or fraudulent complaints may be restricted or removed, considering context and available evidence. The operator may also act against impersonation, counterfeit activity, deceptive attribution, or unauthorized commercial use.</p>'),
      ('External platforms','<p>Content hosted by Spotify, YouTube, Apple Music, social networks, or another service must also be addressed through that provider’s process. This website can change its own pages and links but cannot remove content controlled by an independent platform.</p>')
    ]
    terms=[
      ('Acceptance and scope','<p>These Terms govern use of the public Mr. Blindbandit website, browser utilities, community, forms, and public account features. Separate signed agreements control label services, distribution, licensing, bookings, employment, and client relationships. If these Terms are not acceptable, do not use interactive features.</p>'),
      ('Eligibility','<p>Users must be able to enter the permissions they grant and must comply with applicable law. Children under 13 may browse general public content with appropriate supervision but must not create accounts, post, subscribe, submit personal information, or use interactive community features.</p>'),
      ('Account security','<p>Provide accurate information, protect authentication factors, and promptly report suspected compromise. Do not share invitation links, impersonate another person, create unauthorized accounts, or attempt to access private portal material. The operator may suspend sessions or require verification to protect accounts.</p>'),
      ('Acceptable use','<p>Do not harass, threaten, exploit, discriminate, spam, deceive, phish, distribute malware, evade controls, scrape protected records, interfere with service, artificially generate advertising interactions, publish private information, promote illegal activity, or infringe rights. The community rules and Child Safety Policy are incorporated into these expectations.</p>'),
      ('Audio converter','<p>The converter is offered as a local browser utility without a guarantee that every codec, metadata field, file, device, or browser will work. Outputs must be reviewed before professional delivery. Users are responsible for backups, rights, format requirements, loudness standards, and preserving original masters.</p>'),
      ('Community license and moderation','<p>Participants keep ownership of their posts while permitting the limited technical use necessary to operate and display them. Content may be reviewed, hidden, removed, preserved, or reported when needed for safety, law, rights, or enforcement. Moderation does not create a duty to monitor every contribution before publication.</p>'),
      ('Submissions and unsolicited material','<p>A music submission is an invitation to consider the material, not an offer, signing, fiduciary relationship, exclusive negotiation, or promise of review. Submitters should not send confidential business plans, identity documents, payment credentials, or material they lack authority to share.</p>'),
      ('Bookings, licensing, and services','<p>Availability, fees, scope, deliverables, travel, rights, credits, cancellation, and payment must be confirmed in a separate written agreement. A form, calendar request, draft, or email exchange is not final acceptance unless clearly stated by an authorized representative.</p>'),
      ('Advertising and endorsements','<p>Advertising may appear on eligible public pages. Ads are supplied by third parties and do not necessarily represent endorsement by Mr. Blindbandit or Blindbandit Records. Visitors must never be asked or encouraged to click advertisements to provide support. Sponsored or affiliate material will be identified where required.</p>'),
      ('External services','<p>Links and players may open independent services. Their availability, content, privacy, accessibility, subscriptions, fees, and terms are controlled by their providers. The presence of a link does not guarantee accuracy or endorsement.</p>'),
      ('Availability and changes','<p>Features can be changed, paused, or discontinued for maintenance, security, provider, legal, or operational reasons. The site is provided on an “as available” basis to the extent permitted by law. No promise of uninterrupted access, error-free conversion, response time, or permanent publication is made.</p>'),
      ('Disclaimers and liability','<p>Website content and utilities provide general information and practical assistance, not legal, financial, medical, tax, accounting, mastering, or emergency advice. To the extent permitted by applicable law, responsibility is limited for indirect or consequential loss arising from use, inability to use, third-party services, or user-supplied content. Mandatory consumer rights are not excluded.</p>'),
      ('Indemnity where lawful','<p>To the extent permitted by applicable law, a user may be responsible for claims and reasonable costs caused by that user’s unlawful content, rights violations, misuse, or material breach. This provision does not apply where prohibited and does not limit liability that cannot legally be limited.</p>'),
      ('Contact and updates','<p>Questions may be sent to '+mail('Legal notices')+'. Safety reports should go to '+mail('Child safety')+', copyright reports to '+mail('Copyright reports')+', and account problems to '+mail('Visitor support')+'. The posted effective date identifies the current version.</p>')
    ]
    cookies=[
      ('Scope','<p>This notice covers cookies, local browser storage, pixels, web beacons, request identifiers, and similar technologies used by the website and connected providers.</p>'),
      ('Essential sessions','<p>Authentication and security providers may use cookies to sign users in, keep sessions active, prevent misuse, remember security state, and route requests. Blocking essential storage can prevent account features from working.</p>'),
      ('Accessibility preferences','<p>The site stores motion, text-size, and contrast selections on the device so the chosen presentation can continue between pages. These preferences are not intended for advertising profiles.</p>'),
      ('Utility storage','<p>The daily planner and checklist maker may save entries locally in the visitor’s browser. Audio and video files selected for conversion are held in memory during processing and are not placed in site storage. Clearing browser data removes locally stored utility information.</p>'),
      ('Advertising','<p>Google and advertising partners may place or read cookies, use web beacons, process IP addresses, and receive ad and device identifiers for delivery, frequency control, personalization where permitted, measurement, and fraud prevention.</p>'),
      ('Consent controls','<p>Where law requires consent before non-essential advertising storage, visitors should receive and use the configured consent message. A policy page is a disclosure, not a substitute for a required consent interface. Choices can also be changed through browser controls and Google’s advertising settings.</p>'),
      ('Embedded players','<p>Spotify, Apple Music, YouTube, and other media providers may receive connection information and use their own storage when a player or external page is opened. Written content remains available without loading an embedded player where practical.</p>'),
      ('Audio engine delivery','<p>When conversion begins, jsDelivr receives an ordinary request for the FFmpeg scripts and WebAssembly engine. The selected audio file is processed locally and is not sent with that engine request.</p>'),
      ('Retention','<p>Cookie and identifier lifetimes vary by purpose and provider. Session cookies may expire when the browser closes; persistent cookies and local storage remain until their set duration, provider action, or visitor deletion.</p>'),
      ('Browser controls','<p>Visitors may block, delete, or restrict storage in browser settings. Private browsing can reduce persistence. Blocking technology may affect sign-in, media, preferences, advertising, or fraud protection.</p>'),
      ('Questions','<p>Contact '+mail('Privacy and data rights')+' for privacy questions and '+mail('Advertising')+' for advertising-specific questions.</p>')
    ]
    safety=[
      ('Commitment','<p>Mr. Blindbandit and Blindbandit Records prohibit child sexual abuse, exploitation, grooming, sextortion, trafficking, sexualization of minors, and any material that depicts or promotes such conduct. Child safety takes priority over engagement, publicity, or advertising.</p>'),
      ('Audience and age boundary','<p>This is a general-audience music service, not a child-directed service. Children under 13 must not create an account, post or comment, vote, subscribe, submit music, send personal information, or use private communication features. Parents and guardians should supervise younger visitors who browse general public content.</p>'),
      ('Prohibited conduct','<p>Users must not seek sexual contact with a minor; request, create, possess, trade, threaten to share, or distribute intimate imagery involving a minor; groom or manipulate a child; sexualize a minor; facilitate trafficking; arrange unsafe meetings; conceal exploitative conduct; or direct a child to an unsafe service.</p>'),
      ('Prohibited content','<p>Child sexual abuse material and content promoting, normalizing, instructing, or soliciting child exploitation are forbidden. So are sexualized depictions of minors, exploitative deepfakes or synthetic media, age-play presented as minors, sexual blackmail, and links or coded directions to prohibited material.</p>'),
      ('Personal information','<p>Do not publish a child’s home address, school, private contact details, live location, travel routine, identifying documents, intimate information, or another detail that could create a safety risk. Family members should share only information they are legally authorized to publish and should consider the child’s dignity and long-term privacy.</p>'),
      ('Reporting to the site','<p>Send urgent platform reports to '+mail('Child safety')+' with the relevant URL, account or display name, date and time, and a plain description. Do not download, copy, email, or forward suspected child sexual abuse imagery. Preserve the URL and other non-graphic context instead.</p>'),
      ('Immediate danger','<p>If a child may be in immediate danger, contact local emergency services or law enforcement first. The site’s email is not an emergency response line and is not continuously monitored.</p>'),
      ('External reporting','<p>Reports concerning online child sexual exploitation may also be made through the <a href="https://report.cybertip.org/">NCMEC CyberTipline</a> in the United States or the appropriate child-protection or law-enforcement authority in the relevant country. Use official reporting channels and follow their evidence instructions.</p>'),
      ('Moderation response','<p>The operator may promptly restrict access, preserve necessary records, remove content, suspend accounts, block repeat access, notify providers, and make reports to appropriate authorities or child-safety organizations when required or reasonably necessary.</p>'),
      ('Evidence handling','<p>Access to safety reports should be limited to people who need it. Records should be handled securely, with unnecessary copies avoided. The site will not ask a reporter to resend illegal imagery to prove a report.</p>'),
      ('No retaliation','<p>Good-faith safety reporting is protected from retaliation within the service. Knowingly false reports, harassment through reporting tools, or attempts to expose a child’s identity may result in restriction.</p>'),
      ('Advertising safeguards','<p>Pages or content involving child-safety reports, moderation, private accounts, or sensitive personal material are not intended for personalized advertising. The site is not directed to children and does not knowingly build advertising profiles from activity of users under 13.</p>'),
      ('Parents and guardians','<p>A parent or guardian may request review or deletion of information believed to have been supplied by a child by contacting '+mail('Child safety')+' and '+mail('Privacy and data rights')+'. Reasonable steps may be taken to verify the relationship and locate the information while minimizing additional collection.</p>'),
      ('Education and prevention','<p>Community rules encourage respectful, age-appropriate participation and prohibit grooming, coercion, sexual content, harassment, doxxing, dangerous challenges, illegal sales, and private-information exposure. Safety notices should use clear language that does not sensationalize abuse.</p>'),
      ('Policy enforcement','<p>Enforcement considers the content, context, available evidence, severity, immediacy, law, and platform obligations. Restoration may be considered after error, but content presenting a child-safety risk may remain restricted while a review is active.</p>'),
      ('Official references','<p>The <a href="https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa">FTC’s COPPA information</a> explains U.S. requirements for certain services directed to children under 13 or knowingly collecting their personal information. The <a href="https://support.google.com/publisherpolicies/answer/10502938">Google Publisher Policies</a> prohibit child sexual abuse and exploitation and impose advertising restrictions involving children.</p>')
    ]
    advertising=[
      ('Purpose','<p>This disclosure explains advertising technology, editorial independence, sponsorship labeling, and expectations for advertiser-friendly public pages.</p>'),
      ('Advertising provider','<p>Eligible public pages include Google AdSense code associated with publisher ID ca-pub-7238428274233485. The authorized seller declaration is published in the site’s ads.txt file.</p>'),
      ('Eligible pages','<p>Advertising is intended only for substantive public pages. Private portal pages, private account records, inboxes, submissions, security screens, and administrative workflows are excluded from advertising placement.</p>'),
      ('Data and technology','<p>Google and its partners may use cookies, web beacons, IP addresses, device information, identifiers, ad requests, and interactions for ad delivery, personalization where allowed, frequency control, reporting, security, and fraud prevention.</p>'),
      ('Visitor choices','<p>Visitors can manage Google ad personalization in <a href="https://myadcenter.google.com/">My Ad Center</a>, use a displayed consent message, and adjust browser storage settings. Non-personalized advertising can still use limited data for context, frequency, security, and measurement.</p>'),
      ('Editorial independence','<p>Advertisers do not receive authority to rewrite artist biography, music credits, reviews, community moderation, or policy decisions unless content is clearly identified as sponsored and the arrangement permits review. Ordinary ads do not imply endorsement.</p>'),
      ('Sponsored and affiliate content','<p>Paid sponsorships, gifted products, affiliate links, or other material relationships will be disclosed clearly where required. Compensation does not guarantee a positive statement or remove the obligation to be accurate.</p>'),
      ('Prohibited encouragement','<p>Visitors must never be asked to click advertisements, refresh pages repeatedly, generate artificial impressions, use automated traffic, or interact with ads as a form of support. Advertising must not be disguised as navigation, downloads, or site controls.</p>'),
      ('Placement standards','<p>Ads should not cover content, obstruct accessibility controls, imitate forms, appear inside modal navigation, create accidental clicks, outnumber substantive publisher content, or appear on empty, error, under-construction, or private screens.</p>'),
      ('Content standards','<p>The site prohibits illegal, infringing, deceptive, dangerous, exploitative, hateful, harassing, sexually explicit, child-endangering, malware, phishing, and rights-abusive content. Community material may be moderated or excluded from monetization when needed.</p>'),
      ('Children and sensitive information','<p>The site is not directed to children under 13. Known child activity and sensitive personal information must not be used for personalized advertising. Private submissions, account records, financial records, and safety reports are not advertising content.</p>'),
      ('Contact','<p>Advertising questions and disclosures may be sent to '+mail('Advertising')+'. Privacy questions go to '+mail('Privacy and data rights')+', safety reports to '+mail('Child safety')+', and suspected policy violations may also be reported through Google’s official channels.</p>')
    ]
    contact=[
      ('Official operator',f'<p>Kaeleb Savon Heck, professionally known as Mr. Blindbandit, operates this website in connection with Blindbandit Records. Business postal address: {ADDRESS}. Philippine phone: <a href="tel:+639626954905">+63 962 695 4905</a>. United States phone: <a href="tel:+15409269791">+1 540 926 9791</a>.</p>'),
      ('Department email directory','<div class="contact-directory">'+''.join(f'<div><h3>{html.escape(label)}</h3><a href="mailto:{address}">{address}</a></div>' for label,address in EMAILS.items())+'</div>'),
      ('Choose the right contact','<p>Use submissions for demos, licensing for sync or music-use permission, bookings for appearances, press for interviews, accessibility for barriers, privacy for data-rights requests, security for suspected compromise, copyright for rights disputes, safety for concerns involving a minor, and legal for formal notices. Use the business address when the category is uncertain.</p>'),
      ('Information to include','<p>Provide your name or organization, a reliable reply address, the relevant page or project, a concise description, important dates, and the action requested. Licensing and booking requests should include territory, media, timing, deliverables, and budget where relevant.</p>'),
      ('Information not to send','<p>Never email passwords, one-time codes, secret keys, complete payment-card data, government identity numbers, unnecessary health information, or illegal imagery. For child-safety reports, preserve URLs and non-graphic context without downloading or forwarding suspected abusive material.</p>'),
      ('Delivery and response','<p>Role addresses are published to route messages by subject. If a role address returns a delivery error, resend the message to '+mail('Business')+'. A message does not guarantee a response time, availability, acceptance, confidentiality agreement, license, booking, partnership, or legal outcome. Email before sending physical materials or visiting an address.</p>')
    ]
    documents=[('/privacy/','Privacy Policy','A detailed account of information practices across public pages, community, submissions, utilities, authentication, advertising, and the private portal.',privacy),('/copyright/','Copyright and Music Use Policy','Rights ownership, submissions, conversion responsibility, licensing requests, copyright reports, and review procedures.',copyright),('/terms/','Website Terms of Use','Rules for accounts, community participation, submissions, utilities, advertising, external services, and professional inquiries.',terms),('/cookies/','Cookies, Storage, and Embedded Media Notice','How authentication, accessibility preferences, local utilities, media, advertising, and browser controls use device technologies.',cookies),('/safety/','Child Safety Policy','Age boundaries, prohibited conduct, reporting, moderation, privacy, advertising safeguards, and emergency guidance.',safety),('/advertising-disclosure/','Advertising and Sponsorship Disclosure','How ads operate, how sponsored material is identified, which pages are excluded, and how visitors can control advertising choices.',advertising),('/contact/','Contact Directory','Official contact routes for business, music, press, bookings, licensing, privacy, legal, copyright, security, accessibility, advertising, and child safety.',contact)]
    for route,title,description,sections in documents:
        layout(route,title,description,policy_body(title,description,sections))
        page=output/route.strip('/')/'index.html'
        source=page.read_text().replace('<body>','<body class="public-modern legal-page">',1).replace('<link rel="stylesheet" href="/styles.css">','<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/public-modern.css">',1)
        page.write_text(source)
        if not any(path==route for _,path in pages):pages.append((title,route))
    safety_notice='<section class="shell section safety-notice"><p class="eyebrow">COMMUNITY SAFETY</p><h2>Protect children and report concerns.</h2><p>Users under 13 may not create accounts, post, comment, subscribe, or submit personal information. Grooming, sextortion, sexualization, trafficking, exploitative imagery, and disclosure of a child’s private information are prohibited.</p><div class="actions"><a class="button" href="/safety/">Read the Child Safety Policy</a><a class="text-link" href="mailto:safety@mrblindbandit.net">Report a safety concern</a></div></section>'
    for rel in ('community/index.html','community/guidelines/index.html'):
        page=output/rel
        if page.exists():page.write_text(page.read_text().replace('</main>',safety_notice+'</main>',1))
