"""Stripe-hosted one-time support and private account overview."""
def add_payment_pages(output,layout,pages):
    definitions=[
      ('/support/card/','Support by card','Support independent music and accessible creator tools.', '''<section class="shell policy-intro"><p class="eyebrow">MR. BLINDBANDIT / SUPPORT</p><h1>Support the next creation</h1><p class="lede">Choose a one-time amount to support Mr. Blindbandit and Blindbandit Records.</p><form class="label-form" data-stripe-checkout><fieldset><legend>Suggested support amounts in US dollars</legend><button type="button" data-support-amount="5">$5</button> <button type="button" data-support-amount="10">$10</button> <button type="button" data-support-amount="25">$25</button> <button type="button" data-support-amount="50">$50</button></fieldset><label>Your amount in USD<input name="amount" type="number" min="2" max="500" step="0.01" value="10" inputmode="decimal" required aria-describedby="amount-help"></label><p id="amount-help">Choose $2–$500 USD. This is one payment, not a subscription. Your bank may apply currency-conversion charges.</p><label><input name="agree" type="checkbox" required> I understand this is voluntary support and accept the <a href="/payments/terms/">support payment terms</a>.</label><button class="button" type="submit">Continue to secure Stripe checkout</button><p role="status" aria-live="polite"></p></form><p>You enter payment details on Stripe’s hosted checkout. Available payment methods are shown there. Supporting does not purchase a record deal, royalties, ownership, guaranteed services or a charitable tax deduction.</p><p><a href="/support/">PayPal and Wise options</a> · <a href="/payments/help/">Payment help</a></p></section>'''),
      ('/support/payment/','Check your support payment','Check the current result of your recent Stripe checkout.', '''<section class="shell policy-intro"><h1>Your support payment</h1><div data-stripe-receipt><p role="status" aria-live="polite">Checking your recent checkout securely…</p><dl data-payment-summary></dl><button type="button" data-check-payment>Check payment status again</button></div><p>A return to this page alone does not prove payment. The result above is retrieved from Stripe. If a payment is processing, check again before paying a second time.</p><p><a href="/payments/help/">Get payment help</a> · <a href="/support/">Return to support</a></p></section>'''),
      ('/payments/help/','Payment help','Help with support payments, confirmations and payment issues.', '''<section class="shell policy-intro"><h1>Payment help</h1><h2>Did my payment complete?</h2><p>Use <a href="/support/payment/">Check your recent payment</a> in the browser where you opened checkout. Status is checked with Stripe. Processing means the payment is not yet confirmed.</p><h2>I closed checkout</h2><p>You can return to the support page. If you submitted payment details, check your confirmation and payment status before starting again.</p><h2>My card was declined</h2><p>Follow the message in Stripe checkout or contact your bank. You can use another eligible method displayed by Stripe, or use the existing PayPal and Wise links.</p><h2>Wrong amount, duplicate payment or refund request</h2><p>Contact <a href="mailto:support@mrblindbandit.net">support@mrblindbandit.net</a> with the date, amount, currency and payment reference. Never send full card numbers, security codes or passwords. Requests are reviewed individually; applicable mandatory rights remain.</p><h2>Can I pay monthly?</h2><p>This checkout accepts one-time support only. It does not enroll you in recurring billing.</p><h2>What is shown in the label portal?</h2><p>Authorized administrators can review Stripe connection status, available and pending Stripe balances, and this website’s support checkout activity. Support is not automatically allocated as artist royalties.</p><p><a href="/payments/terms/">Support payment terms</a> · <a href="/privacy/">Privacy Policy</a></p></section>'''),
      ('/payments/terms/','Support payment terms','Terms for voluntary one-time payments through Stripe.', '''<section class="shell policy-intro"><h1>Support payment terms</h1><p>Effective September 14, 2026.</p><h2>Recipient and purpose</h2><p>Payments support Kaeleb Savon Heck, professionally known as Mr. Blindbandit, and Blindbandit Records. Address: Purok 6-A, Mabuhay, Barangay Capungagan, Davao del Norte 8113, Philippines. Contact: support@mrblindbandit.net.</p><h2>One-time voluntary support</h2><p>You choose the amount in USD and review it on Stripe’s hosted checkout before authorizing payment. This does not create a subscription, buy goods or services, create ownership or royalty rights, guarantee a release or label relationship, or represent a tax-deductible charitable donation.</p><h2>Payment processing</h2><p>Stripe processes payment information on its own hosted checkout. The website receives payment references, amount, currency, status and associated transaction information. Card credentials are not collected by ordinary site forms. Stripe and your financial institution may have their own terms, fees and currency-conversion practices.</p><h2>Authority</h2><p>Only authorize a payment using a method you are permitted to use and when you have legal capacity or the required representative’s authorization.</p><h2>Errors and refunds</h2><p>For an accidental amount, suspected duplicate or other payment issue, contact support with the reference, date and amount. Refund requests are reviewed according to the circumstances and applicable law. Nothing here limits a remedy or payment-dispute right that cannot lawfully be excluded. A request does not itself issue a refund.</p><h2>Confirmation and records</h2><p>The payment-status page checks Stripe’s current response. Do not treat a browser redirect as confirmation. Transaction records may be retained for accounting, payment administration, fraud prevention, dispute handling and legal obligations.</p><h2>Privacy and help</h2><p>Read the <a href="/privacy/">Privacy Policy</a> and <a href="https://stripe.com/privacy">Stripe Privacy Policy</a>. Privacy questions: privacy@mrblindbandit.net. For support, use <a href="/payments/help/">Payment help</a>.</p></section>'''),
    ]
    for route,title,description,body in definitions:
        layout(route,title,description,body)
        path=output/route.strip('/')/'index.html';markup=path.read_text().replace('<body>','<body class="public-modern legal-page">').replace('</head>','<link rel="stylesheet" href="/public-modern.css"><meta name="referrer" content="no-referrer"></head>').replace('</body>','<script src="/payments.js" defer></script></body>');path.write_text(markup);pages.append((title,route))
    p=output/'support/index.html';markup=p.read_text();p.write_text(markup.replace('</main>','<section class="shell section"><h2>Support with Stripe</h2><p>Choose a one-time amount and pay on Stripe’s secure checkout.</p><a class="button" href="/support/card/" data-full-navigation>Support by card</a> <a href="/payments/help/">Payment help</a></section></main>'))
    for path in output.rglob('index.html'):
        markup=path.read_text()
        if '/portal/' in str(path):markup=markup.replace('</body>','<script src="/payments.js" defer></script></body>')
        path.write_text(markup)
    p=output/'privacy/index.html';markup=p.read_text();p.write_text(markup.replace('</main>','<section class="shell legal-copy"><h2>Stripe support payments — added September 14, 2026</h2><p>Stripe receives payment details through hosted checkout. The website requests one-time support sessions and accesses transaction references, amounts, currencies and payment status for payment administration. Authorized administrators can view Stripe account balances and site checkout activity. An essential, signed, HttpOnly cookie keeps the latest checkout reference for up to 24 hours so this browser can check its result. This does not subscribe you to marketing or make your payment public. No raw card credentials are collected by this website’s forms.</p><p><a href="/payments/terms/">Support payment terms</a> · <a href="https://stripe.com/privacy">Stripe Privacy Policy</a></p></section></main>'))
