import re,html,json

def enhance(root,output,layout,pages):
 def add(path,title,description,body):
  layout(path,title,description,'<article class="shell policy-body"><p class="eyebrow">MR. BLINDBANDIT / OFFICIAL WEBSITE</p><h1>'+html.escape(title)+'</h1>'+body+'</article>')
  if not any(u==path for _,u in pages):pages.append((title,path))
 story=json.loads((root/'data/master-story.json').read_text())
 add('/story/',story['title'],'Kaeleb Savon Heck tells his complete first-person story of blindness, music, independent travel, and life with Emma in the Philippines.','<p>By Kaeleb Savon Heck · Mr. Blindbandit</p>'+''.join('<p>'+html.escape(p)+'</p>' for p in story['paragraphs'])+'<p><a href="/biography/">Read the reference biography</a> · <a href="/music/">Listen to my music</a> · <a href="/accessibility/">Accessibility</a></p>')
 bio=json.loads((root/'data/master-biography.json').read_text())
 add('/biography/','Who Is Mr. Blindbandit?','The artist-supplied biography of Kaeleb Savon Heck: early life, music, accessible creation, international travel and life in the Philippines.','<p>This reference biography is published by the artist using his supplied account. It is not a Wikipedia article or an independently reported biography.</p>'+''.join('<section><h2>'+html.escape(h)+'</h2><p>'+html.escape(p)+'</p></section>' for h,p in bio)+'<h2>Explore the artist’s work</h2><p><a href="/story/">The complete first-person Philippines story</a> · <a href="/music/">Music and discography</a> · <a href="/label/">Blindbandit Records</a> · <a href="/press/">Press information</a> · <a href="/contact/">Contact</a></p>')
 add('/news/','News & publications','Official articles and announcements from Mr. Blindbandit and Blindbandit Records.','<p>Music, independent creation, and updates from the artist and label.</p><p><a href="/story/">Read the complete Philippines story</a> · <a href="/biography/">Who is Mr. Blindbandit?</a></p>')
 add('/reading-room/','Reading room','Selected RSS and Atom feed headlines, excerpts and links to original publishers.','<p>Selected headlines from feeds approved by the label. Read the original publisher for each full article.</p><div data-feed-room><p role="status">Loading selected articles…</p></div>')
 departments=['General','Business','Sponsorships','Press','Bookings','Licensing','Submissions','Legal','Privacy','Accessibility','Copyright','Security','Support','Partnerships','Webmaster']
 contact=output/'contact/index.html';s=contact.read_text();cards=''.join('<article><h3>'+d+'</h3><p>'+({'Copyright':'Identify the work and disputed URL, describe your authority and include supporting evidence.','Privacy':'Tell us whether you need access, correction or deletion. Do not send identity documents in the initial message.','Security':'Describe the issue privately; do not post passwords or exploit details in the community.','Submissions':'Use the music submission form for a listening link or audio file.'}.get(d,'Describe your request, timing and the best way to reach you.'))+'</p><a href="/contact/forms/?department='+d.lower()+'">Contact '+d.lower()+'</a></article>' for d in departments)
 s=s.replace('</main>','<section class="shell section"><h2>Choose a department</h2><p>Department forms arrive in the protected label inbox. Our published email contact is <a href="mailto:business@mrblindbandit.net">business@mrblindbandit.net</a>. We do not promise a response deadline or publish unverified department mailboxes.</p><div class="cards">'+cards+'</div></section></main>');contact.write_text(s)
 for route in ['privacy','cookies']:
  p=output/route/'index.html';s=p.read_text();s=s.replace('</main>','<section class="shell policy-body"><h2>Privacy choices on this device</h2><p>Use Privacy choices in the footer to accept all, reject nonessential storage, or choose individual categories. Essential sign-in and security storage cannot be disabled here. Analytics is not currently configured. The Google AdSense verification script is present on public pages, while this website creates advertising placements only when the advertising service is enabled and you have opted in. Optional embedded media is loaded only after you allow it. Preferences are stored on this browser for 180 days; you can withdraw them at any time.</p><button type="button" data-privacy-choices>Manage privacy choices</button><h2>Submission and security records</h2><p>We store form details, consent time, source page, uploaded audio, reference numbers, thread status, internal notes, assignments, replies, and email request status. Resend receives the email recipient and message content for acknowledgments, notifications, replies, invitations and security verification. Acceptance by Resend does not prove inbox delivery. Administrators use an additional email verification code; hashed one-time recovery codes and verification records support account protection.</p><p>Authorized owners and administrators can access submissions. Client accounts do not have access. Submission records remain until deleted by an administrator; there is no automatic deletion schedule. Contact business@mrblindbandit.net for access, correction or deletion requests. Verification codes expire after 10 minutes and verification sessions after 12 hours. Public RSS excerpts link to third-party publishers, whose own privacy terms apply when you visit them.</p></section></main>');p.write_text(s)
 p=output/'copyright/index.html';s=p.read_text().replace('</main>','<section class="shell policy-body"><h2>Copyright notice and review</h2><p>Send a report through <a href="/contact/forms/?department=copyright">the copyright contact form</a>. Identify the protected work, the exact disputed page or file, your relationship to the rights holder, contact details, and an explanation of the issue with supporting evidence links. Do not submit passwords or confidential documents through public posts.</p><p>Reports receive a private reference and can be assigned, reviewed, replied to and closed in the label inbox. We may request further information, remove or restrict material where appropriate, or explain the outcome. A report is not an automatic legal determination. We do not claim ownership of third-party music, artwork, RSS material, or trademarks merely because they are linked or embedded here.</p></section></main>');p.write_text(s)
 p=output/'index.html';s=p.read_text().replace('</main>','<section class="shell section"><h2>Meet the person behind the music</h2><p>Mr. Blindbandit is Kaeleb Savon Heck, an American blind music creator and digital artist from Virginia, now building his life and creative work in the Philippines. Sound, accessible technology and personal experience shape his music.</p><p><a href="/biography/">Who is Mr. Blindbandit?</a> · <a href="/story/">I didn’t see the Philippines. I heard it.</a> · <a href="/music/">Explore the music</a> · <a href="/news/">Latest publications</a></p></section></main>');p.write_text(s)
 # Phase 1 identity links and Phase 2 disclosures follow actual implemented features.
 for route in ['music','accessibility','contact','story','press']:
  p=output/route/'index.html';markup=p.read_text();links='<nav class="shell section" aria-label="Artist and website information"><a href="/biography/">Who is Mr. Blindbandit?</a> · <a href="/story/">The complete Philippines story</a> · <a href="/videos/">Videos</a> · <a href="/press/">Press</a> · <a href="/news/">News</a> · <a href="/contact/">Contact</a></nav>';p.write_text(markup.replace('</main>',links+'</main>'))
 p=output/'privacy/index.html';markup=p.read_text().replace('Contact business@mrblindbandit.net for access, correction or deletion requests.','Contact privacy@mrblindbandit.net for access, correction or deletion requests.');markup=markup.replace('</main>','<section class="shell policy-body"><h2>Account notes, security methods and browser preferences</h2><p>Personal portal notes are stored with the account that created them; other portal users cannot open them through the portal. Shared reply templates are available to authorized label administrators. Optional authenticator secrets are encrypted, and recovery codes are stored as hashes. New verified administrator sessions trigger a security email that can include the browser description, time and IP address. These details are not a precise location. Repeated incorrect email codes can trigger a security warning. Remembered browser labels expire after 90 days and can be renamed or forgotten in Account &amp; security; they never bypass verification.</p><p>The public release checklist saves selected steps in this browser only. Resetting that checklist clears its saved progress. Language choices and accessibility preferences also use browser storage. Search terms are sent to the server to find public content and may appear in hosting request logs; do not put private information into public search.</p><h2>Contact and choices</h2><p><a href="mailto:privacy@mrblindbandit.net">Privacy requests</a> · <a href="mailto:legal@mrblindbandit.net">Formal legal correspondence</a> · <a href="mailto:security@mrblindbandit.net">Security concerns</a> · <a href="/cookies/">Cookies</a> · <a href="/terms/">Terms</a> · <a href="/copyright/">Copyright</a> · <a href="/accessibility/">Accessibility</a></p><button data-privacy-choices>Manage privacy choices</button></section></main>');p.write_text(markup)
 p=output/'cookies/index.html';markup=p.read_text().replace('</main>','<section class="shell policy-body"><h2>Saved tools and advertising controls</h2><p>Release-checklist progress, language choice and accessibility settings are stored in your browser when you use those tools. You can reset the checklist on its page or clear site data in your browser. Administrator-configured ad placements are limited to selected music, video, news and article pages. Ad requests require advertising consent and an enabled, verified consent-platform integration; saving placement settings alone does not activate ads.</p></section></main>');p.write_text(markup)
 from priority_next import enhance_next
 enhance_next(root,output,layout,pages)
 for p in output.rglob('index.html'):
  s=p.read_text()
  if '/portal/' not in str(p) and '/owner/' not in str(p):
   s=s.replace('</footer>','<button type="button" data-privacy-choices>Privacy choices</button><a href="/news/">News</a><a href="/reading-room/">Reading room</a></footer>')
   s=s.replace('</head>','<script src="/consent.js" defer></script><script src="/reading-room.js" defer></script></head>')
  p.write_text(s)
