import html,json,zipfile

def enhance_next(root,output,layout,pages):
 departments=['info','business','sponsorships','press','bookings','licensing','submissions','legal','privacy','accessibility','copyright','security','support','partnerships','webmaster']
 def add(path,title,description,body):
  layout(path,title,description,'<article class="shell policy-body"><h1>'+html.escape(title)+'</h1>'+body+'</article>')
  if not any(u==path for _,u in pages):pages.append((title,path))
 add('/search/','Search the site','Search public pages and published stories from Mr. Blindbandit.','<p>Find music, artist information and stories.</p><form class="label-form" method="get" action="/search/"><label>Search words<input name="q" type="search" minlength="2" maxlength="100" required></label><button>Search</button></form>')
 checks=['Confirm who owns the master recording','List all writers, producers and featured artists','Check the spelling of artist names and track titles','Prepare the final audio file requested by your distributor','Prepare artwork you have permission to use','Resolve sample, beat and third-party permissions','Agree contributor credits and ownership splits','Choose a proposed release date','Collect your streaming and social profile links','Prepare a private listening link that works','Write a short description of your release','Review the submission before sending']
 body='<p>Use this checklist to organize a release before contacting the label. Your selections stay in this browser; they are not sent to Blindbandit Records.</p><section data-release-checklist><progress max="12" value="0" aria-label="Release preparation progress"></progress><p role="status">Checklist ready. Enable JavaScript to save progress and download a copy.</p><fieldset class="workspace-checklist"><legend>Prepare your release</legend>'+''.join('<label><input type="checkbox" value="'+str(i)+'"> '+html.escape(c)+'</label>' for i,c in enumerate(checks))+'</fieldset><div class="actions"><button data-download>Download my checklist</button><button data-reset>Reset progress</button></div></section><h2>Ready to introduce your music?</h2><p>Completing the checklist does not submit your music or guarantee distribution. Review any proposed terms before agreeing to work together.</p><p><a class="button" href="/submit/">Submit music</a> · <a href="/contact/">Ask a question</a> · <a href="/label/">About the label</a></p><script src="/release-checklist.js" defer></script>'
 add('/release-checklist/','Prepare your release','An interactive release preparation checklist with saved progress and a downloadable copy.',body)
 for route in ['index.html','submit/index.html','label/index.html']:
  p=output/route;s=p.read_text();p.write_text(s.replace('</main>','<section class="shell section"><h2>Tools for your next step</h2><p><a href="/search/">Search the website</a> · <a href="/release-checklist/">Prepare your release with an interactive checklist</a></p></section></main>'))
 p=output/'accessibility/index.html';s=p.read_text();s=s.replace('</main>','<section class="shell policy-body"><h2>Accessibility status</h2><p>Our target is WCAG 2.2 Level AA across the artist site and private label portal. Work includes keyboard skip links, visible focus, form-error summaries, verification-code autofill, motion and text controls, and narrow-screen layouts. We have not completed a full conformance evaluation.</p><h2>Known limitations and assistance</h2><p>Third-party music and video players, captions and audio descriptions, uploaded contracts and other documents, and complete screen-reader workflows still need individual review. Contact <a href="mailto:accessibility@mrblindbandit.net">accessibility@mrblindbandit.net</a> for help or an alternative format. Include the page address, device, browser, assistive technology and the action that was blocked. Do not send passwords or verification codes.</p></section></main>');p.write_text(s)
 p=output/'privacy/index.html';s=p.read_text();s=s.replace('</main>','<section class="shell policy-body"><h2>Optional website translation</h2><p>Our hosted Filipino and Cebuano pages do not send your content to a translation provider. Separately labeled Google Translate links open Google with the public page address only, without query parameters. Google processes those requests under its own privacy policy. We do not send private portal pages, account tokens or form values through those links. Automatic translations can contain errors.</p></section></main>');p.write_text(s)
 p=output/'contact/index.html';s=p.read_text();s=s.replace('We do not promise a response deadline or publish unverified department mailboxes.','Choose the relevant department below. Response times depend on the request.')
 s=s.replace('</main>','<section class="shell section"><h2>Department email directory</h2><p>These public contact addresses are managed by the artist. Include your project, timeline and relevant reference number.</p><dl>'+''.join('<dt>'+d.capitalize()+'</dt><dd><a href="mailto:'+d+'@mrblindbandit.net">'+d+'@mrblindbandit.net</a></dd>' for d in departments)+'</dl></section></main>');p.write_text(s)
 for route in ['privacy','copyright']:
  p=output/route/'index.html';s=p.read_text().replace('</main>','<section class="shell policy-body"><h2>Dedicated contact</h2><p><a href="mailto:'+route+'@mrblindbandit.net">'+route+'@mrblindbandit.net</a></p></section></main>');p.write_text(s)
 for department,title,prompt in [('bookings','Booking inquiries','Include event date, venue or remote format, location, audience, accessibility arrangements and budget.'),('licensing','Music licensing','Identify the track, intended media, territory, term, budget and the rights you are requesting.'),('sponsorships','Sponsorship opportunities','Describe the brand, campaign, proposed deliverables, timing, audience and budget.'),('partnerships','Creative partnerships','Describe your organization, proposal, responsibilities, timeline and what you hope to create together.')]:
  body='<p>'+prompt+'</p><p>Email <a href="mailto:'+department+'@mrblindbandit.net">'+department+'@mrblindbandit.net</a>, or use this private form.</p><form class="brief-form native-form" data-native-form="inquiry"><input type="hidden" name="category" value="'+department+'"><label>Name / organization<input name="name" required maxlength="120"></label><label>Email<input type="email" name="email" required maxlength="254"></label><label>Project details<textarea name="message" required maxlength="4000" rows="8"></textarea></label><label>Relevant link (optional)<input name="reference" type="url" maxlength="1500"></label><label><input type="checkbox" name="consent" required> I agree to be contacted about this inquiry. This does not subscribe me to marketing emails.</label><label class="bot-field" aria-hidden="true">Leave empty<input name="website" tabindex="-1" autocomplete="off"></label><button class="button" type="submit">Send '+department+' inquiry</button><p role="status" aria-live="polite"></p></form><p>Submitting does not reserve availability, grant rights or create an agreement. Keep your reference for follow-up.</p><script src="/forms.js" defer></script>'
  add('/contact/'+department+'/',title,prompt,body)
  route={'bookings':'booking','licensing':'licensing','sponsorships':'partnerships','partnerships':'partnerships'}[department]
  p=output/route/'index.html'
  if p.exists():p.write_text(p.read_text().replace('</main>','<section class="shell section"><a class="button" href="/contact/'+department+'/">'+title+'</a></section></main>'))
 bio=json.loads((root/'data/master-biography.json').read_text());short='Mr. Blindbandit is Kaeleb Savon Heck, an American blind music creator and digital artist born in Salem, Virginia. Based in the Philippines, he works with accessible technology and screen readers to create music shaped by sound, memory and movement.'
 medium=short+'\n\n'+bio[2][1]+'\n\nHis first-person story, “I Didn’t See the Philippines for the First Time. I Heard It.”, recounts independent travel, meeting Emma and building a life in the Philippines.'
 long='\n\n'.join(h+'\n'+text for h,text in bio)
 files=[]
 for size,text in [('short',short),('medium',medium),('long',long)]:
  name='bio-'+size+'.txt';p=output/'press'/name;p.write_text('Mr. Blindbandit — '+size+' artist biography\nArtist-supplied information\n\n'+text+'\n\nPress: press@mrblindbandit.net\nBusiness: business@mrblindbandit.net\nOfficial website: https://mrblindbandit.net\n');files.append(p)
 instructions=output/'press/press-kit-readme.txt';instructions.write_text('Mr. Blindbandit — electronic press kit\n\nBiographies are artist-supplied. The included portrait is the image used by the artist on the official site; confirm intended usage and any credit with press@mrblindbandit.net. No ownership of third-party releases or artwork is transferred.\n\nBiography: https://mrblindbandit.net/biography/\nStory: https://mrblindbandit.net/story/\nMusic: https://mrblindbandit.net/music/\nVideos: https://mrblindbandit.net/videos/\nPress: press@mrblindbandit.net\nBusiness: business@mrblindbandit.net\n');files.append(instructions)
 with zipfile.ZipFile(output/'press/mr-blindbandit-press-kit.zip','w',zipfile.ZIP_DEFLATED) as z:
  for p in files:z.write(p,p.name)
  z.write(output/'assets/artist.jpg','artist-portrait.jpg')
  z.write(output/'assets/blindbandit-records-gold.jpeg','blindbandit-records-logo.jpeg')
 p=output/'press/index.html';s=p.read_text().replace('mailto:business@mrblindbandit.net','mailto:press@mrblindbandit.net');s=s.replace('</main>','<section class="shell policy-body"><h2>Download the electronic press kit</h2><p>Three biography lengths, the official portrait and label logo, contact information and usage guidance in one download.</p><a class="button" href="/press/mr-blindbandit-press-kit.zip" download>Download press kit ZIP</a><p><a href="/assets/blindbandit-records-gold.jpeg" download>Download the official label logo</a></p>'+''.join('<h3>'+size.capitalize()+' biography</h3><p>'+html.escape(text).replace('\n\n','</p><p>')+'</p><a href="/press/bio-'+size+'.txt" download>Download '+size+' biography</a>' for size,text in [('short',short),('medium',medium),('long',long)])+'<p><a href="/biography/">Who is Mr. Blindbandit?</a> · <a href="/music/">Music</a> · <a href="/videos/">Videos</a> · <a href="mailto:press@mrblindbandit.net">Press inquiries</a> · <a href="mailto:business@mrblindbandit.net">Business inquiries</a></p></section></main>');p.write_text(s)
 add('/feeds/','Follow with RSS','Subscribe to official news and music release feeds from Mr. Blindbandit.','<p>Use these addresses in your preferred feed reader. News feeds update when public articles are published. The music feed reflects the website’s release catalog.</p><ul><li><a href="/feeds/news.xml">Official news — RSS</a></li><li><a href="/feeds/news.atom">Official news — Atom</a></li><li><a href="/feeds/music.xml">Music releases — RSS</a></li></ul>')
 add('/es/','Mr. Blindbandit — Música e historias','Sitio oficial de Mr. Blindbandit: música, historias personales y Blindbandit Records.','<p>Bienvenido al sitio oficial de Mr. Blindbandit, el proyecto musical de Kaeleb Savon Heck.</p><h2>Descubre su música</h2><p>Explora sus lanzamientos, conoce Blindbandit Records y descubre las historias que inspiran su trabajo.</p><p><a href="/music/">Escuchar música (en inglés)</a> · <a href="/biography/">Biografía (en inglés)</a> · <a href="/story/">Historia personal (en inglés)</a> · <a href="/contact/">Contacto (en inglés)</a></p><p>Esta introducción está disponible en español. Las páginas enlazadas y la navegación principal están en inglés.</p>')
 p=output/'es/index.html';p.write_text(p.read_text().replace('<html lang="en">','<html lang="es">'))
 for p in output.rglob('index.html'):
  if '/portal/' in str(p) or '/owner/' in str(p):continue
  s=p.read_text();s=s.replace('</head>','<link rel="alternate" type="application/rss+xml" title="Mr. Blindbandit news" href="https://mrblindbandit.net/feeds/news.xml"><link rel="alternate" type="application/atom+xml" title="Mr. Blindbandit news — Atom" href="https://mrblindbandit.net/feeds/news.atom"><script src="/languages.js?v=phase29" defer></script></head>')
  if '/forms.js' not in s:s=s.replace('</head>','<script src="/forms.js" defer></script></head>')
  s=s.replace('</footer>','<a href="/feeds/">RSS feeds</a><nav aria-label="Language"><a lang="en" hreflang="en" href="/" data-language="en">English</a> · <a lang="es" hreflang="es" href="/es/" data-language="es">Español</a> · <a href="/fil/" lang="fil" data-language="fil">Filipino</a> · <a href="/ceb/" lang="ceb" data-language="ceb">Cebuano</a></nav></footer>')
  s=s.replace('</header>','<nav class="shell language-choice" aria-label="Site language"><a href="/" lang="en" data-language="en">English</a> · <a href="/es/" lang="es" data-language="es">Español</a> · <a href="/fil/" lang="fil" data-language="fil">Filipino</a> · <a href="/ceb/" lang="ceb" data-language="ceb">Cebuano</a></nav></header>')
  if p in [output/'index.html',output/'es/index.html']:s=s.replace('</head>','<link rel="alternate" hreflang="en" href="https://mrblindbandit.net/"><link rel="alternate" hreflang="es" href="https://mrblindbandit.net/es/"><link rel="alternate" hreflang="x-default" href="https://mrblindbandit.net/"></head>')
  if not any('/'+prefix+'/' in str(p) for prefix in ['portal','owner','community/account','community/dashboard','community/moderation']):
   route='/' if p==output/'index.html' else '/'+str(p.parent.relative_to(output))+'/'
   from urllib.parse import urlencode
   links=' · '.join('<a data-public-translate="'+l+'" href="https://translate.google.com/translate?'+html.escape(urlencode({'sl':'en','tl':'tl' if l=='fil' else l,'u':'https://mrblindbandit.net'+route}),quote=True)+'" rel="noopener noreferrer">'+label+'</a>' for l,label in [('es','Español'),('fil','Filipino'),('ceb','Cebuano')])
   s=s.replace('</footer>','<details><summary>Translate this public page with Google</summary><p>Automatic translation opens on Google. Translations can contain errors; private portal pages are excluded.</p>'+links+'</details></footer>')
  p.write_text(s)

 # Prominent, accessible community entry points on the public site.
 for route in ['', 'news', 'community']:
  p=output/route/'index.html'
  if p.exists():
   block='<section class="shell section"><h2>Join the conversation</h2><p>Share your thoughts with the community or catch up on official announcements.</p><a class="button" href="/community/?compose=1#new-post" data-full-navigation>Create a community post</a> <a class="button" href="/community/announcements/" data-full-navigation>Read official announcements</a><p>Sign in with your Clerk account to post. Community posts are public.</p></section>'
   p.write_text(p.read_text().replace('</main>',block+'</main>'))
