"""Public design and policy layer. Run before SEO and Worker document compilation."""
import re

def refresh(root,d,layout,pages,cards,own,player):
    mail='<a href="mailto:business@mrblindbandit.net">business@mrblindbandit.net</a>'
    address='Purok 6-A, Mabuhay, Barangay Capungagan, Davao del Norte 8113, Philippines'
    policies={
    'privacy':('Privacy policy','How information moves through the artist website, community, submissions, and private label portal.',[
    ('Who operates this website',f'This notice covers the Mr. Blindbandit website and Blindbandit Records services operated by Kaeleb Savon Heck. Business contact address: {address}. Philippine phone: <a href="tel:+639626954905">+63 962 695 4905</a>. United States phone: <a href="tel:+15409269791">+1 540 926 9791</a>. For privacy questions, access, correction, or deletion requests, contact {mail} with the subject “Privacy request.” The private label portal also has a <a href="/portal/privacy/" data-full-navigation>portal privacy notice</a>.'),
    ('Information you provide','Music submissions collect your artist name, contact email, project title, genre, listening link, message, permission confirmation, and optional MP3 or WAV file. Professional inquiries collect your name or organization, email, inquiry category, project details, and optional reference link. Mailing-list requests collect your email, optional first name, interests, and consent. Please provide only information needed for the request; do not submit passwords for unrelated accounts, identity documents, or payment-card details.'),
    ('Community information is public','Posts, comments, chosen display names, and posting times are visible to other visitors and may be copied or indexed. Your community profile is associated with a site-specific sign-in identity. Poll votes are stored with that identity to maintain one current vote per person; public results show totals. Do not post private contact information or other people’s personal information without permission. Removing a post hides it from public display; it does not necessarily erase the stored record or copies made by others. Comments can be removed through the available controls.'),
    ('Accounts and private label records','Community sign-in uses ChatGPT and is separate from invited label accounts. Label accounts store names, emails, roles, account status, password hashes, sessions, and activity records. The portal stores client earnings entries, contracts, messages, tasks, and internal planning records. Clients see their own permitted records; authorized staff have access appropriate to their role. Public visitors do not receive access to private records.'),
    ('Technical information and device preferences','Fonts load from Google Fonts, which receives connection information when font styles and files are requested. Hosting and authentication providers process connection information such as IP address, browser information, request times, and security events. Forms use a daily hashed IP-based rate-limit key to reduce abuse. Account sessions may store IP address and user-agent information. Local browser storage remembers motion, contrast, and text-size preferences. See the <a href="/cookies/">cookies and media notice</a> for details.'),
    ('Why information is used','Information is used to review music, answer inquiries, maintain accounts, show community discussions, manage label projects and client records, record newsletter interest, and prevent abuse. A submission or inquiry does not automatically add you to marketing. Mailing-list consent is collected separately. This website currently records signup requests; signup does not promise a particular sending schedule.'),
    ('Service providers and external platforms','The site uses Sites and Cloudflare-backed hosting, database, and file storage. ChatGPT supports community and site-owner authentication. Resend processes requested account emails, including temporary invitation or reset links. Spotify, Apple Music, and video services process information when their players or external pages are opened. PayPal and Wise process support payments on their own services. Their notices govern their independent processing. Google or Apple account connections are available only if configured and shown in the portal.'),
    ('Sharing and advertising','Information is available to the operator, authorized label staff, and service providers needed to operate the requested features. Community contributions are intentionally public. We may disclose relevant records where required by law or needed to investigate abuse or protect rights. Google AdSense code is installed on public pages for site verification and advertising services. When ads are served, Google and other third-party advertising vendors may collect IP address, device and browser information, cookie identifiers, and interactions with ads. Private submissions are not automatically published or supplied as advertising content. Embedded platforms may apply their own tracking practices after you load them.'),
    ('Google advertising and your choices','Third-party vendors, including Google, may use cookies to select ads based on earlier visits to this website or other websites. Advertising cookies can allow Google and its partners to personalize ads using activity across sites. Advertising services may also use web beacons or similar technologies for delivery, measurement, and fraud prevention. You can manage Google ad personalization in <a href="https://myadcenter.google.com/">My Ad Center</a>, learn about other vendors’ opt-out choices at <a href="https://www.aboutads.info/choices/">AboutAds choices</a>, and read <a href="https://policies.google.com/technologies/partner-sites">how Google uses information from partner sites</a>. Opting out of personalization does not necessarily remove all ads or all storage used for security and measurement. Where a consent message is displayed, use its choices to grant, refuse, or revise consent. Browser cookie settings offer additional controls. A privacy notice alone does not collect consent.'),
    ('Retention and deletion','There is no automatic retention schedule currently configured for every category. Submissions, inquiries, signup requests, account records, and label records remain until removed according to operational and recordkeeping needs. Archiving an internal record does not delete it. The operator can delete a submission and its uploaded file. Request deletion by email; tell us which account, submission, or post is involved. Some records may need to be retained for security, contract, accounting, or legal reasons, and provider backups may persist under provider practices.'),
    ('Your choices and requests',f'You can avoid optional forms and players, edit available profile details, use available community removal controls, and change device preferences. To withdraw mailing-list consent, email {mail} with “Unsubscribe” from the subscribed address. To request a copy, correction, restriction, or deletion of your information, explain your request without attaching identity documents. We may ask for reasonable verification through the relevant account or email. Depending on your location, additional privacy rights and a right to contact a data-protection authority may apply; requests are assessed under applicable law.'),
    ('International processing and security','The operator and service providers may process information in countries other than your own. The site does not promise storage in a single country. HTTPS, hashed passwords, access checks, and private file routes help protect records, but no system is guaranteed secure. Report suspected exposure privately through the contact address rather than posting personal information in the forum.'),
    ('Children and changes',f'This site is intended for a general music audience; account participation and information submissions are not intended for children under 13. If you believe a child has submitted personal information, contact {mail} so it can be investigated and addressed. We will update the effective date when this notice changes and provide additional notice where required.')]),
    'copyright':('Copyright & music use','Ownership, permission requests, and a clear route for reporting disputed material.',[
    ('Ownership and credits','Music, recordings, artwork, photographs, video, writing, logos, and website material may be protected by copyright or other rights. Rights belong to their respective owners. A collaboration credit, streaming link, or appearance on this site does not mean Blindbandit Records owns every right in that work. © 2026 Mr. Blindbandit. All rights reserved, except where permission or applicable law allows use.'),
    ('Listening, sharing, and linking','You may use the site for personal listening and share links to official pages and streaming services. Access to a player does not grant permission to download, sample, remix, redistribute, monetize, synchronize with video, use in advertising, or imply an endorsement. Any uses permitted by applicable law remain available.'),
    ('Ask for permission',f'For licensing, samples, sync, commercial use, artwork, or press-image permissions, use the <a href="/licensing/">licensing page</a> or contact {mail}. Identify the work, proposed use, platforms, territory, duration, and budget. Written approval must come from the relevant rights holder. Recordings and compositions can require separate permissions; a request or unanswered message is not approval.'),
    ('Your submissions and community contributions','You retain your rights in music and other material you submit. By submitting music, you permit the label to receive, store, and review it for the requested consideration and contact you about it. This is not a transfer of ownership, signing agreement, or promise of release. By posting in the community, you permit the site to store and display your contribution for the community feature. Only share material you own or have permission to use. Private submissions are not automatically published.'),
    ('Report a copyright concern',f'Email {mail} with the subject “Copyright concern.” Include your name and contact details, identification of the protected work, the exact website URL of the disputed material, why you believe the use is unauthorized, and whether you are the owner or an authorized representative. Include supporting links and a signed statement that your information is accurate and your complaint is made in good faith. Do not submit a knowingly false complaint or assume that every disagreement is copyright infringement.'),
    ('Review and response','The operator may ask for clarification, restrict access while reviewing a concern, contact the contributor, or remove material where appropriate. Relevant complaint details may be shared with the affected contributor to allow a response; omit unrelated sensitive information. Repeated substantiated infringement may result in posting restrictions or account suspension. A report does not guarantee a particular outcome or response time.'),
    ('If your material was removed',f'Contact {mail} with the affected URL, the removal details, and the basis for your permission, ownership, or other lawful use. This contact route is a general copyright-review process, not a representation that a statutory DMCA agent has been registered. Formal notices or counter-notices may carry additional legal requirements. Read the <a href="https://www.copyright.gov/512/">U.S. Copyright Office’s notice and counter-notice guidance</a> before submitting a formal claim.'),
    ('External services','If disputed material is hosted on Spotify, Apple Music, YouTube, or another platform, report it through that platform’s process as well. This site can address its own links and content but cannot remove a recording from another service. For permitted brand and press uses, check the <a href="/press/">press room</a> and obtain any necessary approval.')]),
    'terms':('Website terms','Ground rules for listening, participating, submitting work, and using label services.',[
    ('Using the site','These terms describe use of the Mr. Blindbandit website and its community and submission features. Use the site lawfully and respect other people’s rights. If you do not agree, do not submit content or use account features. Separate signed agreements govern paid services, licensing, distribution, and client relationships where applicable; visiting this site does not create those agreements.'),
    ('Accounts and participation','Keep your account credentials private and provide accurate information for the features you use. Label accounts are invitation-only and role-restricted. A fan community account does not provide label access. Do not impersonate others, bypass access controls, spam, harass, expose private information, or upload harmful material. Follow the <a href="/community/guidelines/">community guidelines</a>. Accounts or posts may be restricted for abuse or security concerns.'),
    ('Music and professional inquiries','Only submit music you are authorized to share. Submissions are for consideration and do not guarantee a response, signing, release, promotion, payment, or confidentiality agreement beyond the site’s stated access practices. Do not send material subject to obligations that prevent this review. Bookings, features, partnerships, and licensing require separate confirmation of scope, fees, timing, and rights.'),
    ('Support payments','Support links open PayPal or Wise. Review the recipient, currency, fees, and payment details there before paying. A voluntary support payment does not purchase a label signing, placement, ownership interest, or guaranteed service. This site does not represent contributions as tax-deductible charitable donations. For an accidental payment, contact the recipient promptly and use the payment provider’s available process; refunds are not automatically promised.'),
    ('Availability and records','Streaming availability, third-party services, and website features can change. We aim to keep information useful but do not guarantee uninterrupted access or that all catalog information is complete. Portal financial entries are manually maintained label records, not live bank balances or automatic royalty imports. Marking a contract reviewed is an acknowledgment, not an electronic signature.'),
    ('Rights and responsibility','The <a href="/copyright/">copyright policy</a> explains permissions and reporting. You remain responsible for material you provide. Nothing in these terms removes rights or remedies that cannot lawfully be excluded. The site does not create a blanket waiver of consumer rights, mandatory arbitration agreement, or consent to unrelated marketing.'),
    ('Questions and updates',f'Contact {mail} about these terms or a site issue. Material updates will be reflected in the effective date. The <a href="/privacy/">privacy policy</a>, <a href="/cookies/">cookies and media notice</a>, and community guidelines explain related practices.')]),
    'cookies':('Cookies & embedded media','What is stored on your device and what happens when you load an external player.',[
    ('Essential account sessions','Authentication uses session cookies to keep signed-in visitors connected to their community or label account. Hosting and sign-in providers may use security cookies. Blocking essential cookies can prevent sign-in. Sign out on shared devices and use your browser’s controls to remove cookies.'),
    ('Local preferences','The site stores motion, high-contrast, and larger-text choices in local browser storage under bb-preferences. These choices apply to that browser. They do not create a public profile. Clearing browser site data removes them. The site does not currently implement a separate advertising-cookie preference system.'),
    ('Advertising cookies','Public pages include the Google AdSense script. When Google advertising services operate, Google and its partners may place or read cookies and use related technologies for advertising, measurement, and fraud prevention. The <a href="/privacy/">privacy policy</a> explains personalization and opt-out links. Motion and text preferences do not control advertising consent. A Google-certified consent message must be configured separately for applicable advertising regions; this notice is not that consent interface.'),
    ('You choose when media loads','Spotify and Apple Music players are opened when you select a player control. Once loaded, a player connects to its provider, which may receive your IP address, device details, and playback interactions and may apply its own cookies. Closing a player removes it from the page but does not erase cookies previously set by that provider. External video and social links open services with their own practices.'),
    ('Control your experience','Use Pause motion in the footer or visit <a href="/accessibility/">accessibility settings</a> for motion, contrast, and text controls. Use browser settings to block or clear third-party cookies. You can browse written content without loading a player. Provider playback and authentication may work differently when cookies are blocked.'),
    ('Provider notices','Read <a href="https://www.spotify.com/legal/privacy-policy/">Spotify privacy</a>, <a href="https://www.apple.com/legal/privacy/">Apple privacy</a>, <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy</a>, and <a href="https://openai.com/policies/privacy-policy/">OpenAI privacy</a> for provider processing. Our <a href="/privacy/">privacy policy</a> covers information collected through this website.')]),
    'contact':('Business contact','Official contact information for Mr. Blindbandit and Blindbandit Records.',[
    ('Artist and label',f'Kaeleb Savon Heck, professionally known as Mr. Blindbandit, operates this artist website and Blindbandit Records. Email {mail} for business, media, privacy, or copyright matters.'),
    ('Contact details',f'<strong>Business contact address</strong><br>{address}<br><br><strong>Philippine phone</strong><br><a href="tel:+639626954905">+63 962 695 4905</a><br><br><strong>United States phone</strong><br><a href="tel:+15409269791">+1 540 926 9791</a><br><br><strong>Email</strong><br>{mail}'),
    ('Choose the right route','Use <a href="/submit/">music submissions</a> for demos, <a href="/contact/forms/">professional inquiries</a> for bookings and creative projects, and <a href="/help/">account help</a> for sign-in issues. For a privacy or copyright concern, include the relevant page address and a clear description. Never send your password or a password-reset link.'),
    ('Before contacting us','A message does not confirm availability, a booking, licensing permission, or a label agreement. Those details are agreed separately in writing. Contact hours and response times are not guaranteed. Please email before sending physical materials or arranging a visit.')]),
    'help':('Help & visitor information','Find the right contact, understand the site, and get back to the music.',[
    ('Listening and players','Open <a href="/music/">Music</a> to browse releases or use the <a href="/listen/">listening room</a>. Player availability depends on the streaming service and your location or account. If a player will not load, use the official streaming link. Close the persistent player when you want playback to stop.'),
    ('Account help','Fan accounts use <a href="/community/account/">community sign-in</a>. Invited artists and staff use the separate <a href="/portal/login/" data-full-navigation>label portal</a>. Label invitations and password emails come from accounts@mrblindbandit.com. The sending domain differs from this website’s mrblindbandit.net address; account links lead back to the official website. For a label password, use the <a href="/portal/reset/" data-full-navigation>reset request page</a>. If the email does not arrive, check spam and contact the label; do not post passwords or reset links publicly.'),
    ('Send music or a business request','Use <a href="/submit/">Submit music</a> for demos and <a href="/contact/forms/">Professional inquiries</a> for bookings, collaborations, licensing, or interviews. The submission form accepts a listening link or MP3/WAV file up to 10 MB. A saved request is not a promise of acceptance.'),
    ('Accessibility and reporting problems',f'The site includes a skip link, labeled controls, keyboard navigation, and adjustable text, contrast, and motion preferences. Third-party players have their own interfaces. We do not claim an independent accessibility certification. If something blocks you, email {mail} with the page address, device or assistive technology, and what you were trying to do. You can also request information in a different format.'),
    ('Privacy, copyright, and community concerns',f'For privacy requests or copyright concerns, use {mail} and the appropriate subject. Read the <a href="/privacy/">privacy policy</a>, <a href="/copyright/">copyright policy</a>, and <a href="/community/guidelines/">community rules</a>. Avoid sending unrelated sensitive information when reporting an issue.')])}
    for slug,(title,description,sections) in policies.items():
        toc=''.join(f'<a href="#policy-{i}">{name}</a>' for i,(name,_) in enumerate(sections,1))
        body=f'<section class="shell policy-intro"><p class="eyebrow">INFORMATION &amp; TRUST</p><h1>{title}</h1><p class="lede">{description}</p><p class="policy-date">Effective September 8, 2026</p></section><div class="shell policy-layout"><aside><nav aria-label="On this page">{toc}</nav><a class="text-link" href="mailto:business@mrblindbandit.net">Contact the operator</a></aside><article>'+''.join(f'<section id="policy-{i}"><span class="policy-index">{i:02}</span><h2>{name}</h2><p>{text}</p></section>' for i,(name,text) in enumerate(sections,1))+'</article></div>'
        layout('/'+slug+'/',title,description,body)
        if not any(u=='/'+slug+'/' for _,u in pages):pages.append((title,'/'+slug+'/'))
    from universe import transform_records
    homepage='<section class="shell modern-hero"><div><p class="eyebrow">MR. BLINDBANDIT / INDEPENDENT ARTIST</p><h1>Sound beyond<br><em>the ordinary.</em></h1><p class="lede">Mr. Blindbandit is Kaeleb Savon Heck, a blind American music creator based in the Philippines. Explore his ambient music, cinematic textures, and hip-hop connections.</p><div class="actions"><a class="button" href="/music/">Explore the music ↗</a><a class="text-link" href="/biography/">Who is Mr. Blindbandit?</a></div><p class="modern-location">Virginia roots · Philippines home · Worldwide sound</p></div><figure><img src="/assets/artist.jpg" alt="Mr. Blindbandit in the Philippines, wearing a green shirt" width="531" height="640" fetchpriority="high"><figcaption>THE ARTIST / KAELEB SAVON HECK</figcaption></figure></section><div class="modern-strip"><span>AMBIENT</span><span>CINEMATIC</span><span>ELECTRONIC</span><span>HIP-HOP</span></div><section class="shell section"><div class="section-heading"><div><p class="eyebrow">THE CATALOG</p><h2>Find your next repeat.</h2></div><a href="/music/" class="text-link">All releases ↗</a></div><div class="records">'+cards(own[:4])+'</div></section><section class="shell modern-label"><div><p class="eyebrow">BLINDBANDIT RECORDS</p><h2>Independent by design.<br>Connected by music.</h2><p>Discover the label, explore creative connections, or introduce us to your own sound.</p><div class="actions"><a class="button" href="/label/">Inside the label ↗</a><a href="/submit/" class="text-link">Submit your music</a></div></div><a class="modern-feature" href="/collaborators/maskman/"><img src="/assets/releases/6802446802.jpg" alt="DA BLINDBANDIT release artwork" width="500" height="500" loading="lazy"><span>UUu Tang Maskman × Mr. Blindbandit<br><strong>Explore the connection ↗</strong></span></a></section><section class="shell section"><div class="section-heading"><div><p class="eyebrow">BEYOND THE RELEASE</p><h2>There’s more to the story.</h2></div></div><div class="modern-paths"><a href="/biography/"><span>01 / THE ARTIST</span><h3>A life in sound.</h3><p>Get to know Kaeleb, his creative work, and the perspective behind it.</p></a><a href="/community/"><span>02 / THE PEOPLE</span><h3>Join the conversation.</h3><p>Talk music, share ideas, and connect with fellow listeners.</p></a><a href="/videos/"><span>03 / THE VISUALS</span><h3>See another side.</h3><p>Follow the music and the creator beyond the studio.</p></a></div></section><section class="shell listen-section"><div><p class="eyebrow">PRESS PLAY</p><h2>Stay a little longer.</h2><p>Explore Mr. Blindbandit on Spotify.</p><a href="/listen/" class="text-link">Open the listening room ↗</a></div>'+player('Spotify','04HZ4GubB66CqMpJrHysy3','MR. BLINDBANDIT')+'</section>'
    layout('/','Mr. Blindbandit | Official artist website','Music, creative connections, and Blindbandit Records. Explore the official Mr. Blindbandit website.',transform_records(homepage))
    footer='<footer class="shell modern-footer"><div class="modern-footer-brand"><a class="wordmark" href="/">MR. BLIND<span>BANDIT.</span></a><p>Independent sound.<br>A world you can feel.</p><a href="mailto:business@mrblindbandit.net">business@mrblindbandit.net</a></div><nav aria-label="Footer music and artist"><h2>Explore</h2><a href="/music/">Music</a><a href="/biography/">The artist</a><a href="/videos/">Videos</a><a href="/collaborators/">Collaborators</a><a href="/explore/">All pages</a></nav><nav aria-label="Footer label and community"><h2>Connect</h2><a href="/label/">Blindbandit Records</a><a href="/submit/">Submit music</a><a href="/community/">Fan community</a><a href="/signup/">Mailing list</a><a href="/support/">Support the artist</a><a href="/portal/login/" data-full-navigation>Label sign-in</a></nav><nav aria-label="Policies and support"><h2>Information</h2><a href="/privacy/">Privacy policy</a><a href="/copyright/">Copyright &amp; music use</a><a href="/terms/">Website terms</a><a href="/cookies/">Cookies &amp; media</a><a href="/accessibility/">Accessibility settings</a><a href="/contact/">Business contact</a><a href="/help/">Help &amp; support</a></nav><div class="modern-footer-bottom"><p>© 2026 Mr. Blindbandit. All rights reserved. Music and artwork belong to their respective rights holders.</p><button class="motion-toggle" aria-pressed="false" hidden>Pause motion</button><a href="#main">Back to top ↑</a></div></footer>'
    for p in d.rglob('index.html'):
        route='/'+str(p.parent.relative_to(d))+'/'
        if '/portal/' in route or '/owner/' in route:continue
        s=p.read_text().replace('<body>','<body class="public-modern">')
        is_public=not route.startswith(('/community/account/','/community/dashboard/','/community/moderation/'))
        if route in ['/privacy/','/copyright/','/terms/','/cookies/','/safety/','/advertising-disclosure/']:s=s.replace('class="public-modern"','class="public-modern legal-page"',1)
        if is_public:
            s=s.replace('</head>','<meta name="google-adsense-account" content="ca-pub-7238428274233485"></head>',1)
            adsense='<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7238428274233485" crossorigin="anonymous"></script>'
            s=s.replace('</head>',adsense+'</head>',1)

        s=re.sub(r'<footer class="shell">.*?</footer>',lambda _:footer,s,flags=re.S)
        s=s.replace('<link rel="stylesheet" href="/styles.css">','<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/public-modern.css">')
        # Keep the primary navigation focused; the full directory remains one click away.
        start=s.find('<nav id="navigation"');end=s.find('</nav>',start)
        if start>=0 and end>=0:s=s[:start]+'<nav id="navigation" aria-label="Main navigation">'+''.join(f'<a href="{u}"'+(' aria-current="page"' if route==u else '')+f'>{n}</a>' for n,u in [('Music','/music/'),('Artist','/biography/'),('Label','/label/'),('Community','/community/'),('Explore','/explore/')])+s[end:]
        if any('/'+slug+'/'==route for slug in policies):s=re.sub(r'<section class="closing shell">.*?</section>','',s,flags=re.S)
        s=s.replace('Player loads when selected.','Loading a player connects to its provider. <a href="/cookies/">Media privacy</a>.')
        s=s.replace('</form>','<p class="small">Read our <a href="/privacy/">privacy policy</a> and <a href="/terms/">website terms</a>.</p></form>') if 'native-form' in s else s
        if route=='/community/guidelines/':
            s=s.replace('</main>','<section class="shell section"><h2>Keep participation safe</h2><p>No sexual exploitation, illegal sales, malware, violent incitement, deceptive offers, or instructions to generate artificial ad clicks or traffic. Report concerning material through the post controls or email business@mrblindbandit.net. Content may be removed and access restricted for violations.</p></section></main>')
        p.write_text(s)
