"""Five practical, browser-local planning tools for artists and collaborators."""
import html

def add_useful_tools(output, layout, pages):
    tools = [
      ('/tools/release-budget/','Release budget calculator','Estimate a release budget and the revenue needed to recover it.', '''
<form class="tool-form" data-tool="budget">
 <div class="tool-grid"><label>Recording and production<input name="production" type="number" min="0" step="0.01" value="0"></label><label>Artwork and design<input name="artwork" type="number" min="0" step="0.01" value="0"></label><label>Marketing<input name="marketing" type="number" min="0" step="0.01" value="0"></label><label>Distribution and delivery<input name="distribution" type="number" min="0" step="0.01" value="0"></label><label>Contingency reserve<input name="reserve" type="number" min="0" step="0.01" value="0"></label><label>Planning revenue per stream<input name="rate" type="number" min="0.0001" step="0.0001" value="0.0030"></label></div>
 <div class="tool-actions"><button class="button" type="submit">Calculate budget</button><button type="reset">Clear</button></div><output class="tool-result" aria-live="polite"></output>
</form><p class="small">This is a planning estimate. Streaming payments vary by platform, territory, subscription type, rights ownership and distributor terms.</p>'''),
      ('/tools/royalty-split/','Royalty split checker','Check whether proposed participant shares add up to exactly 100 percent.', '''
<form class="tool-form" data-tool="split">
 <div class="tool-grid"><label>Participant 1<input name="name1" value="Lead artist" maxlength="80"></label><label>Share 1 (%)<input name="share1" type="number" min="0" max="100" step="0.01" value="50"></label><label>Participant 2<input name="name2" value="Collaborator" maxlength="80"></label><label>Share 2 (%)<input name="share2" type="number" min="0" max="100" step="0.01" value="50"></label><label>Participant 3<input name="name3" maxlength="80"></label><label>Share 3 (%)<input name="share3" type="number" min="0" max="100" step="0.01" value="0"></label><label>Participant 4<input name="name4" maxlength="80"></label><label>Share 4 (%)<input name="share4" type="number" min="0" max="100" step="0.01" value="0"></label></div>
 <div class="tool-actions"><button class="button" type="submit">Check shares</button><button type="button" data-download>Download summary</button></div><output class="tool-result" aria-live="polite"></output>
</form><p class="small">A valid total does not create an agreement. Confirm master and composition splits separately in a signed writing.</p>'''),
      ('/tools/metadata-checklist/','Release metadata checklist','Prepare a cleaner delivery package and save your progress on this device.', '''
<form class="tool-form" data-tool="metadata">
 <fieldset class="tool-checklist"><legend>Release preparation</legend><label><input type="checkbox" name="artist"> Artist names and exact styling confirmed</label><label><input type="checkbox" name="title"> Release and track titles confirmed</label><label><input type="checkbox" name="contributors"> Writers, producers and featured artists credited</label><label><input type="checkbox" name="rights"> Master, composition, sample and artwork rights checked</label><label><input type="checkbox" name="audio"> Final audio files and versions labeled</label><label><input type="checkbox" name="artwork"> Artwork format and ownership checked</label><label><input type="checkbox" name="codes"> ISRC and UPC status documented</label><label><input type="checkbox" name="dates"> Release date, territories and explicit-content status confirmed</label><label><input type="checkbox" name="links"> Artist profiles and pre-release links verified</label><label><input type="checkbox" name="archive"> Final delivery package archived</label></fieldset>
 <div class="tool-actions"><button class="button" type="submit">Save progress</button><button type="button" data-download>Download checklist</button><button type="reset">Start over</button></div><output class="tool-result" aria-live="polite"></output>
</form><p class="small">Progress stays in this browser and is not uploaded to Blindbandit Records.</p>'''),
      ('/tools/collaboration-brief/','Collaboration brief builder','Turn a collaboration idea into a clear brief you can copy or download.', '''
<form class="tool-form" data-tool="brief">
 <div class="tool-grid"><label>Project or song title<input name="project" required maxlength="120"></label><label>Your name or artist name<input name="artist" required maxlength="120"></label><label>Requested collaborator<input name="collaborator" maxlength="120"></label><label>Requested role<input name="role" placeholder="Feature, production, remix, writing" maxlength="120"></label><label>Target date<input name="date" type="date"></label><label>Budget or proposed terms<input name="terms" maxlength="160"></label><label class="tool-wide">Creative direction<textarea name="direction" rows="5" maxlength="1500" required></textarea></label><label class="tool-wide">Deliverables and references<textarea name="deliverables" rows="5" maxlength="1500"></textarea></label></div>
 <div class="tool-actions"><button class="button" type="submit">Build brief</button><button type="button" data-copy disabled>Copy</button><button type="button" data-download disabled>Download</button></div><output class="tool-result tool-document" aria-live="polite"></output>
</form><p class="small">The generated brief stays on your device. It is not a contract or a submission to the label.</p>'''),
      ('/tools/press-brief/','Interview brief builder','Create a focused interview request before contacting Mr. Blindbandit or another artist.', '''
<form class="tool-form" data-tool="press">
 <div class="tool-grid"><label>Outlet or program<input name="outlet" required maxlength="120"></label><label>Contact name<input name="contact" required maxlength="120"></label><label>Interview format<select name="format"><option>Written Q&amp;A</option><option>Audio interview</option><option>Video interview</option><option>Podcast</option><option>Live appearance</option></select></label><label>Requested date<input name="date" type="date"></label><label>Estimated duration<input name="duration" placeholder="30 minutes" maxlength="80"></label><label>Publication date<input name="publication" type="date"></label><label class="tool-wide">Main angle<textarea name="angle" rows="4" maxlength="1200" required></textarea></label><fieldset class="tool-wide tool-checklist"><legend>Suggested topics</legend><label><input type="checkbox" name="topic" value="music and creative process"> Music and creative process</label><label><input type="checkbox" name="topic" value="blindness and accessible technology"> Blindness and accessible technology</label><label><input type="checkbox" name="topic" value="independent releases and Blindbandit Records"> Independent releases and Blindbandit Records</label><label><input type="checkbox" name="topic" value="life between Virginia and the Philippines"> Life between Virginia and the Philippines</label></fieldset></div>
 <div class="tool-actions"><button class="button" type="submit">Build interview brief</button><button type="button" data-copy disabled>Copy</button><button type="button" data-download disabled>Download</button></div><output class="tool-result tool-document" aria-live="polite"></output>
</form><p class="small">Review the generated text, then use the official <a href="/booking/">booking and interview form</a> to send the request.</p>''')
    ]
    for path,title,description,tool in tools:
        body='<section class="page-intro shell"><p class="eyebrow">MR. BLINDBANDIT / ARTIST TOOLKIT</p><h1>'+html.escape(title)+'</h1><p class="lede">'+html.escape(description)+'</p></section><section class="shell section tool-shell"><h2>Build it here</h2>'+tool+'</section><section class="shell section"><h2>Your information stays with you</h2><p>Calculations and generated drafts run in this browser. Nothing entered on this page is submitted to the label. Review any output before relying on it.</p><a class="text-link" href="/resources/">Explore artist resources ↗</a></section><script src="/planning-tools.js" defer></script>'
        layout(path,title,description,body)
        if not any(existing==path for _,existing in pages): pages.append((title,path))

