import * as media from './media';
import {legacy} from './legacy';
import {modules as workspaceModules} from '../workspace';
import {z} from 'zod';
import {ApiError,q,uuid,hash,setting,setSetting,audit,limit,input,guardOrigin,page,origins,type Env} from './core';
import {authenticate,upstream,owner,recent,issue,refresh,bootstrap,reauthenticate,type Actor} from './auth';
import {providers,catalog,save,connectionTest} from './integrations';
import {register,unregister,registerWebPush,unregisterWebPush,listTopics,listTopicSubscriptions,subscribeTopic,unsubscribeTopic,deepLink,notify,notifyAndDeliver,pushTest,vapidPublicConfig} from './notifications';
import {mintLiveKitToken,livekitPublicStatus} from './livekit';
import * as social from './social';
import * as socialAdmin from './social-admin';
import {socialAuthenticate, type SocialActor} from './auth';
type Context={request:Request;env:Env;a:AnyActor;data:any;params:Record<string,string>;rid:string;url:URL};
type Route={method:string;path:string;access:'public'|'user'|'owner'|'recent_owner'|'worker'|'social'|'social_admin';summary:string;schema?:z.ZodType;handler:(c:Context)=>Promise<any>|any};
type AnyActor=Actor|SocialActor;
export const routes:Route[]=[];
const add=(method:string,path:string,access:Route['access'],summary:string,schema:Route['schema'],handler:Route['handler'])=>routes.push({method,path,access,summary,schema,handler});
const object=(shape:any)=>z.object(shape).strict();
const text=(max=200,min=1)=>z.string().trim().min(min).max(max);
const empty=object({});
const environment=z.enum(['development','staging','production']);
const id=text(100);
const device={device_name:text(100),platform:z.enum(['ios','android','web','desktop']),app_version:text(40)};
const current=(a:Actor)=>({id:a.id,name:a.name,email:a.email,role:a.role});
const configDefault={api_version:'v1',maintenance:false,announcement:'',ios_version:'',android_version:'',minimum_ios_version:'',minimum_android_version:'',support_url:'https://mrblindbandit.net/support/',privacy_url:'https://mrblindbandit.net/privacy/',terms_url:'https://mrblindbandit.net/terms/',accessibility_url:'https://mrblindbandit.net/accessibility/',features:{native_notifications:true,native_profile:true,native_label:true,server_media_jobs:false,web_push:true,social_mobile:true,livekit:true},android_package:'net.mrblindbandit.app',push_register_url:'https://mrblindbandit.net/api/v1/social/devices'};
const configSchema=object({maintenance:z.boolean().optional(),announcement:text(500,0).optional(),ios_version:text(40,0).optional(),android_version:text(40,0).optional(),minimum_ios_version:text(40,0).optional(),minimum_android_version:text(40,0).optional(),features:object({native_notifications:z.boolean().optional(),native_profile:z.boolean().optional(),native_label:z.boolean().optional()}).optional()});
async function config(env:Env){const saved=await setting(env,'app_config',{});return {...configDefault,...saved,features:{...configDefault.features,...saved.features,server_media_jobs:await media.mediaWorkerReady(env),web_push:!!(env.VAPID_PUBLIC_KEY||env.WEBPUSH_PUBLIC_KEY),livekit:!!(env.LIVEKIT_API_KEY&&env.LIVEKIT_API_SECRET)},environment:'production'};}
async function ownChange(c:Context,sql:string,...values:any[]){const row=await q(c.env,sql,...values).first();if(!row)throw new ApiError(404,'NOT_FOUND','Record not found.');return row;}
add('GET','/v1/system/health','public','Public API liveness',undefined,()=>({status:'ok',api_version:'v1'}));
add('GET','/v1/app/config','public','Public mobile configuration',undefined,c=>config(c.env));
add('POST','/v1/auth/session','user','Exchange an existing website session for a mobile session',object(device),async c=>{if(c.a.sessionId)throw new ApiError(400,'UPSTREAM_REQUIRED','Use your website authentication to register a new session.');if(['owner','admin'].includes(c.a.role))recent(c.a);return issue(c.env,c.a,c.data,c.rid);});
add('POST','/v1/auth/refresh','public','Rotate access and refresh credentials',object({refresh_token:text(100)}),c=>refresh(c.env,c.data,c.rid));
add('POST','/v1/auth/logout','user','Revoke this API session',empty,async c=>{if(!c.a.sessionId)throw new ApiError(400,'API_SESSION_REQUIRED','Use website sign out to end a website session.');await c.env.DB.batch([q(c.env,'UPDATE platform_sessions SET revoked_at=? WHERE id=?',Date.now(),c.a.sessionId),audit(c.env,c.a.id,'session.revoked',c.a.sessionId,c.rid)]);return {revoked:true};});
add('POST','/v1/auth/logout-all','user','Revoke all API sessions for the current account',object({confirmation:z.literal('REVOKE ALL MY API SESSIONS')}),async c=>{recent(c.a);await c.env.DB.batch([q(c.env,'UPDATE platform_sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL',Date.now(),c.a.id),audit(c.env,c.a.id,'session.all_revoked',c.a.id,c.rid)]);return {revoked:true};});
add('GET','/v1/auth/status','user','Current API authentication status',undefined,c=>({authenticated:true,user:current(c.a),session_id:c.a.sessionId||null,reauthentication_required:c.a.verifiedAt<Date.now()-5*60000}));
const reauthSchema=object({master_secret:text(256,32).optional(),authenticator_code:z.string().regex(/^\d{6}$/).optional()});
add('POST','/v1/auth/reauthenticate','user','Verify a sensitive API session',reauthSchema,c=>reauthenticate(c.env,c.a,c.data,c.rid));
add('POST','/v1/owner/reauthenticate','owner','Verify an owner API session',reauthSchema,c=>reauthenticate(c.env,c.a,c.data,c.rid));
add('POST','/v1/owner/bootstrap','public','Exchange the dedicated owner master credential',object({...device,master_secret:text(256,32)}),c=>bootstrap(c.env,c.data,c.rid));
add('GET','/v1/owner/status','owner','Mobile owner access status',undefined,async c=>({enabled:await setting(c.env,'owner_mobile_enabled',false),master_configured:!!await setting(c.env,'owner_master_digest','')}));
add('POST','/v1/owner/configure','recent_owner','Configure or rotate the dedicated owner credential',object({master_secret:z.string().regex(/^[0-9a-fA-F]{64}$/),enabled:z.boolean(),confirmation:z.literal('ROTATE OWNER ACCESS')}),async c=>{if(c.a.provider==='owner')throw new ApiError(403,'WEBSITE_SESSION_REQUIRED','Rotate master access from an independently authenticated website session.');await c.env.DB.batch([setSetting(c.env,'owner_master_digest',await hash(c.data.master_secret)),setSetting(c.env,'owner_mobile_enabled',c.data.enabled),q(c.env,"UPDATE platform_sessions SET revoked_at=? WHERE kind='owner' AND revoked_at IS NULL",Date.now()),audit(c.env,c.a.id,'owner.credential_rotated',c.a.id,c.rid)]);return {configured:true,enabled:c.data.enabled};});
add('POST','/v1/owner/disable','recent_owner','Disable mobile owner access and revoke owner credentials',object({confirmation:z.literal('DISABLE MOBILE OWNER ACCESS')}),async c=>{await c.env.DB.batch([setSetting(c.env,'owner_mobile_enabled',false),q(c.env,"UPDATE platform_sessions SET revoked_at=? WHERE kind='owner' AND revoked_at IS NULL",Date.now()),audit(c.env,c.a.id,'owner.disabled','all',c.rid)]);return {enabled:false};});
add('GET','/v1/owner/sessions','owner','List owner device sessions',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,"SELECT id,device_name,platform,app_version,created_at,last_used_at,expires_at,refresh_expires_at,revoked_at FROM platform_sessions WHERE kind='owner' ORDER BY created_at DESC LIMIT ? OFFSET ?",p.limit,p.offset).all()).results,...p};});
add('DELETE','/v1/owner/sessions/{id}','recent_owner','Revoke one owner device session',undefined,async c=>{await ownChange(c,"UPDATE platform_sessions SET revoked_at=? WHERE id=? AND kind='owner' RETURNING id",Date.now(),c.params.id);await audit(c.env,c.a.id,'owner.session_revoked',c.params.id,c.rid).run();return {revoked:true};});
add('POST','/v1/owner/sessions/revoke-all','recent_owner','Revoke every mobile owner session',object({confirmation:z.literal('REVOKE ALL OWNER DEVICES')}),async c=>{await c.env.DB.batch([q(c.env,"UPDATE platform_sessions SET revoked_at=? WHERE kind='owner' AND revoked_at IS NULL",Date.now()),audit(c.env,c.a.id,'owner.sessions_revoked','all',c.rid)]);return {revoked:true};});
add('GET','/v1/integrations','owner','Integration catalog and safe credential status',undefined,c=>catalog(c.env));
add('PUT','/v1/integrations/{provider}','recent_owner','Encrypt and save integration credentials',object({environment,public_config:z.record(z.string(),z.string()).default({}),secret_config:z.record(z.string(),z.string()).default({})}),c=>save(c.env,c.a,c.params.provider,c.data,c.rid));
add('POST','/v1/integrations/{provider}/test','recent_owner','Run a read-only provider connection test',object({environment}),c=>connectionTest(c.env,c.a,c.params.provider,c.data.environment,c.rid));
add('POST','/v1/integrations/{provider}/disable','recent_owner','Disable an integration configuration',object({environment}),async c=>{if(!providers[c.params.provider])throw new ApiError(404,'NOT_FOUND','Integration not found.');const target=c.params.provider+':'+c.data.environment;await c.env.DB.batch([q(c.env,"INSERT INTO platform_integrations(id,provider,environment,public_config,secret_config,enabled,status,updated_at) VALUES(?,?,?,'{}','',0,'disabled',?) ON CONFLICT(id) DO UPDATE SET enabled=0,status='disabled',updated_at=excluded.updated_at",target,c.params.provider,c.data.environment,Date.now()),audit(c.env,c.a.id,'integration.disabled',target,c.rid)]);return {disabled:true};});
add('DELETE','/v1/integrations/{provider}','recent_owner','Remove saved credentials and keep the integration disabled',object({environment,confirmation:z.literal('DELETE CREDENTIALS')}),async c=>{const target=c.params.provider+':'+c.data.environment;await ownChange(c,"UPDATE platform_integrations SET secret_config='',public_config='{}',enabled=0,status='disabled',updated_at=? WHERE id=? RETURNING id",Date.now(),target);await audit(c.env,c.a.id,'integration.credentials_deleted',target,c.rid).run();return {deleted:true,disabled:true};});
add('GET','/v1/me','user','Current account profile',undefined,c=>current(c.a));
add('PATCH','/v1/me','user','Update the label display name',object({name:text(100)}),async c=>{await c.env.DB.batch([q(c.env,'UPDATE label_user SET name=?,updated_at=? WHERE id=?',c.data.name,Date.now(),c.a.id),audit(c.env,c.a.id,'profile.updated',c.a.id,c.rid)]);return {...current(c.a),name:c.data.name};});
const preferences=object({language:z.enum(['en','es','fil','ceb']).optional(),reduce_motion:z.boolean().optional(),notification_categories:z.array(z.enum(['system','account','label','payment','earnings','release','community','message','creator_tool','media_job','announcement','beta','maintenance','marketing'])).max(14).optional()});
add('GET','/v1/me/preferences','user','Read notification and accessibility preferences',undefined,async c=>{const row=await q(c.env,'SELECT value FROM platform_preferences WHERE user_id=?',c.a.id).first();return row?JSON.parse(row.value):{language:'en',reduce_motion:false,notification_categories:[]};});
add('PATCH','/v1/me/preferences','user','Update notification and accessibility preferences',preferences,async c=>{const row=await q(c.env,'SELECT value FROM platform_preferences WHERE user_id=?',c.a.id).first();const value={...(row?JSON.parse(row.value):{}),...c.data};await q(c.env,'INSERT INTO platform_preferences(user_id,value,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at',c.a.id,JSON.stringify(value),Date.now()).run();return value;});
add('GET','/v1/dashboard','user','Native home dashboard',undefined,async c=>({user:current(c.a),unread_notifications:(await q(c.env,'SELECT COUNT(*) AS n FROM platform_notifications WHERE user_id=? AND read_at IS NULL AND deleted_at IS NULL',c.a.id).first()).n,configuration:await config(c.env),quick_actions:[{title:'Label portal',url:'https://mrblindbandit.net/portal/'},{title:'Creator tools',url:'https://mrblindbandit.net/media-tools/'}]}));
add('PUT','/v1/admin/app-config','recent_owner','Update remote app configuration',configSchema,async c=>{const old=await setting(c.env,'app_config',{});const next={...old,...c.data,features:{...old.features,...c.data.features}};await c.env.DB.batch([setSetting(c.env,'app_config',next),audit(c.env,c.a.id,'app.config_updated','production',c.rid)]);return config(c.env);});
add('POST','/v1/push/register','user','Register or update an encrypted device token',object({installation_id:text(100),platform:z.enum(['ios','android']),token:text(4096),app_version:text(40),language:text(20)}),c=>register(c.env,c.a,c.data,c.rid));
add('GET','/v1/push/devices','user','List own devices without raw push tokens',undefined,async c=>({items:(await q(c.env,'SELECT id,installation_id,platform,app_version,language,enabled,created_at,updated_at FROM platform_devices WHERE user_id=? ORDER BY created_at DESC LIMIT 20',c.a.id).all()).results}));
add('PATCH','/v1/push/devices/{id}','user','Update own device preference',object({enabled:z.boolean()}),async c=>ownChange(c,'UPDATE platform_devices SET enabled=?,updated_at=? WHERE id=? AND user_id=? RETURNING id,enabled',c.data.enabled?1:0,Date.now(),c.params.id,c.a.id));
add('DELETE','/v1/push/devices/{id}','user','Unregister an owned device',undefined,async c=>{await ownChange(c,'DELETE FROM platform_devices WHERE id=? AND user_id=? RETURNING id',c.params.id,c.a.id);return {deleted:true};});
add('POST','/v1/push/test','recent_owner','Send a test to one of the owner’s own devices',object({device_id:id,environment}),c=>pushTest(c.env,c.a,c.data,c.rid));
add('GET','/v1/push/deliveries','owner','Inspect sanitized push delivery results',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,notification_id,device_id,status,provider_code,created_at,updated_at FROM platform_deliveries ORDER BY created_at DESC LIMIT ? OFFSET ?',p.limit,p.offset).all()).results,...p};});
add('GET','/v1/notifications','user','List owned notifications',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,title,body,category,deep_link,created_at,read_at FROM platform_notifications WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?',c.a.id,p.limit,p.offset).all()).results,...p};});
add('GET','/v1/notifications/unread-count','user','Count unread owned notifications',undefined,async c=>({count:(await q(c.env,'SELECT COUNT(*) AS n FROM platform_notifications WHERE user_id=? AND read_at IS NULL AND deleted_at IS NULL',c.a.id).first()).n}));
add('POST','/v1/notifications/read-all','user','Mark own notifications as read',empty,async c=>{await q(c.env,'UPDATE platform_notifications SET read_at=? WHERE user_id=? AND read_at IS NULL AND deleted_at IS NULL',Date.now(),c.a.id).run();return {read:true};});
add('POST','/v1/notifications/{id}/read','user','Mark an owned notification as read',empty,c=>ownChange(c,'UPDATE platform_notifications SET read_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL RETURNING id,read_at',Date.now(),c.params.id,c.a.id));
add('DELETE','/v1/notifications/{id}','user','Dismiss an owned notification',undefined,c=>ownChange(c,'UPDATE platform_notifications SET deleted_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL RETURNING id',Date.now(),c.params.id,c.a.id));
add('POST','/v1/admin/notifications','recent_owner','Create an in-app notification for one active account',object({user_id:id,title:text(100),body:text(1000),category:z.enum(['system','account','security','label','payment','earnings','release','community','message','creator_tool','media_job','announcement','beta','maintenance']),deep_link:text(500)}),c=>notify(c.env,c.a,c.data,c.rid));
add('GET','/v1/favorites','user','List own favorite links',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,url,title,created_at FROM platform_favorites WHERE user_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',c.a.id,p.limit,p.offset).all()).results,...p};});
add('POST','/v1/favorites','user','Save a website shortcut',object({url:text(500),title:text(100)}),async c=>{const url=deepLink(c.data.url),id=uuid();await q(c.env,'INSERT INTO platform_favorites(id,user_id,url,title,created_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,url) DO UPDATE SET title=excluded.title',id,c.a.id,url,c.data.title,Date.now()).run();return q(c.env,'SELECT id,url,title FROM platform_favorites WHERE user_id=? AND url=?',c.a.id,url).first();});
add('DELETE','/v1/favorites/{id}','user','Delete an owned shortcut',undefined,c=>ownChange(c,'DELETE FROM platform_favorites WHERE id=? AND user_id=? RETURNING id',c.params.id,c.a.id));
add('POST','/v1/support/tickets','user','Submit a support ticket',object({category:z.enum(['technical','billing','accessibility','beta','account','creator_tools']),subject:text(160),body:text(6000)}),async c=>{const id=uuid();await c.env.DB.batch([q(c.env,"INSERT INTO platform_tickets(id,user_id,category,subject,body,status,created_at) VALUES(?,?,?,?,?,'open',?)",id,c.a.id,c.data.category,c.data.subject,c.data.body,Date.now()),audit(c.env,c.a.id,'support.created',id,c.rid)]);return {id,status:'open'};});
add('GET','/v1/support/tickets','user','List own support tickets',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,category,subject,status,created_at FROM platform_tickets WHERE user_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',c.a.id,p.limit,p.offset).all()).results,...p};});
add('GET','/v1/support/tickets/{id}','user','Read an owned support ticket',undefined,async c=>{const row=await q(c.env,'SELECT id,category,subject,body,status,created_at FROM platform_tickets WHERE id=? AND user_id=?',c.params.id,c.a.id).first();if(!row)throw new ApiError(404,'NOT_FOUND','Ticket not found.');return row;});
add('POST','/v1/beta/feedback','user','Submit beta feedback without automatic diagnostics',object({category:text(80),description:text(6000),platform:z.enum(['ios','android','web']),app_version:text(40),accessibility_impact:text(2000,0)}),async c=>{const id=uuid();await q(c.env,'INSERT INTO platform_feedback(id,user_id,category,description,platform,app_version,accessibility_impact,created_at) VALUES(?,?,?,?,?,?,?,?)',id,c.a.id,c.data.category,c.data.description,c.data.platform,c.data.app_version,c.data.accessibility_impact,Date.now()).run();return {id};});
add('GET','/v1/activity','user','Current account activity without security events',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,"SELECT id,action,target_id,created_at FROM platform_audit WHERE actor_id=? AND action IN ('profile.updated','support.created') ORDER BY created_at DESC LIMIT ? OFFSET ?",c.a.id,p.limit,p.offset).all()).results,...p};});
add('GET','/v1/security/events','owner','Sanitized security events',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,"SELECT * FROM platform_audit WHERE action LIKE 'owner.%' OR action LIKE 'session.%' OR result='denied' ORDER BY created_at DESC LIMIT ? OFFSET ?",p.limit,p.offset).all()).results,...p};});
add('GET','/v1/admin/audit','owner','Owner audit history',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT * FROM platform_audit ORDER BY created_at DESC LIMIT ? OFFSET ?',p.limit,p.offset).all()).results,...p};});
add('GET','/v1/diagnostics','owner','Safe platform diagnostics',undefined,async c=>({api_version:'v1',database:(await q(c.env,'SELECT 1 AS ok').first()).ok===1?'healthy':'unavailable',vault_configured:!!c.env.PLATFORM_VAULT_KEY,owner_mobile_enabled:await setting(c.env,'owner_mobile_enabled',false),server_media_jobs:await media.mediaWorkerReady(c.env)?'configured':'not_configured',web_push:(c.env.VAPID_PUBLIC_KEY||c.env.WEBPUSH_PUBLIC_KEY)?'configured':'not_configured',integrations:await catalog(c.env)}));
function finance(a:Actor){if(!['owner','admin','accountant','client'].includes(a.role))throw new ApiError(403,'PERMISSION_DENIED','This role cannot access financial records.');}
add('GET','/v1/label/dashboard','user','Label summary for the current role',undefined,c=>({profile:current(c.a),portal_url:'https://mrblindbandit.net/portal/',financial_records_are_manual:true}));
add('GET','/v1/label/earnings','user','Read permitted earnings records',undefined,async c=>{finance(c.a);const p=page(c.url);return {items:(await q(c.env,'SELECT id,client_id,description,source,period,currency,amount,status,reference,created_at FROM label_earnings '+(c.a.role==='client'?'WHERE client_id=? ':'')+'ORDER BY created_at DESC LIMIT ? OFFSET ?',...(c.a.role==='client'?[c.a.id]:[]),p.limit,p.offset).all()).results,...p};});
add('GET','/v1/label/contracts','user','Read permitted contract metadata',undefined,async c=>{if(!['owner','admin','manager','client'].includes(c.a.role))throw new ApiError(403,'PERMISSION_DENIED','This role cannot access contracts.');const p=page(c.url);return {items:(await q(c.env,'SELECT id,client_id,title,file_name,status,reviewed_at,created_at FROM label_contracts '+(c.a.role==='client'?'WHERE client_id=? ':'')+'ORDER BY created_at DESC LIMIT ? OFFSET ?',...(c.a.role==='client'?[c.a.id]:[]),p.limit,p.offset).all()).results,...p};});
add('GET','/v1/label/artists','user','Read permitted artist profiles',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,"SELECT m.id,m.artist_name,u.name FROM label_members m JOIN label_user u ON u.id=m.id WHERE m.role='client' AND m.status='active' "+(!['owner','admin','manager'].includes(c.a.role)?'AND m.id=? ':'')+'ORDER BY u.name LIMIT ? OFFSET ?',...(!['owner','admin','manager'].includes(c.a.role)?[c.a.id]:[]),p.limit,p.offset).all()).results,...p};});
const memberCreate=object({name:text(120),email:z.email(),role:z.enum(['admin','manager','accountant','client']),artistName:text(120,0).optional()});
add('GET','/v1/admin/users','owner','List existing label accounts',undefined,c=>legacy(c,'members'));
add('POST','/v1/admin/users','recent_owner','Invite a label account with an allowed role',memberCreate,c=>legacy(c,'members'));
add('PATCH','/v1/admin/users/{id}','recent_owner','Update an existing label role or account state',object({role:z.enum(['admin','manager','accountant','client']),status:z.enum(['active','suspended'])}),c=>legacy(c,'members/'+c.params.id));
add('GET','/v1/label/messages','user','Read a permitted client message thread',undefined,c=>legacy(c,'messages'));
add('POST','/v1/label/messages','user','Send a message within a permitted client thread',object({clientId:id.optional(),body:text(5000)}),c=>legacy(c,'messages'));
add('GET','/v1/label/payments','user','Read permitted existing payment information',undefined,c=>legacy(c,'payments'));
add('GET','/v1/label/tasks','user','Read permitted existing client tasks',undefined,c=>legacy(c,'tasks'));
add('POST','/v1/label/tasks','user','Create a task subject to existing project permissions',object({clientId:id,title:text(200),details:text(3000,0).optional(),dueDate:text(10,0).optional()}),c=>legacy(c,'tasks'));
add('POST','/v1/label/earnings','user','Record earnings subject to existing finance permissions',object({clientId:id,description:text(200),source:text(120),period:text(60),currency:z.enum(['USD','PHP','EUR','GBP','CAD','AUD']),amount:z.string().regex(/^-?\d{1,10}(\.\d{1,2})?$/),status:z.enum(['reported','payable','paid','adjustment']),reference:text(200,0).optional()}),c=>legacy(c,'earnings'));
add('GET','/v1/announcements','user','Read existing announcements allowed for this account',undefined,c=>legacy(c,'operations/announcements'));
add('POST','/v1/admin/announcements','recent_owner','Create a label announcement',object({title:text(160),body:text(6000),audience:z.enum(['all','staff','clients']),status:z.enum(['draft','published','archived'])}),c=>legacy(c,'operations/announcements'));
add('GET','/v1/search','user','Search existing label records with role filters',undefined,c=>legacy(c,'tools/search'));
add('GET','/v1/label/workspaces','user','Discover available label workspace modules and field schemas',undefined,c=>({items:workspaceModules.filter(m=>m.roles.includes(c.a.role))}));
const workspaceInput=object({title:text(200),status:text(100),owner:text(120,0).optional(),dueDate:text(10,0).optional(),details:z.record(z.string(),z.string().max(6000)),checklist:z.array(z.boolean()).max(100),revision:z.number().int().positive().optional(),archived:z.boolean().optional()});
add('GET','/v1/label/workspaces/{module}','user','Read an existing workspace subject to its role policy',undefined,c=>legacy(c,'workspace/'+c.params.module));
add('POST','/v1/label/workspaces/{module}','user','Create a validated workspace record',workspaceInput,c=>legacy(c,'workspace/'+c.params.module));
add('PATCH','/v1/label/workspaces/{module}/{id}','user','Update a workspace record using its revision',workspaceInput,c=>legacy(c,'workspace/'+c.params.module+'/'+c.params.id));
add('GET','/v1/label/releases','user','Read existing release plans subject to label permissions',undefined,c=>legacy(c,'workspace/release-plans'));
add('POST','/v1/label/releases','user','Create a validated release plan',workspaceInput,c=>legacy(c,'workspace/release-plans'));
add('PATCH','/v1/label/releases/{id}','user','Update a release plan using its current revision',workspaceInput,c=>legacy(c,'workspace/release-plans/'+c.params.id));
add('GET','/v1/tools','user','List background tools and processor readiness',undefined,async c=>({items:media.toolsCatalog,processor_configured:await media.mediaWorkerReady(c.env)}));
add('POST','/v1/uploads','user','Reserve private media storage (1 GB per account)',object({filename:text(200),content_type:z.enum(['audio/wav','audio/mpeg','audio/flac','audio/mp4','video/mp4','image/png','image/jpeg','image/webp']),size_bytes:z.number().int().min(12).max(250*1024*1024)}),c=>media.reserve(c.env,c.a,c.data,c.rid));
add('PUT','/v1/uploads/{id}','user','Stream reserved bytes with exact Content-Type and Content-Length',undefined,c=>media.upload(c.request,c.env,c.a,c.params.id,c.rid));
add('GET','/v1/media','user','List owned private media',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,filename,content_type,size_bytes,status,created_at FROM platform_media WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT ? OFFSET ?',c.a.id,p.limit,p.offset).all()).results,...p};});
add('GET','/v1/media/{id}','user','Read owned media metadata',undefined,c=>media.mediaRecord(c.env,c.a.id,c.params.id));
add('GET','/v1/media/{id}/download','user','Download owned media using authentication',undefined,c=>media.download(c.env,c.a.id,c.params.id));
add('DELETE','/v1/media/{id}','user','Delete owned media after confirmation',object({confirmation:z.literal('DELETE MEDIA')}),async c=>{await media.mediaRecord(c.env,c.a.id,c.params.id);const active=await q(c.env,"SELECT id FROM platform_jobs WHERE user_id=? AND (media_id=? OR json_extract(options,'$.artwork_id')=?) AND status IN ('queued','processing') LIMIT 1",c.a.id,c.params.id,c.params.id).first();if(active)throw new ApiError(409,'MEDIA_IN_USE','Cancel the active job before deleting its input.');await q(c.env,"UPDATE platform_media SET status='deleted',deleted_at=? WHERE id=? AND user_id=?",Date.now(),c.params.id,c.a.id).run();await c.env.BUCKET.delete('private/platform-media/'+c.params.id);await audit(c.env,c.a.id,'media.deleted',c.params.id,c.rid).run();return {deleted:true};});
const jobOptions=object({format:z.enum(['wav','mp3','flac','m4a']).default('wav'),start_seconds:z.number().min(0).max(86400).default(0),duration_seconds:z.number().min(1).max(3600).default(300),width:z.number().int().min(128).max(3840).default(1920),height:z.number().int().min(128).max(3840).default(1080),sample_rate:z.enum(['44100','48000','96000']).default('48000'),bitrate:z.enum(['128k','192k','256k','320k']).default('320k'),show_waveform:z.boolean().default(true),title:text(120,0).default(''),artist:text(120,0).default(''),artwork_id:id.optional()});
add('POST','/v1/tools/jobs','user','Queue an idempotent background media job',object({tool:z.enum(['audio-converter','audio-clipper','audio-normalizer','artwork-resizer','art-track','audiogram']),media_id:id,idempotency_key:text(100,8),options:jobOptions}),c=>media.createJob(c.env,c.a,c.data,c.rid));
add('GET','/v1/tools/jobs','user','List own processing jobs',undefined,async c=>{const p=page(c.url);return {items:(await q(c.env,'SELECT id,media_id,tool,status,output_id,error_code,created_at,updated_at FROM platform_jobs WHERE user_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?',c.a.id,p.limit,p.offset).all()).results,...p};});
add('GET','/v1/tools/jobs/{id}','user','Read an owned processing job',undefined,async c=>{const r=await q(c.env,'SELECT id,media_id,tool,status,output_id,error_code,created_at,updated_at FROM platform_jobs WHERE id=? AND user_id=?',c.params.id,c.a.id).first();if(!r)throw new ApiError(404,'NOT_FOUND','Job not found.');return r;});
add('DELETE','/v1/tools/jobs/{id}','user','Cancel an owned queued or running job',undefined,c=>ownChange(c,"UPDATE platform_jobs SET status='cancelled',lease_hash=NULL,updated_at=? WHERE id=? AND user_id=? AND status IN ('queued','processing') RETURNING id,status",Date.now(),c.params.id,c.a.id));
add('POST','/v1/worker/jobs/claim','worker','Claim a queued job using the media-worker credential',empty,c=>media.claim(c.request,c.env));
add('GET','/v1/worker/jobs/{id}/input','worker','Download input for an authenticated leased job',undefined,c=>media.workerInput(c.request,c.env,c.params.id));
add('GET','/v1/worker/jobs/{id}/artwork','worker','Download artwork for an authenticated leased job',undefined,c=>media.workerInput(c.request,c.env,c.params.id,true));
add('PUT','/v1/worker/jobs/{id}/output','worker','Upload output for an authenticated leased job',undefined,c=>media.workerOutput(c.request,c.env,c.params.id,c.rid));
add('POST','/v1/worker/jobs/{id}/fail','worker','Mark an authenticated leased job failed',empty,c=>media.failJob(c.request,c.env,c.params.id,c.rid));

/* ——— Notifications: unregister, web push, topics ——— */
add('POST','/v1/push/unregister','user','Unregister a device token by id or installation',object({device_id:id.optional(),installation_id:text(100,0).optional()}),c=>unregister(c.env,c.a,c.data,c.rid));
add('POST','/v1/push/web/register','social','Register a Web Push subscription for the signed-in Clerk user',object({endpoint:text(2048),keys:object({p256dh:text(200),auth:text(200)}),user_agent:text(400,0).optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return registerWebPush(c.env,{id:me.id},c.data,c.rid);});
add('POST','/v1/push/web/unregister','social','Unregister a Web Push subscription',object({endpoint:text(2048,0).optional(),subscription_id:id.optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return unregisterWebPush(c.env,{id:me.id},c.data,c.rid);});
add('GET','/v1/push/web/vapid-public-key','public','Public VAPID key for browser PushManager.subscribe',undefined,c=>vapidPublicConfig(c.env));
add('GET','/v1/push/topics','public','List notification topics',undefined,c=>listTopics(c.env));
add('GET','/v1/push/topics/subscriptions','social','List topics the current user is subscribed to',undefined,async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return listTopicSubscriptions(c.env,me.id);});
add('POST','/v1/push/topics/{name}/subscribe','social','Subscribe to a notification topic',empty,async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return subscribeTopic(c.env,{id:me.id},c.params.name,c.rid);});
add('DELETE','/v1/push/topics/{name}/subscribe','social','Unsubscribe from a notification topic',undefined,async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return unsubscribeTopic(c.env,{id:me.id},c.params.name,c.rid);});
add('POST','/v1/social/devices','social','Register iOS/Android FCM/APNs device token (apps alias)',object({installation_id:text(100),platform:z.enum(['ios','android']),token:text(4096),app_version:text(40),language:text(20),provider:z.enum(['fcm','apns','firebase']).optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return register(c.env,{id:me.id},c.data,c.rid);});
add('GET','/v1/social/devices','social','List own registered app devices (no raw tokens)',undefined,async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return {items:(await q(c.env,'SELECT id,installation_id,platform,app_version,language,enabled,created_at,updated_at FROM platform_devices WHERE user_id=? ORDER BY created_at DESC LIMIT 20',me.id).all()).results};});
add('DELETE','/v1/social/devices','social','Unregister device by installation_id or device_id',object({device_id:id.optional(),installation_id:text(100,0).optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return unregister(c.env,{id:me.id},c.data,c.rid);});
add('POST','/v1/social/devices/register','social','Register iOS/Android device token for Blindbandit Mobile apps',object({installation_id:text(100),platform:z.enum(['ios','android']),token:text(4096),app_version:text(40),language:text(20)}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return register(c.env,{id:me.id},c.data,c.rid);});
add('POST','/v1/social/devices/unregister','social','Unregister a Blindbandit Mobile app device',object({device_id:id.optional(),installation_id:text(100,0).optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return unregister(c.env,{id:me.id},c.data,c.rid);});
add('POST','/v1/notifications/test','social','Send a test notification to the current user devices',object({environment:environment.optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return notifyAndDeliver(c.env,me.id,{user_id:me.id,title:'Blindbandit test',body:'Push delivery scaffolding is working.',category:'system',deep_link:'/mobile/'},c.rid,c.data.environment||'production');});

/* ——— LiveKit ——— */
add('GET','/v1/livekit/status','public','Public LiveKit configuration status (no secrets)',undefined,c=>livekitPublicStatus(c.env));
add('POST','/v1/livekit/token','social','Mint a LiveKit room access token for the owner LiveKit server',object({room:text(128),identity:text(128,0).optional(),name:text(100,0).optional(),can_publish:z.boolean().optional(),can_subscribe:z.boolean().optional(),ttl_seconds:z.number().int().min(60).max(86400).optional(),room_type:z.enum(['voice','video','data']).optional()}),async c=>{
  const a=c.a as SocialActor;
  const me=await social.getOrCreateProfile(c.env,a);
  await socialAdmin.assertCanCall(c.env,me.id);
  const identity=c.data.identity||me.id;
  return mintLiveKitToken(c.env,{identity,name:c.data.name||me.display_name||a.name,room:c.data.room,canPublish:c.data.can_publish,canSubscribe:c.data.can_subscribe,ttlSeconds:c.data.ttl_seconds,roomType:c.data.room_type||'video',metadata:JSON.stringify({handle:me.handle,email:a.email})});
});

/* ——— Social /mobile ——— */
add('GET','/v1/social/health','public','Social product liveness',undefined,async c=>{await social.ensureSeedArtist(c.env);return {status:'ok',product:'blindbandit-mobile'};});
add('GET','/v1/social/spotify','public','Official Spotify artist embeds for Music tab',undefined,()=>social.spotifyArtistCatalog());
add('GET','/v1/social/explore','public','Explore public profiles',undefined,c=>social.explore(c.env,c.url));
add('GET','/v1/social/feed','public','Public social feed (optional following mode when signed in)',undefined,async c=>{let viewer:SocialActor|undefined;try{viewer=await socialAuthenticate(c.request,c.env);}catch{}return social.listFeed(c.env,c.url,viewer);});
add('GET','/v1/social/profiles/{handle}','public','Public profile by handle',undefined,c=>social.getProfileByHandle(c.env,c.params.handle));
add('GET','/v1/social/profiles/{handle}/posts','public','Posts for a public profile',undefined,c=>social.listProfilePosts(c.env,c.params.handle,c.url));
add('GET','/v1/social/me','social','Current social profile (creates on first call)',undefined,async c=>{const row=await social.getOrCreateProfile(c.env,c.a as SocialActor);return social.getProfileByHandle(c.env,row.handle);});
add('POST','/v1/social/me','social','Create or ensure social profile',object({handle:text(30,0).optional(),display_name:text(100,0).optional(),bio:text(2000,0).optional()}),async c=>{const row=await social.getOrCreateProfile(c.env,c.a as SocialActor,c.data);return social.getProfileByHandle(c.env,row.handle);});
add('PATCH','/v1/social/me','social','Update social profile',object({handle:text(30,0).optional(),display_name:text(100,0).optional(),bio:text(2000,0).optional(),avatar_url:text(500,0).optional(),cover_url:text(500,0).optional(),location:text(120,0).optional(),website:text(500,0).optional()}),c=>social.updateProfile(c.env,c.a as SocialActor,c.data,c.rid));
add('POST','/v1/social/posts','social','Create a public post (open to any Clerk account)',object({body:text(4000),media:z.array(z.string().max(500)).max(8).optional()}),c=>social.createPost(c.env,c.a as SocialActor,c.data,c.rid));
add('DELETE','/v1/social/posts/{id}','social','Delete own post',undefined,c=>social.deletePost(c.env,c.a as SocialActor,c.params.id,c.rid));
add('POST','/v1/social/profiles/{handle}/follow','social','Follow a profile',empty,c=>social.follow(c.env,c.a as SocialActor,c.params.handle,c.rid));
add('DELETE','/v1/social/profiles/{handle}/follow','social','Unfollow a profile',undefined,c=>social.unfollow(c.env,c.a as SocialActor,c.params.handle,c.rid));
add('GET','/v1/social/messages','social','List conversations',undefined,c=>social.listConversations(c.env,c.a as SocialActor,c.url));
add('GET','/v1/social/messages/{id}','social','List messages in a conversation',undefined,c=>social.listMessages(c.env,c.a as SocialActor,c.params.id,c.url));
add('POST','/v1/social/messages','social','Send a direct message',object({handle:text(30),body:text(4000)}),c=>social.sendMessage(c.env,c.a as SocialActor,c.data,c.rid));
add('POST','/v1/social/calls','social','Start a voice or video call (LiveKit room)',object({handle:text(30),kind:z.enum(['voice','video']).default('voice')}),c=>social.startCall(c.env,c.a as SocialActor,c.data,c.rid));
add('POST','/v1/social/calls/{id}/join','social','Join an existing call and receive a LiveKit token',empty,c=>social.joinCall(c.env,c.a as SocialActor,c.params.id));
add('POST','/v1/social/calls/{id}/end','social','End a call',empty,c=>social.endCall(c.env,c.a as SocialActor,c.params.id,c.rid));
add('POST','/v1/social/verification','social','Apply for profile verification',object({evidence:text(4000,0).optional()}),c=>social.applyVerification(c.env,c.a as SocialActor,c.data,c.rid));
add('POST','/v1/social/verification/{id}/review','social','Approve or reject verification (operator)',object({approve:z.boolean(),note:text(1000,0).optional()}),c=>social.reviewVerification(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/monetization','social','Apply to creator monetization program',object({payout_email:z.string().email().optional(),notes:text(2000,0).optional()}),c=>social.applyMonetization(c.env,c.a as SocialActor,c.data,c.rid));
add('GET','/v1/social/ads','public','List active marketplace ads',undefined,c=>social.listAds(c.env,c.url));
add('POST','/v1/social/ads','social','Submit an ads marketplace listing',object({title:text(120),body:text(1000),target_url:text(500),budget_cents:z.number().int().min(0).max(100000000).optional()}),c=>social.createAd(c.env,c.a as SocialActor,c.data,c.rid));


/* ——— Social admin (moderator / operator) ——— */
add('GET','/v1/social/admin/overview','social_admin','Social admin dashboard counters',undefined,c=>socialAdmin.adminOverview(c.env));
add('GET','/v1/social/admin/users','social_admin','Search and list social profiles with moderation state',undefined,c=>socialAdmin.searchUsers(c.env,c.url));
add('POST','/v1/social/admin/users/{id}/ban','social_admin','Permanently ban a social account',object({reason:text(1000,0).optional()}),c=>socialAdmin.banUser(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/admin/users/{id}/suspend','social_admin','Temporarily suspend a social account',object({reason:text(1000,0).optional(),until:z.number().int().positive()}),c=>socialAdmin.suspendUser(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/admin/users/{id}/reinstate','social_admin','Unban or unsuspend a social account',empty,c=>socialAdmin.reinstateUser(c.env,c.a as SocialActor,c.params.id,c.rid));
add('PATCH','/v1/social/admin/users/{id}/restrictions','social_admin','Mute posts/messages, disable calls, shadow-restrict, rate limits, feature flags',object({mute_posts:z.boolean().optional(),mute_messages:z.boolean().optional(),calls_disabled:z.boolean().optional(),shadow_restricted:z.boolean().optional(),rate_limit_multiplier:z.number().int().min(1).max(20).optional(),feature_flags:z.record(z.string(),z.boolean()).optional()}),c=>socialAdmin.setRestrictions(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/admin/users/{id}/verify','social_admin','Force-verify a profile',empty,c=>socialAdmin.forceVerify(c.env,c.a as SocialActor,c.params.id,true,c.rid));
add('POST','/v1/social/admin/users/{id}/unverify','social_admin','Revoke verification badge',empty,c=>socialAdmin.forceVerify(c.env,c.a as SocialActor,c.params.id,false,c.rid));
add('GET','/v1/social/admin/users/{id}/devices','social_admin','Inspect redacted push devices for a profile',undefined,c=>socialAdmin.inspectDevices(c.env,c.params.id));
add('POST','/v1/social/admin/users/{id}/devices/revoke','social_admin','Revoke all push tokens for a profile',empty,c=>socialAdmin.revokeAllTokens(c.env,c.a as SocialActor,c.params.id,c.rid));
add('POST','/v1/social/admin/users/{id}/calls/disconnect','social_admin','Force-end LiveKit calls for a profile',empty,c=>socialAdmin.forceDisconnectCalls(c.env,c.a as SocialActor,c.params.id,c.rid));
add('POST','/v1/social/admin/users/{id}/monetization','social_admin','Approve or reject monetization',object({approve:z.boolean().optional(),status:text(40,0).optional()}),c=>socialAdmin.reviewMonetization(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('GET','/v1/social/admin/verification','social_admin','Verification review queue',undefined,c=>socialAdmin.listVerificationQueue(c.env,c.url));
add('GET','/v1/social/admin/reports','social_admin','List content reports',undefined,c=>socialAdmin.listReports(c.env,c.url));
add('POST','/v1/social/admin/reports/{id}/resolve','social_admin','Resolve, dismiss, or escalate a report',object({status:z.enum(['resolved','dismissed','escalated']).optional(),note:text(1000,0).optional()}),c=>socialAdmin.resolveReport(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/admin/posts/{id}/hide','social_admin','Hide a post from public feeds',empty,c=>socialAdmin.hidePost(c.env,c.a as SocialActor,c.params.id,true,c.rid));
add('POST','/v1/social/admin/posts/{id}/unhide','social_admin','Unhide a post',empty,c=>socialAdmin.hidePost(c.env,c.a as SocialActor,c.params.id,false,c.rid));
add('DELETE','/v1/social/admin/posts/{id}','social_admin','Admin-delete a post',undefined,c=>socialAdmin.deletePostAdmin(c.env,c.a as SocialActor,c.params.id,c.rid));
add('GET','/v1/social/admin/ads','social_admin','List pending ads marketplace listings',undefined,c=>socialAdmin.listPendingAds(c.env,c.url));
add('POST','/v1/social/admin/ads/{id}/review','social_admin','Approve or reject an ads listing',object({approve:z.boolean().optional(),status:text(40,0).optional()}),c=>socialAdmin.reviewAd(c.env,c.a as SocialActor,c.params.id,c.data,c.rid));
add('POST','/v1/social/admin/broadcast','social_admin','Create system announcement and notify recent users',object({title:text(120),body:text(2000),audience:text(40,0).optional(),deep_link:text(500,0).optional()}),c=>socialAdmin.broadcast(c.env,c.a as SocialActor,c.data,c.rid));
add('GET','/v1/social/admin/audit','social_admin','Social admin action audit log',undefined,c=>socialAdmin.listAdminAudit(c.env,c.url));
add('POST','/v1/social/admin/notifications/test','social_admin','Admin test push to a profile id',object({user_id:id,title:text(100,0).optional(),body:text(1000,0).optional(),environment:environment.optional()}),async c=>notifyAndDeliver(c.env,(c.a as SocialActor).clerkUserId,{user_id:c.data.user_id,title:c.data.title||'Admin test',body:c.data.body||'Test notification from Social Admin.',category:'system',deep_link:'/mobile/'},c.rid,c.data.environment||'production'));
add('POST','/v1/social/reports','social','Report a post, profile, or message',object({target_type:z.enum(['post','profile','message','call']),target_id:id,reason:text(200),details:text(2000,0).optional()}),async c=>{const me=await social.getOrCreateProfile(c.env,c.a as SocialActor);return socialAdmin.createReport(c.env,me.id,c.data);});

export function openapi(){const paths:Record<string,any>={};for(const route of routes){const parameters=[...route.path.matchAll(/\{(\w+)\}/g)].map(m=>({name:m[1],in:'path',required:true,schema:{type:'string',maxLength:100}}));paths[route.path]??={};paths[route.path][route.method.toLowerCase()]={summary:route.summary,operationId:route.method.toLowerCase()+route.path.replace(/[^a-zA-Z0-9]/g,'_'),security:route.access==='public'?[]:route.access==='worker'?[{mediaWorker:[]}]:(route.access==='social'||route.access==='social_admin')?[{clerkSession:[]}]:[{bearerAuth:[]},{websiteCookie:[]}],'x-required-access':route.access,parameters:[...parameters,...(route.method==='GET'?[{name:'limit',in:'query',schema:{type:'integer',minimum:1,maximum:100,default:25}},{name:'offset',in:'query',schema:{type:'integer',minimum:0,maximum:100000,default:0}}]:[])],...(route.schema?{requestBody:{required:true,content:{'application/json':{schema:z.toJSONSchema(route.schema,{io:'input'})}}}}:{}),responses:{'200':{description:'Successful response. data contains the operation result.',content:{'application/json':{schema:{$ref:'#/components/schemas/Success'}}}},...Object.fromEntries([400,401,403,404,409,413,415,429,503].map(s=>[s,{description:'Request rejected',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}]))}};}return {openapi:'3.1.0',info:{title:'Blindbandit Platform API',version:'1.0.0',description:'Blindbandit Platform API. Label portal routes require an active label account. Social /mobile routes (access=social) accept any verified Clerk account (Google or email; Apple Sign In is disabled). Paths are available under /v1 and /api/v1 on mrblindbandit.net and api.mrblindbandit.net.'},servers:[{url:'https://mrblindbandit.net'},{url:'https://api.mrblindbandit.net'}],paths,components:{securitySchemes:{mediaWorker:{type:'http',scheme:'bearer',description:'Dedicated media processor credential. Leased operations additionally require X-Job-Lease.'},bearerAuth:{type:'http',scheme:'bearer'},websiteCookie:{type:'apiKey',in:'cookie',name:'blindbandit_label.session_token'},clerkSession:{type:'http',scheme:'bearer',description:'Clerk session JWT from the browser or mobile Clerk SDK. Required for social /mobile routes.'}},schemas:{Success:{type:'object',required:['success','data','meta'],properties:{success:{const:true},data:{},meta:{type:'object',required:['request_id','api_version'],properties:{request_id:{type:'string'},api_version:{const:'v1'}}}}},Error:{type:'object',required:['success','error'],properties:{success:{const:false},error:{type:'object',required:['code','message','request_id'],properties:{code:{type:'string'},message:{type:'string'},request_id:{type:'string'}}}}}}}};}
export async function platformApi(request:Request,env:Env):Promise<Response>{const rid=uuid(),url=new URL(request.url);let actor:AnyActor|undefined;
 const headers=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'private, no-store','x-request-id':rid,'x-content-type-options':'nosniff','referrer-policy':'no-referrer','vary':'Origin, Cookie, Authorization'});const origin=request.headers.get('origin');if(origin&&origins.includes(origin)){headers.set('access-control-allow-origin',origin);headers.set('access-control-allow-credentials','true');headers.set('access-control-expose-headers','X-Request-ID');}
 const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers});
 try{guardOrigin(request);const pathname=url.pathname.replace(/^\/api(?=\/v1\/)/,'');if(request.method==='OPTIONS'){headers.set('access-control-allow-methods','GET, POST, PATCH, PUT, DELETE, OPTIONS');headers.set('access-control-allow-headers','Authorization, Content-Type, Idempotency-Key');headers.set('access-control-max-age','600');return new Response(null,{status:204,headers});}
 if(url.pathname==='/openapi.json'||url.pathname==='/api/openapi.json'){if(request.method!=='GET')throw new ApiError(405,'METHOD_NOT_ALLOWED','Use GET.');return json(openapi());}
 const matched=routes.map(route=>{const names=[...route.path.matchAll(/\{(\w+)\}/g)].map(m=>m[1]);const pattern='^'+route.path.replace(/\{\w+\}/g,'([^/]+)')+'/?$';const m=pathname.match(pattern);return m?{route,params:Object.fromEntries(names.map((n,i)=>[n,m[i+1]]))}:null;}).filter(Boolean) as {route:Route;params:Record<string,string>}[];
 const selected=matched.find(r=>r.route.method===request.method);if(!selected)throw new ApiError(matched.length?405:404,matched.length?'METHOD_NOT_ALLOWED':'NOT_FOUND',matched.length?'This method is not supported.':'API route not found.');
 const {route,params}=selected;
 if(pathname!=='/v1/system/health'){if(!env.DB)throw new ApiError(503,'DATABASE_UNAVAILABLE','The service is not ready.');const sensitive=/\/(auth|owner)\//.test(url.pathname);await limit(env,'ip:'+request.headers.get('cf-connecting-ip')+':'+(sensitive?'auth':'api'),sensitive?20:180);}
 if(route.access==='worker')await media.workerAuth(request,env);
 if(route.access==='social'||route.access==='social_admin'){actor=await socialAuthenticate(request,env);await limit(env,'social:'+actor.id,240);if(route.access==='social_admin')socialAdmin.assertSocialAdmin(actor as SocialActor,env);}else if(route.access!=='public'&&route.access!=='worker'){actor=await authenticate(request,env);await limit(env,'user:'+actor.id,180);if(pathname.endsWith('/reauthenticate'))await limit(env,'reauth:'+actor.id,10);if(route.access==='owner'||route.access==='recent_owner')owner(actor as Actor);if(route.access==='recent_owner')recent(actor as Actor);}
 let data:any={};if(route.schema){const parsed=route.schema.safeParse(await input(request));if(!parsed.success)throw new ApiError(400,'INVALID_INPUT','Check required fields, supported values, and length limits.');data=parsed.data;}
 const result=await route.handler({request,env,a:actor!,data,params,rid,url});if(result instanceof Response){const h=new Headers(result.headers);for(const [k,v] of headers)if(!['content-type'].includes(k))h.set(k,v);return new Response(result.body,{status:result.status,headers:h});}return json({success:true,data:result,meta:{request_id:rid,api_version:'v1'}});
 }catch(error){const e=error instanceof ApiError?error:new ApiError(503,'SERVICE_UNAVAILABLE','The service could not complete this request.');if(e.status===403&&env.DB)try{await audit(env,actor?.id||'anonymous','access.denied',url.pathname.slice(0,200),rid,'denied').run();}catch{}if(!(error instanceof ApiError))console.error(JSON.stringify({event:'platform.error',request_id:rid,route:url.pathname.slice(0,200)}));if(e.status===429)headers.set('retry-after','60');return json({success:false,error:{code:e.code,message:e.message,request_id:rid}},e.status);}
}
