export type Env = {DB:any;BUCKET:any;[key:string]:any};
export class ApiError extends Error {constructor(public status:number,public code:string,message:string){super(message);}}
export const q=(env:Env,sql:string,...args:any[])=>env.DB.prepare(sql).bind(...args);
export const uuid=()=>crypto.randomUUID();
export const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),v=>v.toString(16).padStart(2,'0')).join('');
export const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');
export async function equal(a:string,b:string){const x=await hash(a),y=await hash(b);let n=0;for(let i=0;i<x.length;i++)n|=x.charCodeAt(i)^y.charCodeAt(i);return n===0;}
export const origins=['https://mrblindbandit.net','https://www.mrblindbandit.net','https://portal.mrblindbandit.net','https://api.mrblindbandit.net','https://mr-blind-bandit.mrblindbandit.chatgpt.site','http://localhost:5173','http://127.0.0.1:5173'];
export function guardOrigin(request:Request){const origin=request.headers.get('origin');if(origin&&!origins.includes(origin))throw new ApiError(403,'ORIGIN_DENIED','This origin is not allowed.');if(!['GET','HEAD','OPTIONS'].includes(request.method)&&!request.headers.has('authorization')&&!origin&&!(!request.headers.has('cookie')&&['/v1/owner/bootstrap','/v1/auth/refresh'].includes(new URL(request.url).pathname)))throw new ApiError(403,'ORIGIN_REQUIRED','A trusted origin is required for browser actions.');}
export async function input(request:Request,max=65536){if(request.headers.get('content-type')?.split(';')[0].trim()!=='application/json')throw new ApiError(415,'JSON_REQUIRED','Use application/json.');const reader=request.body?.getReader();if(!reader)throw new ApiError(400,'INVALID_JSON','A JSON object is required.');let size=0;const chunks:Uint8Array[]=[];while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>max){await reader.cancel();throw new ApiError(413,'BODY_TOO_LARGE','The request is too large.');}chunks.push(r.value);}let data:any;try{data=JSON.parse(await new Blob(chunks as BlobPart[]).text());}catch{throw new ApiError(400,'INVALID_JSON','Enter valid JSON.');}if(!data||Array.isArray(data)||typeof data!=='object')throw new ApiError(400,'INVALID_JSON','A JSON object is required.');return data;}
export function fields(data:any,allowed:string[]){if(Object.keys(data).some(k=>!allowed.includes(k)))throw new ApiError(400,'UNKNOWN_FIELD','Remove unsupported fields.');}
export function str(value:any,max=200,min=1){if(typeof value!=='string'||value.trim().length<min||value.length>max)throw new ApiError(400,'INVALID_INPUT','Check the required text fields and length limits.');return value.trim();}
export function choice(value:any,values:string[]){if(!values.includes(value))throw new ApiError(400,'INVALID_INPUT','Choose a supported option.');return value as string;}
export function page(url:URL){const limit=Number(url.searchParams.get('limit')||25),offset=Number(url.searchParams.get('offset')||0);if(!Number.isInteger(limit)||limit<1||limit>100||!Number.isInteger(offset)||offset<0||offset>100000)throw new ApiError(400,'INVALID_PAGINATION','Use limit 1–100 and a nonnegative offset.');return {limit,offset};}
export async function limit(env:Env,key:string,max=60,period=60000){const window=Math.floor(Date.now()/period);const row=await q(env,'INSERT INTO platform_limits (key,window,hits) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET window=excluded.window,hits=CASE WHEN platform_limits.window=excluded.window THEN platform_limits.hits+1 ELSE 1 END WHERE platform_limits.window<>excluded.window OR platform_limits.hits<? RETURNING hits',await hash(key),window,max).first();if(!row)throw new ApiError(429,'RATE_LIMITED','Too many requests. Try again shortly.');}
export const audit=(env:Env,actor:string,action:string,target:string,requestId:string,result='success')=>q(env,'INSERT INTO platform_audit(id,actor_id,action,target_id,request_id,result,created_at) VALUES(?,?,?,?,?,?,?)',uuid(),actor,action,target,requestId,result,Date.now());
export async function setting(env:Env,key:string,fallback:any=null){const row=await q(env,'SELECT value FROM platform_settings WHERE key=?',key).first();return row?JSON.parse(row.value):fallback;}
export const setSetting=(env:Env,key:string,value:any)=>q(env,'INSERT INTO platform_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,JSON.stringify(value));
export async function encrypt(env:Env,value:string,context:string){if(!env.PLATFORM_VAULT_KEY||!/^[0-9a-f]{64}$/i.test(env.PLATFORM_VAULT_KEY))throw new ApiError(503,'VAULT_NOT_CONFIGURED','The server encryption key has not been configured.');const bytes=new Uint8Array(env.PLATFORM_VAULT_KEY.match(/../g).map((v:string)=>parseInt(v,16)));const key=await crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(context)},key,new TextEncoder().encode(value)));return JSON.stringify({v:1,iv:Array.from(iv),cipher:Array.from(cipher)});}
export async function decrypt(env:Env,value:string,context:string){if(!env.PLATFORM_VAULT_KEY||!/^[0-9a-f]{64}$/i.test(env.PLATFORM_VAULT_KEY))throw new ApiError(503,'VAULT_NOT_CONFIGURED','The server encryption key has not been configured.');const parsed=JSON.parse(value);if(parsed.v!==1)throw new Error('Unsupported encryption version');const bytes=new Uint8Array(env.PLATFORM_VAULT_KEY.match(/../g).map((v:string)=>parseInt(v,16)));const key=await crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(parsed.iv),additionalData:new TextEncoder().encode(context)},key,new Uint8Array(parsed.cipher)));}
