import {ApiError,q,uuid,encrypt,decrypt,audit,type Env} from './core';
export const providers:Record<string,{name:string;public:string[];secret:string[];required:string[];env:Record<string,string>}>={
 media_worker:{name:'Background Media Processor',public:[],secret:['worker_key'],required:['worker_key'],env:{}},
 clerk:{name:'Clerk',public:['publishable_key'],secret:['secret_key','webhook_secret'],required:['secret_key'],env:{publishable_key:'CLERK_PUBLISHABLE_KEY',secret_key:'CLERK_SECRET_KEY'}},
 resend:{name:'Resend',public:['from_address'],secret:['api_key','webhook_secret'],required:['api_key'],env:{api_key:'RESEND_API_KEY',from_address:'PORTAL_EMAIL_FROM'}},
 stripe:{name:'Stripe',public:['publishable_key'],secret:['secret_key','webhook_secret'],required:['secret_key'],env:{secret_key:'STRIPE_SECRET_KEY',publishable_key:'STRIPE_PUBLISHABLE_KEY',webhook_secret:'STRIPE_WEBHOOK_SECRET'}},
 cloudinary:{name:'Cloudinary',public:['cloud_name','api_key'],secret:['api_secret'],required:['cloud_name','api_key','api_secret'],env:{cloud_name:'CLOUDINARY_CLOUD_NAME',api_key:'CLOUDINARY_API_KEY',api_secret:'CLOUDINARY_API_SECRET'}},
 apns:{name:'Apple Push Notifications',public:['team_id','key_id','bundle_id'],secret:['private_key'],required:['team_id','key_id','bundle_id','private_key'],env:{team_id:'APNS_TEAM_ID',key_id:'APNS_KEY_ID',bundle_id:'APNS_BUNDLE_ID',private_key:'APNS_PRIVATE_KEY'}},
 fcm:{name:'Firebase Cloud Messaging',public:['project_id'],secret:['service_account_json'],required:['project_id','service_account_json'],env:{project_id:'FCM_PROJECT_ID',service_account_json:'FCM_SERVICE_ACCOUNT_JSON'}},
 livekit:{name:'LiveKit',public:['url'],secret:['api_key','api_secret'],required:['api_key','api_secret'],env:{url:'LIVEKIT_URL',api_key:'LIVEKIT_API_KEY',api_secret:'LIVEKIT_API_SECRET'}},
 webpush:{name:'Web Push',public:['public_key','contact'],secret:['private_key'],required:['public_key','private_key','contact'],env:{public_key:'VAPID_PUBLIC_KEY',private_key:'VAPID_PRIVATE_KEY',contact:'VAPID_SUBJECT'}},
 github:{name:'GitHub',public:[],secret:['api_token','webhook_secret'],required:['api_token'],env:{}},
 cloudflare:{name:'Cloudflare',public:['account_id'],secret:['api_token'],required:['api_token'],env:{}}
};
export function provider(name:string){const p=providers[name];if(!p)throw new ApiError(404,'PROVIDER_NOT_FOUND','Integration not found.');return p;}
export async function credentials(env:Env,name:string,environment='production'){const p=provider(name),row=await q(env,'SELECT * FROM platform_integrations WHERE provider=? AND environment=?',name,environment).first();if(row){if(!row.enabled)return null;return {...JSON.parse(row.public_config),...JSON.parse(await decrypt(env,row.secret_config,row.id))};}if(environment!=='production')return null;const out:Record<string,string>={};for(const [field,key] of Object.entries(p.env)){if(env[key])out[field]=env[key];}if(name==='clerk'&&!out.publishable_key&&env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)out.publishable_key=env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;return p.required.every(k=>!!out[k])?out:null;}
export async function catalog(env:Env){const rows=(await q(env,'SELECT id,provider,environment,public_config,enabled,status,updated_at,last_checked_at,last_success_at FROM platform_integrations').all()).results;return Object.entries(providers).map(([id,p])=>({id,name:p.name,public_fields:p.public,secret_fields:p.secret,required_fields:p.required,configurations:['development','staging','production'].map(environment=>{const row=rows.find((r:any)=>r.provider===id&&r.environment===environment);const configured=environment==='production'&&p.required.every(k=>!!env[p.env[k]]);return row?{...row,public_config:JSON.parse(row.public_config),secrets:'configured'}:{environment,enabled:configured,status:configured?'environment_configured':'not_configured',public_config:{},secrets:configured?'configured':'not_configured'};})}));}
export async function save(env:Env,a:any,name:string,data:any,rid:string){const p=provider(name),id=name+':'+data.environment;const old=await q(env,'SELECT * FROM platform_integrations WHERE id=?',id).first();const pub:any=old?JSON.parse(old.public_config):{},secret:any=old?.secret_config?JSON.parse(await decrypt(env,old.secret_config,id)):{};
 for(const [key,value]of Object.entries(data.public_config||{})){if(!p.public.includes(key)||typeof value!=='string'||value.length>2048)throw new ApiError(400,'INVALID_CONFIG','Check public configuration fields.');pub[key]=value;}
 for(const [key,value]of Object.entries(data.secret_config||{})){if(!p.secret.includes(key)||typeof value!=='string'||value.length>20000||!value.trim())throw new ApiError(400,'INVALID_CONFIG','Check secret configuration fields.');secret[key]=value;}
 if(!p.required.every(k=>!!(pub[k]||secret[k])))throw new ApiError(400,'CONFIG_INCOMPLETE','Complete all required credentials.');
 if(name==='cloudinary'&&!/^[a-zA-Z0-9_-]+$/.test(pub.cloud_name))throw new ApiError(400,'INVALID_CONFIG','Enter a valid cloud name.');
 if(name==='media_worker'&&!/^[0-9a-fA-F]{64}$/.test(secret.worker_key))throw new ApiError(400,'INVALID_CONFIG','Use a random 64-character hexadecimal worker credential.');
 if(name==='fcm'){let service:any;try{service=JSON.parse(secret.service_account_json);}catch{throw new ApiError(400,'INVALID_CONFIG','Enter valid service account JSON.');}if(service.type!=='service_account'||service.project_id!==pub.project_id||!service.client_email||!service.private_key)throw new ApiError(400,'INVALID_CONFIG','The service account must match the project.');}
 const cipher=await encrypt(env,JSON.stringify(secret),id),now=Date.now();
 await env.DB.batch([q(env,"INSERT INTO platform_integrations(id,provider,environment,public_config,secret_config,enabled,status,updated_at) VALUES(?,?,?,?,?,1,'unverified',?) ON CONFLICT(id) DO UPDATE SET public_config=excluded.public_config,secret_config=excluded.secret_config,enabled=1,status='unverified',updated_at=excluded.updated_at",id,name,data.environment,JSON.stringify(pub),cipher,now),audit(env,a.id,'integration.saved',id,rid)]);
 return {id,status:'unverified',secrets:'configured'};
}
export async function connectionTest(env:Env,a:any,name:string,environment:string,rid:string){const c=await credentials(env,name,environment);if(!c)throw new ApiError(409,'NOT_CONFIGURED','Configure this integration first.');let url='',headers:Record<string,string>={};
 if(name==='resend'){url='https://api.resend.com/domains';headers.authorization='Bearer '+c.api_key;}
 if(name==='stripe'){url='https://api.stripe.com/v1/balance';headers.authorization='Bearer '+c.secret_key;}
 if(name==='clerk'){url='https://api.clerk.com/v1/users?limit=1';headers.authorization='Bearer '+c.secret_key;}
 if(name==='cloudinary'){if(!/^[a-zA-Z0-9_-]+$/.test(c.cloud_name))throw new ApiError(400,'INVALID_CONFIG','Invalid cloud name.');url='https://api.cloudinary.com/v1_1/'+c.cloud_name+'/ping';headers.authorization='Basic '+btoa(c.api_key+':'+c.api_secret);}
 if(name==='github'){url='https://api.github.com/user';headers={authorization:'Bearer '+c.api_token,'user-agent':'Blindbandit-Control-Center',accept:'application/vnd.github+json'};}
 if(name==='cloudflare'){url='https://api.cloudflare.com/client/v4/user/tokens/verify';headers.authorization='Bearer '+c.api_token;}
 if(name==='media_worker')return {status:'worker_check_required',message:'Run the media processor with this credential, then check the job service status.'};
 if(!url)return {status:'delivery_test_required',message:'Use Push Test with your registered device to verify delivery. Web Push delivery is not enabled in this release.'};
 let ok=false;try{const response=await fetch(url,{headers,redirect:'error',signal:AbortSignal.timeout(12000)});ok=response.ok;if(name==='cloudflare'&&ok){const result:any=await response.json();ok=result.success===true&&result.result?.status==='active';}else await response.body?.cancel();}catch{}
 const now=Date.now();await env.DB.batch([q(env,'UPDATE platform_integrations SET status=?,last_checked_at=?,last_success_at=CASE WHEN ?=1 THEN ? ELSE last_success_at END WHERE provider=? AND environment=?',ok?'connected':'error',now,ok?1:0,now,name,environment),audit(env,a.id,'integration.tested',name+':'+environment,rid,ok?'success':'failure')]);
 return {status:ok?'connected':'error',message:ok?'Connection successful.':'Connection failed. Check credentials and provider permissions.',checked_at:now};
}
