import {q,response,id,hash,audit,sendMail} from './editorial-common';
import {verified} from './security';
export async function accountAdmin(request:Request,env:any,a:any,d:any){if(!['owner','admin'].includes(a.role))return response({error:'Administrator access required.'},403);const kind=new URL(request.url).pathname.split('/').pop();if(request.method!=='GET'&&!await verified(request,env,a,true))return response({error:'Verify your identity to continue.',verificationRequired:true},403);
 if(kind==='sessions'){
 if(request.method==='GET'){const rows=await q(env,'SELECT s.id,s.user_id,s.user_agent,s.ip_address,s.created_at,s.expires_at,u.name,u.email FROM label_session s JOIN label_user u ON u.id=s.user_id WHERE s.expires_at>? AND (?=\'owner\' OR s.user_id=?) ORDER BY s.created_at DESC LIMIT 200',Date.now(),a.role,a.id).all();return response({sessions:rows.results.map((r:any)=>({...r,current:r.id===a.sessionKey})),scope:a.role==='owner'?'All account sessions (up to 200)':'Your sessions'});}
 if(request.method==='POST'){const s=await q(env,'SELECT id,user_id FROM label_session WHERE id=?',d.id).first();if(!s||a.role!=='owner'&&s.user_id!==a.id)return response({error:'Session unavailable.'},404);if(s.id===a.sessionKey)return response({error:'Use Sign out for your current session.'},400);await env.DB.batch([q(env,'DELETE FROM label_session WHERE id=?',s.id),q(env,'DELETE FROM security_proofs WHERE session_key=?',s.id),audit(env,a.id,'security.account_session_revoked',s.user_id)]);return response({ok:true});}
 }
 if(kind==='community-accounts'){
 if(request.method==='GET'){const rows=await q(env,"SELECT key,value FROM label_settings WHERE key LIKE 'community_invite:%' LIMIT 200").all();return response({accounts:rows.results.map((r:any)=>({...JSON.parse(r.value),key:r.key}))});}
 if(request.method==='POST'){
 const email=String(d.email||'').trim().toLowerCase(),name=String(d.name||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||!name||name.length>40)return response({error:'Enter a valid email and display name of up to 40 characters.'},400);
 if((await q(env,"SELECT COUNT(*) AS n FROM label_settings WHERE key LIKE 'community_invite:%'").first()).n>=200)return response({error:'This invitation directory supports 200 accounts.'},400);
 const key='community_invite:'+await hash(email);if(await q(env,'SELECT key FROM label_settings WHERE key=?',key).first())return response({error:'This community invitation already exists.'},409);
 const record={email,name,status:'invited',createdAt:Date.now(),userId:null};await q(env,'INSERT INTO label_settings(key,value) VALUES(?,?)',key,JSON.stringify(record)).run();const delivery=await sendMail(env,key,'community_invitation',email,'Your Mr. Blindbandit community invitation',['Hello '+name+',','You have been invited to join the public Mr. Blindbandit fan community. Sign in with a ChatGPT account using '+email+' to claim this profile.','Community posts and your chosen display name are public. This invitation does not grant access to private label dashboards or financial records.'],'https://mrblindbandit.net/community/account/','Open your community account');await audit(env,a.id,'community.account_invited',key).run();return response({ok:true,delivery},201);
 }
 if(request.method==='PATCH'){if(!['active','suspended'].includes(d.status)||typeof d.key!=='string'||!d.key.startsWith('community_invite:'))return response({error:'Invalid account change.'},400);const row=await q(env,'SELECT value FROM label_settings WHERE key=?',d.key).first();if(!row)return response({error:'Account not found.'},404);const record=JSON.parse(row.value);record.status=d.status;await env.DB.batch([q(env,'UPDATE label_settings SET value=? WHERE key=?',JSON.stringify(record),d.key),audit(env,a.id,'community.account_'+d.status,d.key)]);return response({ok:true});}
 }
 return response({error:'Method not allowed.'},405);
}
export async function invitedCommunity(request:Request,env:any,user:any){if(!user)return user;const email=(user.email||request.headers.get('oai-authenticated-user-email')||'').toLowerCase(),key='community_invite:'+await hash(email),row=await q(env,'SELECT value FROM label_settings WHERE key=?',key).first();if(!row)return user;const r=JSON.parse(row.value);if(r.status==='suspended'&&!user.moderator)return null;if(!r.userId){r.userId=user.id;r.status='active';await env.DB.batch([q(env,'INSERT INTO community_profiles(user_id,display_name,created_at) VALUES(?,?,?) ON CONFLICT(user_id) DO NOTHING',user.id,r.name,Date.now()),q(env,'UPDATE label_settings SET value=? WHERE key=? AND value=?',JSON.stringify(r),key,row.value)]);}return user;}
