import {q,response,id,audit} from './editorial-common';
export async function editorialActions(request:Request,env:any,a:any,d:any,key:string){
 if(key==='duplicate'&&request.method==='POST'){const r=await q(env,'SELECT * FROM site_articles WHERE id=?',d.id).first();if(!r)return response({error:'Article not found.'},404);const newid=id(),now=Date.now(),meta=JSON.parse(r.metadata||'{}');meta.canonical='';meta.featured=false;meta.lastEditor=a.name;meta.privateNotes='';await env.DB.batch([q(env,'INSERT INTO site_articles(id,slug,title,body,excerpt,author,category,tags,status,publish_at,metadata,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',newid,r.slug.slice(0,90)+'-copy-'+newid.slice(0,8),(r.title+' — copy').slice(0,160),r.body,r.excerpt,r.author,r.category,r.tags,'draft',null,JSON.stringify(meta),1,now,now),audit(env,a.id,'article.duplicated',newid)]);return response({id:newid},201);}
 if(key==='bulk'&&request.method==='POST'){
 if(!Array.isArray(d.records)||!d.records.length||d.records.length>20||d.records.some((r:any)=>typeof r.id!=='string'||!Number.isInteger(r.revision))||new Set(d.records.map((r:any)=>r.id)).size!==d.records.length)return response({error:'Select 1–20 distinct articles.'},400);
 if(!['draft','archived','taxonomy'].includes(d.action)||d.confirm!=='UPDATE SELECTED')return response({error:'Choose an action and type UPDATE SELECTED.'},400);
 if(d.action==='taxonomy'&&(typeof d.category!=='string'||!d.category.trim()||d.category.length>80||typeof d.tags!=='string'||d.tags.length>300))return response({error:'Enter a category and up to 300 characters of tags.'},400);
 const ids=d.records.map((r:any)=>r.id),placeholders=ids.map(()=>'?').join(','),matches=d.records.map(()=>'(id=? AND revision=?)').join(' OR '),values=d.records.flatMap((r:any)=>[r.id,r.revision]);
 const old=(await q(env,'SELECT * FROM site_articles WHERE id IN ('+placeholders+')',...ids).all()).results;
 const set=d.action==='taxonomy'?'category=?,tags=?':'status=?',args=d.action==='taxonomy'?[d.category.trim(),d.tags.trim()]:[d.action],now=Date.now();
 const changed=(await q(env,'UPDATE site_articles SET '+set+",metadata=json_set(metadata,'$.lastEditor',?),updated_at=?,revision=revision+1 WHERE status<>'trash' AND id IN ("+placeholders+") AND (SELECT COUNT(*) FROM site_articles WHERE status<>'trash' AND ("+matches+'))=? RETURNING id',...args,a.name,now,...ids,...values,ids.length).all()).results;
 if(changed.length!==ids.length)return response({error:'A selected article changed or is in Trash. Reload before updating.'},409);
 await env.DB.batch([...old.map((r:any)=>q(env,'INSERT INTO article_revisions(id,article_id,snapshot,actor_id,created_at) VALUES(?,?,?,?,?)',id(),r.id,JSON.stringify(r),a.id,now)),audit(env,a.id,'article.bulk_'+d.action,ids.join(','))]);return response({updated:changed.length});
 }
 if(key==='export'&&request.method==='GET'){const rows=(await q(env,'SELECT slug,title,author,category,tags,status,publish_at,updated_at FROM site_articles ORDER BY updated_at DESC LIMIT 1001').all()).results;if(rows.length>1000)return response({error:'Export supports up to 1,000 articles.'},400);const columns=['slug','title','author','category','tags','status','publish_at','updated_at'];const cell=(v:any)=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replaceAll('"','""')+'"';return new Response([columns,...rows.map((r:any)=>columns.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n'),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="blindbandit-article-metadata.csv"','cache-control':'private, no-store','x-robots-tag':'noindex'}});}
 return null;
}
