export const esc=(x:any)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const hash=async(x:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(x))),b=>b.toString(16).padStart(2,'0')).join('');
export const q=(env:any,sql:string,...args:any[])=>env.DB.prepare(sql).bind(...args);
export const id=()=>crypto.randomUUID();
export const response=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','cache-control':'private, no-store','x-content-type-options':'nosniff'}});
export const audit=(env:any,a:string,action:string,target:string)=>q(env,'INSERT INTO label_audit (id,actor_id,action,target_id,created_at) VALUES (?,?,?,?,?)',id(),a,action,target,Date.now());
export function str(x:any,max=200,required=true){if(typeof x!=='string'||x.trim().length>max||(required&&!x.trim()))throw Error('Complete the fields within their length limits.');return x.trim();}
export function safeURL(x:any){const u=new URL(str(x,2000));if(u.protocol!=='https:'||u.username||u.password)throw Error('Use an HTTPS URL without credentials.');return u.href;}
export async function sendMail(env:any,thread:string,kind:string,to:string,title:string,paragraphs:string[],link='https://mrblindbandit.net/contact/',action='Contact the label',mailId=id(),replyTo='business@mrblindbandit.net'){
 const year=new Date().getUTCFullYear();const signature='Blindbandit Records · On behalf of Kaeleb Savon Heck / Mr. Blindbandit\nbusiness@mrblindbandit.net\nPurok 6-A, Mabuhay, Barangay Capungagan, Davao del Norte 8113, Philippines\n+63 962 695 4905 · +1 540 926 9791';
 const legal='Confidentiality: Intended for the named recipient. If received in error, notify the sender and delete it. Do not share private account links. This notice does not create legal privilege.\nLegal: Receipt of a message does not create a recording, licensing, employment or payment agreement, or transfer rights. Separate authorized agreements are required.';
 const footer='Privacy: https://mrblindbandit.net/privacy/\nAccessibility: https://mrblindbandit.net/accessibility/\nContact: https://mrblindbandit.net/contact/\n© '+year+' Blindbandit Records. All rights reserved.';
 const text=title+'\n\n'+paragraphs.join('\n\n')+'\n\n'+action+': '+link+'\n\n'+signature+'\n\n'+legal+'\n\n'+footer;
 const html='<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#111310;color:#f4f5ed;font:16px/1.7 Arial,sans-serif"><table role="presentation" width="100%"><tr><td align="center" style="padding:20px"><table role="presentation" width="100%" style="max-width:640px;background:#1b1f17;border-top:5px solid #ddfa67"><tr><td style="padding:32px;color:#f4f5ed"><a href="https://mrblindbandit.net/" style="display:block;margin-bottom:24px"><img src="https://mrblindbandit.net/assets/blindbandit-records-gold.jpeg" width="360" alt="Mr. Blindbandit — Blindbandit Records" style="display:block;width:100%;max-width:360px;height:auto;border:0;background:#111b16"></a><p style="color:#ddfa67;font-weight:bold;font-size:24px">MR. BLINDBANDIT.</p><h1 style="font-size:26px">'+esc(title)+'</h1>'+paragraphs.map(p=>'<p style="color:#e2e8dc">'+esc(p).replaceAll('\n','<br>')+'</p>').join('')+'<p style="color:#e2e8dc"><a style="display:inline-block;padding:14px 20px;background:#ddfa67;color:#111310" href="'+esc(link)+'">'+esc(action)+'</a></p><p style="color:#e2e8dc">'+esc(signature).replaceAll('\n','<br>')+'</p><hr><p style="font-size:13px">'+esc(legal).replaceAll('\n','<br>')+'</p><p style="color:#e2e8dc"><a style="color:#ddfa67" href="https://mrblindbandit.net/privacy/">Privacy</a> · <a style="color:#ddfa67" href="https://mrblindbandit.net/accessibility/">Accessibility</a> · <a style="color:#ddfa67" href="https://mrblindbandit.net/contact/">Contact</a></p><p style="color:#e2e8dc">© '+year+' Blindbandit Records. All rights reserved.</p><p style="color:#e2e8dc"><a style="color:#ddfa67" href="mailto:business@mrblindbandit.net">Email the label</a> · <a style="color:#ddfa67" href="tel:+639626954905">Philippines: +63 962 695 4905</a> · <a style="color:#ddfa67" href="tel:+15409269791">US: +1 540 926 9791</a><br><a style="color:#ddfa67" href="https://www.google.com/maps/search/?api=1&amp;query=Purok%206-A%20Mabuhay%20Capungagan%20Davao%20del%20Norte%20Philippines">View the public business area on a map</a></p></td></tr></table></td></tr></table></body></html>';
 await q(env,'INSERT INTO site_mail (id,thread_id,kind,recipient,status,created_at) VALUES (?,?,?,?,?,?)',mailId,thread,kind,to,'pending',Date.now()).run();
 try{if(!env.RESEND_API_KEY)throw Error('Email sender is not configured.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+env.RESEND_API_KEY,'content-type':'application/json','idempotency-key':mailId},body:JSON.stringify({from:env.PORTAL_EMAIL_FROM||'Blindbandit Records <accounts@mrblindbandit.com>',to:[to],reply_to:replyTo,subject:title,html,text}),signal:AbortSignal.timeout(15000)});const d:any=await r.json();if(!r.ok||!d.id)throw Error('Email was not accepted.');await q(env,"UPDATE site_mail SET status='accepted',provider_id=? WHERE id=?",d.id,mailId).run();return 'accepted';}catch{await q(env,"UPDATE site_mail SET status='failed' WHERE id=?",mailId).run();return 'failed';}
}
export async function submissionNotices(env:any,r:any){const details=JSON.parse(r.details),category=details.category||r.kind,department=['bookings','licensing','sponsorships','partnerships','press','copyright','privacy','accessibility','support','security','legal','submissions','business','info','webmaster'].includes(category)?category:'business';await sendMail(env,r.id,'sender_receipt',r.email,'We received your '+category+' · '+r.id.slice(0,8),['Hello '+(r.name||'there')+',','Your message has been saved by Blindbandit Records. Reference: '+r.id,'Category: '+category+'\nReceived: '+new Date(r.created_at).toISOString(),'This receipt confirms submission, not acceptance of a demo or a business agreement. We review messages as capacity permits. Please keep your reference if you contact us.'],'https://mrblindbandit.net/contact/','Contact '+department,undefined,department+'@mrblindbandit.net');const setting=await q(env,"SELECT value FROM label_settings WHERE key='notification_email'").first();const to=setting?.value||env.COMMUNITY_MODERATOR_EMAIL;if(to)await sendMail(env,r.id,'owner_notice',to,'New '+category+' · '+r.id.slice(0,8),['A website message is ready for review.','From: '+r.name+' <'+r.email+'>\nReference: '+r.id+'\nCategory: '+category+'\nReceived: '+new Date(r.created_at).toISOString()+'\nSource: '+(details.source||'Website form'),String(details.message||details.title||details.interests||'').slice(0,600)],'https://mrblindbandit.net/portal/inbox/?thread='+r.id,'Open private submission');}
