import {q,id,response,str,audit,sendMail} from './editorial-common';
const states=['new','open','waiting_on_sender','replied','closed','qualified','proposal','negotiation','won','lost','archived','spam','trash'];
export async function inbox(request:Request,env:any,a:any,d:any){const u=new URL(request.url),parts=u.pathname.split('/').filter(Boolean),key=parts[3],action=parts[4];if(!['owner','admin'].includes(a.role))return response({error:'Administrator access required.'},403);
 try{
 if(!key&&request.method==='GET'){const page=Math.max(0,Math.min(10000,Number(u.searchParams.get('page'))||0)),search=(u.searchParams.get('q')||'').slice(0,200),status=u.searchParams.get('status')||'',department=u.searchParams.get('department')||'';const where=" WHERE (?='' OR r.name LIKE ? OR r.email LIKE ? OR r.details LIKE ? OR t.tags LIKE ?) AND (?='' OR COALESCE(t.status,'new')=?) AND (?='' OR t.department=?)";const args=[search,...Array(4).fill('%'+search+'%'),status,status,department,department];const rows=await q(env,"SELECT r.*,COALESCE(t.status,'new') AS status,COALESCE(t.unread,1) AS unread,t.starred,t.priority,t.department FROM site_requests r LEFT JOIN inbox_threads t ON t.id=r.id"+where+' ORDER BY r.created_at DESC LIMIT 25 OFFSET ?',...args,page*25).all();const count=await q(env,'SELECT COUNT(*) AS total FROM site_requests r LEFT JOIN inbox_threads t ON t.id=r.id'+where,...args).first();return response({requests:rows.results,total:count.total,page});}
 if(key==='bulk'&&request.method==='POST'){if(!Array.isArray(d.ids)||d.ids.length>25||!states.includes(d.status))throw Error('Select up to 25 messages and a valid status.');await env.DB.batch(d.ids.map((x:any)=>q(env,'INSERT INTO inbox_threads (id,status,updated_at) SELECT id,?,? FROM site_requests WHERE id=? ON CONFLICT(id) DO UPDATE SET status=excluded.status,updated_at=excluded.updated_at',d.status,Date.now(),str(x,100))));await audit(env,a.id,'inbox.bulk:'+d.status,d.ids.join(',')).run();return response({ok:true});}
 const r=key&&await q(env,'SELECT * FROM site_requests WHERE id=?',key).first();if(!r)return response({error:'Message not found.'},404);
 await q(env,'INSERT INTO inbox_threads (id,department,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING',key,JSON.parse(r.details).category||r.kind,Date.now()).run();
 if(action==='file'&&request.method==='GET'){const file=r.storage_key&&await env.BUCKET.get(r.storage_key);if(!file)return response({error:'File not found.'},404);await audit(env,a.id,'inbox.attachment_download',key).run();return new Response(file.body,{headers:{'content-type':'application/octet-stream','content-disposition':'attachment; filename="'+String(r.file_name).replace(/[^a-zA-Z0-9._-]/g,'_')+'"','cache-control':'private, no-store','x-content-type-options':'nosniff'}});}
 if(!action&&request.method==='GET'){const [t,m,mail]=await Promise.all([q(env,'SELECT * FROM inbox_threads WHERE id=?',key).first(),q(env,'SELECT m.*,u.name AS actor_name FROM inbox_messages m LEFT JOIN label_user u ON u.id=m.actor_id WHERE thread_id=? ORDER BY m.created_at',key).all(),q(env,'SELECT kind,recipient,status,created_at FROM site_mail WHERE thread_id=? ORDER BY created_at',key).all()]);return response({request:r,thread:t,messages:m.results,mail:mail.results});}
 if(!action&&request.method==='PATCH'){if(!states.includes(d.status)||!['low','normal','high','urgent'].includes(d.priority))throw Error('Select valid status and priority.');const assignee=str(d.assignee||'',100,false);if(assignee&&!await q(env,"SELECT id FROM label_members WHERE id=? AND role IN ('owner','admin') AND status='active'",assignee).first())throw Error('Assign to an active owner or administrator.');const follow=str(d.followUp||'',10,false);if(follow&&!/^\d{4}-\d{2}-\d{2}$/.test(follow))throw Error('Use a date.');await env.DB.batch([q(env,'UPDATE inbox_threads SET status=?,priority=?,department=?,assignee=?,tags=?,starred=?,unread=?,follow_up=?,updated_at=? WHERE id=?',d.status,d.priority,str(d.department||'general',100),assignee,str(d.tags||'',300,false),d.starred?1:0,d.unread?1:0,follow,Date.now(),key),audit(env,a.id,'inbox.updated:'+d.status,key)]);return response({ok:true});}
 if(action==='message'&&request.method==='POST'){if(!['reply','note','forward'].includes(d.kind))throw Error('Choose reply, note or internal forward.');const body=str(d.body,6000);let to='';if(d.kind==='reply')to=r.email;if(d.kind==='forward'){const target=await q(env,"SELECT u.email FROM label_user u JOIN label_members m ON m.id=u.id WHERE u.id=? AND m.role IN ('owner','admin') AND m.status='active'",str(d.recipient,100)).first();if(!target)throw Error('Choose an active owner or administrator.');to=target.email;}const messageId=id();await q(env,'INSERT INTO inbox_messages (id,thread_id,actor_id,kind,body,recipient,delivery,created_at) VALUES (?,?,?,?,?,?,?,?)',messageId,key,a.id,d.kind,body,to,to?'pending':'internal',Date.now()).run();let delivery='internal';if(to){delivery=await sendMail(env,key,d.kind,to,(d.kind==='reply'?'Re: Your message':'Internal submission forward')+' · '+key.slice(0,8),[body,'Reference: '+key],d.kind==='reply'?'https://mrblindbandit.net/contact/':'https://mrblindbandit.net/portal/inbox/?thread='+key,d.kind==='reply'?'Contact the label':'Open private thread');await q(env,'UPDATE inbox_messages SET delivery=? WHERE id=?',delivery,messageId).run();}await env.DB.batch([q(env,"UPDATE inbox_threads SET status=CASE WHEN ?='reply' AND ?='accepted' THEN 'replied' ELSE status END,updated_at=? WHERE id=?",d.kind,delivery,Date.now(),key),audit(env,a.id,'inbox.'+d.kind+':'+delivery,key)]);return response({ok:true,delivery});}
 if(!action&&request.method==='DELETE'){const t=await q(env,'SELECT status FROM inbox_threads WHERE id=?',key).first();if(t.status!=='trash'||d.confirm!==key)throw Error('Move to trash first, then confirm the full reference to delete permanently.');await env.DB.batch([q(env,'DELETE FROM inbox_messages WHERE thread_id=?',key),q(env,'DELETE FROM site_mail WHERE thread_id=?',key),q(env,'DELETE FROM inbox_threads WHERE id=?',key),q(env,'DELETE FROM site_requests WHERE id=?',key),audit(env,a.id,'inbox.permanently_deleted',key)]);if(r.storage_key)await env.BUCKET.delete(r.storage_key);return response({ok:true});}
 return response({error:'Action not available.'},405);
 }catch(e){return response({error:e instanceof Error?e.message:'Inbox action failed.'},400);}}
