import searchConsoleSnapshot from '../data/search-console-snapshot.json';
import {editorialActions} from './editorial-actions';
import {writingAssist} from './writing-assist';
import {articleMetadata,articleChecks,articleBody} from './article-tools';
import {translations,translationPath} from './translations';
import {q,id,response,str,esc,safeURL,audit} from './editorial-common';
import {sitePages} from './site-pages';
const origin='https://mrblindbandit.net';
export const publicRoutes=()=>Object.keys(sitePages).filter(p=>!/^\/(portal|owner)(\/|$)|^\/community\/(account|dashboard|moderation)\//.test(p));
export function articleHTML(r:any,preview=false,related:any[]=[],neighbors:any[]=[]){const meta=JSON.parse(r.metadata||'{}'),path='/journal/articles/'+r.slug+'/';const body=articleBody(r.body);let html=sitePages['/journal/']||sitePages['/'];html=html.replace(/<main\b[^>]*id="main"[^>]*>[\s\S]*?<\/main>/,'<main id="main" tabindex="-1"><article class="shell policy-body"><p class="eyebrow">'+esc(r.category)+'</p><h1>'+esc(r.title)+'</h1><p>'+esc(r.excerpt)+'</p><p>By '+esc(r.author)+' · '+new Date(r.publish_at||r.updated_at).toISOString().slice(0,10)+'</p>'+(preview?'<p role="status">Private preview — this version may not be public.</p>':'')+(meta.image?'<figure><img src="'+esc(meta.image)+'" alt="'+esc(meta.imageAlt)+'" style="max-width:100%;height:auto" decoding="async">'+(meta.imageCaption?'<figcaption>'+esc(meta.imageCaption)+'</figcaption>':'')+'</figure>':'')+body+(meta.authorBio?'<aside class="author-profile"><h2>About '+esc(r.author)+'</h2><p>'+esc(meta.authorBio)+'</p></aside>':'')+(neighbors.length?'<nav aria-label="Article navigation">'+neighbors.map((n:any)=>'<p><a href="/journal/articles/'+esc(n.slug)+'/">'+esc(n.label)+': '+esc(n.title)+'</a></p>').join('')+'</nav>':'')+(related.length?'<nav aria-label="Related reading"><h2>Related reading</h2><ul>'+related.map((x:any)=>'<li><a href="'+esc(x.path)+'">'+esc(x.title)+'</a></li>').join('')+'</ul></nav>':'')+'<p><a href="/news/">More news</a> · <a href="/biography/">About the artist</a></p></article></main>');html=html.replace(/<script[^>]*type="application\/ld\+json"[^>]*>[\s\S]*?<\/script>/g,'');html=applyMetadata(html,path,{...meta,title:meta.title||r.title,description:meta.description||r.excerpt,noindex:preview||meta.noindex});const schema={'@context':'https://schema.org','@type':'Article',headline:r.title,...(meta.image?{image:[meta.image]}:{}),description:r.excerpt,author:{'@type':'Person',name:r.author},datePublished:new Date(r.publish_at||r.created_at).toISOString(),dateModified:new Date(r.updated_at).toISOString(),mainEntityOfPage:origin+path};return html.replace('</head>','<script type="application/ld+json">'+JSON.stringify(schema).replaceAll('<','\\u003c')+'</script></head>');}
export function applyMetadata(html:string,path:string,m:any){const title=m.title||(/<title>(.*?)<\/title>/.exec(html)?.[1]||'Mr. Blindbandit'),description=m.description||(/<meta name="description" content="([^"]*)"/.exec(html)?.[1]||'');html=html.replace(/<title>[\s\S]*?<\/title>/,'<title>'+esc(title)+'</title>').replace(/<link rel="canonical"[^>]*>|<meta (?:name="(?:description|robots|twitter:title|twitter:description)"|property="og:(?:title|description|url)")[^>]*>/g,'');if(m.socialImage||m.image)html=html.replace(/<meta (?:property="og:image(?:[^"]*)"|name="twitter:(?:image|card)")[^>]*>/g,'').replace('</head>','<meta property="og:image" content="'+esc(m.socialImage||m.image)+'"><meta name="twitter:image" content="'+esc(m.socialImage||m.image)+'"><meta name="twitter:card" content="summary_large_image"></head>');return html.replace('</head>','<meta name="description" content="'+esc(description)+'"><meta name="robots" content="'+(m.noindex?'noindex,nofollow':'index,follow,max-image-preview:large')+'"><link rel="canonical" href="'+esc(m.canonical||origin+path)+'"><meta property="og:title" content="'+esc(title)+'"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+esc(m.canonical||origin+path)+'"><meta name="twitter:title" content="'+esc(title)+'"><meta name="twitter:description" content="'+esc(description)+'"></head>');}
const metadata=articleMetadata;
export async function editorialAPI(request:Request,env:any,a:any,d:any){if(!['owner','admin'].includes(a.role))return response({error:'Administrator access required.'},403);const u=new URL(request.url),section=u.pathname.split('/')[3],key=u.pathname.split('/')[4];try{
 if(section==='publishing'){
 if(['duplicate','bulk','export'].includes(key)){const action=await editorialActions(request,env,a,d,key);if(action)return action;}
 if(key==='suggest'&&request.method==='POST')return writingAssist(env,d);
 if(key==='check'&&request.method==='POST'){
 const checks=articleChecks(d);const duplicate=await q(env,"SELECT id FROM site_articles WHERE lower(title)=lower(?) AND id<>? AND status<>'trash' LIMIT 1",String(d.title||''),String(d.id||'')).first();if(duplicate)checks.warnings.push('Another article already uses this title. Consider a distinct title.');
 const paths=[...new Set(Array.from(String(d.body||'').matchAll(/\[[^\]]+\]\((\/[^\s)]*)\)/g)).map(m=>m[1].split(/[?#]/)[0]))].slice(0,30);
 for(const path of paths){if(!publicRoutes().includes(path)&&!await q(env,"SELECT id FROM site_articles WHERE slug=? AND status IN ('published','scheduled') AND publish_at<=?",path.match(/^\/journal\/articles\/([a-z0-9-]+)\/$/)?.[1]||'',Date.now()).first())checks.warnings.push('Internal link is not an available public page: '+path);}
 return response({...checks,renderedBody:articleBody(String(d.body||'')),schema:{'@context':'https://schema.org','@type':'Article',headline:d.title,description:d.excerpt,author:{'@type':'Person',name:d.author},mainEntityOfPage:origin+'/journal/articles/'+d.slug+'/'}});
 }
 if(!key&&request.method==='GET'){
 const search=(u.searchParams.get('q')||'').slice(0,200),status=u.searchParams.get('status')||'',offset=Math.max(0,Math.min(100000,Number(u.searchParams.get('offset'))||0));
 const category=(u.searchParams.get('category')||'').slice(0,80),author=(u.searchParams.get('author')||'').slice(0,120),tag=(u.searchParams.get('tag')||'').slice(0,100),after=u.searchParams.get('after')||'',before=u.searchParams.get('before')||'';if([after,before].some(v=>v&&!/^\d{4}-\d{2}-\d{2}$/.test(v)))throw Error('Use YYYY-MM-DD filter dates.');const where=" WHERE (?='' OR instr(lower(title||' '||excerpt||' '||author||' '||category||' '||tags),lower(?))>0) AND (?='' OR status=?) AND (?='' OR category=?) AND (?='' OR author=?) AND (?='' OR instr(lower(tags),lower(?))>0) AND (?='' OR updated_at>=?) AND (?='' OR updated_at<?)",args=[search,search,status,status,category,category,author,author,tag,tag,after,after?Date.parse(after):0,before,before?Date.parse(before)+86400000:0];
 return response({articles:(await q(env,'SELECT id,slug,title,excerpt,author,category,status,publish_at,revision,updated_at,json_extract(metadata,\'$.lastEditor\') AS last_editor FROM site_articles'+where+' ORDER BY updated_at DESC,id LIMIT 50 OFFSET ?',...args,offset).all()).results,total:(await q(env,'SELECT COUNT(*) AS total FROM site_articles'+where,...args).first()).total,offset});}

 if(key&&request.method==='GET'){const r=await q(env,'SELECT * FROM site_articles WHERE id=?',key).first();if(!r)return response({error:'Article not found.'},404);return response({article:r,revisions:(await q(env,'SELECT id,snapshot,created_at FROM article_revisions WHERE article_id=? ORDER BY created_at DESC LIMIT 30',key).all()).results});}
 if(request.method==='DELETE'){const r=await q(env,'SELECT * FROM site_articles WHERE id=?',key).first();if(!r||r.status!=='trash'||d.confirm!==r.slug)throw Error('Move to trash, then confirm the slug to delete.');await env.DB.batch([q(env,'DELETE FROM site_articles WHERE id=?',key),q(env,'DELETE FROM article_revisions WHERE article_id=?',key),audit(env,a.id,'article.deleted',key)]);return response({ok:true});}
 if(['POST','PATCH'].includes(request.method)){const old=key?await q(env,'SELECT * FROM site_articles WHERE id=?',key).first():null;if(key&&!old)throw Error('Article not found.');if(old&&old.revision!==d.revision)return response({error:'This article changed. Reload before saving.'},409);const slug=str(d.slug,120);const reserved=await q(env,'SELECT value FROM label_settings WHERE key=?','article-alias:'+slug).first();if(reserved&&JSON.parse(reserved.value).articleId!==key)throw Error('This URL is reserved by a previous article address.');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw Error('Use lowercase words separated by hyphens in the URL slug.');if(!['draft','published','scheduled','archived','trash'].includes(d.status))throw Error('Choose a valid publication status.');if(['published','scheduled'].includes(d.status)&&!d.previewConfirmed)throw Error('Preview and confirm this version before publication.');const publishAt=d.publishAt?Date.parse(d.publishAt):Date.now();if(!Number.isFinite(publishAt))throw Error('Choose a valid publication date.');const checked=articleChecks(d);if(['published','scheduled'].includes(d.status)&&!checked.canPublish)throw Error(checked.problems.join(' '));const related=metadata(d.metadata||{}).related;for(const path of related){if(path==='/journal/articles/'+slug+'/')throw Error('Related content cannot link to this article itself.');if(!publicRoutes().includes(path)&&!await q(env,"SELECT id FROM site_articles WHERE slug=? AND status IN ('published','scheduled') AND publish_at<=?",path.match(/^\/journal\/articles\/([a-z0-9-]+)\/$/)?.[1]||'',Date.now()).first())throw Error('Related links must point to existing public pages or published articles.');}const record=key||id(),now=Date.now(),args=[slug,str(d.title,160),str(d.body,100000),str(d.excerpt,500),str(d.author,120),str(d.category,80),str(d.tags||'',300,false),d.status,publishAt,JSON.stringify({...metadata(d.metadata||{}),lastEditor:a.name}),now];if(old){const changed=await q(env,'UPDATE site_articles SET slug=?,title=?,body=?,excerpt=?,author=?,category=?,tags=?,status=?,publish_at=?,metadata=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=? RETURNING id',...args,record,d.revision).first();if(!changed)return response({error:'Article changed. Reload before saving.'},409);await q(env,'INSERT INTO article_revisions (id,article_id,snapshot,actor_id,created_at) VALUES (?,?,?,?,?)',id(),record,JSON.stringify(old),a.id,now).run();}else await q(env,'INSERT INTO site_articles (slug,title,body,excerpt,author,category,tags,status,publish_at,metadata,updated_at,id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',...args,record,now).run();if(old&&old.slug!==slug)await q(env,'INSERT INTO label_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value','article-alias:'+old.slug,JSON.stringify({articleId:record})).run();await audit(env,a.id,'article.saved:'+d.status,record).run();return response({id:record});}
 }
 if(section==='seo'&&request.method==='GET'){const overrides=(await q(env,'SELECT * FROM seo_overrides').all()).results;const published=(await q(env,"SELECT * FROM site_articles WHERE status IN ('published','scheduled') AND publish_at<=? ORDER BY updated_at DESC LIMIT 501",Date.now()).all()).results;const articlePages=published.slice(0,500).map((r:any)=>{const m=JSON.parse(r.metadata||'{}'),path='/journal/articles/'+r.slug+'/';return {path,title:m.title||r.title,description:m.description||r.excerpt,canonical:m.canonical||origin+path,noindex:!!m.noindex,socialImage:m.socialImage||m.image||'',articleId:r.id};});const pages=publicRoutes().map(path=>{const html=sitePages[path],m=JSON.parse(overrides.find((o:any)=>o.path===path)?.settings||'{}');return {path,title:m.title||/<title>(.*?)<\/title>/.exec(html)?.[1]||'',description:m.description||/<meta name="description" content="([^"]*)"/.exec(html)?.[1]||'',canonical:m.canonical||origin+path,noindex:!!m.noindex,socialImage:m.socialImage||m.image||''};}).concat(articlePages as any);const links=publicRoutes().flatMap(path=>Array.from(sitePages[path].matchAll(/href="(\/[^"#?]*)/g)).map(m=>({from:path,to:m[1]})));for(const r of published){links.push({from:'/news/',to:'/journal/articles/'+r.slug+'/'});for(const to of JSON.parse(r.metadata||'{}').related||[])links.push({from:'/journal/articles/'+r.slug+'/',to});}const broken=links.filter(l=>l.to.endsWith('/')&&!sitePages[l.to]&&!articlePages.some((p:any)=>p.path===l.to)&&!l.to.startsWith('/portal/')).slice(0,100);return response({searchConsoleSnapshot,pages,articleLimitReached:published.length>500,duplicateDescriptions:pages.filter(p=>p.description&&pages.some(other=>other.path!==p.path&&other.description===p.description)),broken,missing:pages.filter(p=>!p.title||!p.description),duplicates:pages.filter(p=>pages.some(other=>other.path!==p.path&&other.title===p.title)),orphans:pages.filter(p=>p.path!=='/'&&!links.some(l=>l.to===p.path)),sitemap:origin+'/sitemap.xml',robots:origin+'/robots.txt',searchConsole:'https://search.google.com/search-console?resource_id=sc-domain%3Amrblindbandit.net',cmp:'Google-certified CMP activation has not been verified. Advertising remains blocked until configured.'});}
 if(section==='seo'&&request.method==='POST'){if(!publicRoutes().includes(d.path))throw Error('Choose an existing public page.');await env.DB.batch([q(env,'INSERT INTO seo_overrides (path,settings,updated_at) VALUES (?,?,?) ON CONFLICT(path) DO UPDATE SET settings=excluded.settings,updated_at=excluded.updated_at',d.path,JSON.stringify(metadata(d)),Date.now()),audit(env,a.id,'seo.updated',d.path)]);return response({ok:true});}
 if(section==='departments'&&request.method==='GET'){const r=await q(env,"SELECT value FROM label_settings WHERE key='notification_email'").first();return response({notificationEmail:r?.value||env.COMMUNITY_MODERATOR_EMAIL,sender:env.PORTAL_EMAIL_FROM||'accounts@mrblindbandit.com',contact:'business@mrblindbandit.net',aliases:['info','business','sponsorships','press','bookings','licensing','submissions','legal','privacy','accessibility','copyright','security','support','partnerships','webmaster'].map(name=>({email:name+'@mrblindbandit.net',status:'Published department contact — routing managed by owner'}))});}
 if(section==='departments'&&request.method==='POST'){const email=str(d.email,254);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid notification address.');await env.DB.batch([q(env,"INSERT INTO label_settings (key,value) VALUES ('notification_email',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",email),audit(env,a.id,'notifications.recipient_changed',a.id)]);return response({ok:true});}
 return response({error:'Endpoint not available.'},404);
 }catch(e){return response({error:e instanceof Error?e.message:'Action failed.'},400);}}
export async function editorialPublic(request:Request,env:any){const u=new URL(request.url),path=u.pathname;const normalized=path.replace(/\/index\.html$/,'/').replace(/\/$/,'')+'/';if(path!==normalized&&sitePages[normalized]&&publicRoutes().includes(normalized))return new Response(null,{status:301,headers:{location:normalized+u.search}});const headers={'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=0, must-revalidate','x-content-type-options':'nosniff'};
 if(path==='/robots.txt')return new Response(request.method==='HEAD'?null:'User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /signin-with-chatgpt\nDisallow: /signout-with-chatgpt\nDisallow: /callback\nSitemap: '+origin+'/sitemap.xml\n',{headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=300','x-content-type-options':'nosniff'}});
 if(path==='/sitemap.xml'){
  try{
   const overrides=(await q(env,'SELECT * FROM seo_overrides').all()).results;
   const articles=(await q(env,"SELECT slug,metadata,updated_at FROM site_articles WHERE status IN ('published','scheduled') AND publish_at<=?",Date.now()).all()).results;
   const settings=new Map(overrides.map((r:any)=>[r.path,r]));
   const paths=new Map<string,number|undefined>();
   for(const route of publicRoutes()){
    const row:any=settings.get(route),m=JSON.parse(row?.settings||'{}');
    const markup=sitePages[route];
    const noindex=m.noindex??/<meta\s+name="robots"\s+content="[^"]*noindex/i.test(markup);
    const canonical=m.canonical||/<link\s+rel="canonical"\s+href="([^"]*)"/i.exec(markup)?.[1]||origin+route;
    if(!noindex&&canonical===origin+route)paths.set(route,row?.updated_at);
   }
   for(const r of articles){const m=JSON.parse(r.metadata||'{}'),route='/journal/articles/'+r.slug+'/';if(!m.noindex&&(!m.canonical||m.canonical===origin+route))paths.set(route,r.updated_at);}
   for(const r of await translations(env)){if(r.status==='published')paths.set(translationPath(r),r.updatedAt);else paths.delete(translationPath(r));}
   const xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+[...paths].sort(([a],[b])=>a.localeCompare(b)).map(([path,date])=>{const valid=typeof date==='number'&&Number.isFinite(date)&&date>0&&date<=Date.now();return '  <url><loc>'+esc(origin+path)+'</loc>'+(valid?'<lastmod>'+new Date(date).toISOString()+'</lastmod>':'')+'</url>';}).join('\n')+'\n</urlset>\n';
   return new Response(request.method==='HEAD'?null:xml,{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=60','x-content-type-options':'nosniff'}});
  }catch{return new Response(request.method==='HEAD'?null:'Sitemap temporarily unavailable. Please retry.',{status:503,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'no-store','retry-after':'60'}});}
 }
 if(path.startsWith('/journal/articles/')){const requestedSlug=path.split('/')[3],alias=await q(env,'SELECT value FROM label_settings WHERE key=?','article-alias:'+requestedSlug).first();if(alias){const target=await q(env,"SELECT slug FROM site_articles WHERE id=? AND status IN ('published','scheduled') AND publish_at<=?",JSON.parse(alias.value).articleId,Date.now()).first();if(target&&target.slug!==requestedSlug)return new Response(null,{status:301,headers:{location:'/journal/articles/'+target.slug+'/', 'cache-control':'public, max-age=300'}});}const slug=path.split('/')[3],r=await q(env,"SELECT * FROM site_articles WHERE slug=? AND status IN ('published','scheduled') AND publish_at<=?",slug,Date.now()).first();const related=[];if(r)for(const dest of JSON.parse(r.metadata||'{}').related||[]){if(publicRoutes().includes(dest)){related.push({path:dest,title:/<title>(.*?)<\/title>/.exec(sitePages[dest])?.[1]||dest});}else{const target=await q(env,"SELECT title FROM site_articles WHERE slug=? AND status IN ('published','scheduled') AND publish_at<=?",dest.match(/^\/journal\/articles\/([a-z0-9-]+)\/$/)?.[1]||'',Date.now()).first();if(target)related.push({path:dest,title:target.title});}}const neighbors=[];if(r){for(const [op,order,label]of [['<','DESC','Previous'],['>','ASC','Next']]){const n=await q(env,"SELECT slug,title FROM site_articles WHERE status IN ('published','scheduled') AND publish_at<=? AND (publish_at"+op+"? OR (publish_at=? AND slug"+op+"?)) ORDER BY publish_at "+order+",slug "+order+" LIMIT 1",Date.now(),r.publish_at,r.publish_at,r.slug).first();if(n)neighbors.push({...n,label});}}return r?new Response(request.method==='HEAD'?null:articleHTML(r,false,related,neighbors),{headers}):new Response('Article not found',{status:404,headers});}
 if(path==='/news/'){const category=(u.searchParams.get('category')||'').slice(0,80),year=u.searchParams.get('year')||'';const rows=(await q(env,"SELECT * FROM site_articles WHERE status IN ('published','scheduled') AND publish_at<=? ORDER BY COALESCE(json_extract(metadata,'$.featured'),0) DESC,publish_at DESC LIMIT 100",Date.now()).all()).results;const categories=[...new Set(rows.map((r:any)=>r.category))],years=[...new Set(rows.map((r:any)=>new Date(r.publish_at).getUTCFullYear().toString()))];const filtered=rows.filter((r:any)=>(!category||r.category===category)&&(!year||new Date(r.publish_at).getUTCFullYear().toString()===year));const source=sitePages[path]||sitePages['/journal/'];const html=source.replace('</main>','<section class="shell section"><h2>Latest publications</h2><form method="get" action="/news/" class="label-form"><label>Category<select name="category"><option value="">All categories</option>'+categories.map((c:any)=>'<option '+(c===category?'selected ':'')+'value="'+esc(c)+'">'+esc(c)+'</option>').join('')+'</select></label><label>Year<select name="year"><option value="">All years</option>'+years.map((y:any)=>'<option '+(y===year?'selected ':'')+'value="'+esc(y)+'">'+esc(y)+'</option>').join('')+'</select></label><button>Filter publications</button><a href="/news/">Clear filters</a></form><p>Browse the latest 100 publications.</p>'+filtered.map((r:any)=>'<article><p>'+(JSON.parse(r.metadata||'{}').featured?'Featured · ':'')+esc(r.category)+'</p><h3><a href="/journal/articles/'+esc(r.slug)+'/">'+esc(r.title)+'</a></h3><p>'+esc(r.excerpt)+'</p></article>').join('')+(!filtered.length?'<p>No publications match these filters.</p>':'')+'</section></main>');return new Response(request.method==='HEAD'?null:html,{headers});}
 if(sitePages[path]&&publicRoutes().includes(path)){const r=await q(env,'SELECT settings FROM seo_overrides WHERE path=?',path).first();const variants=(await translations(env)).filter((t:any)=>t.status==='published'&&t.source===path);let html=r?applyMetadata(sitePages[path],path,JSON.parse(r.settings)):sitePages[path];if(variants.length){html=html.replace(/<link rel="alternate" hreflang="[^"]*"[^>]*>/g,'');html=html.replace('</head>','<link rel="alternate" hreflang="en" href="'+origin+path+'">'+variants.map((t:any)=>'<link rel="alternate" hreflang="'+t.language+'" href="'+origin+translationPath(t)+'">').join('')+'</head>');html=html.replace('</main>','<nav class="shell" aria-label="Translations of this page">'+variants.map((t:any)=>'<a href="'+translationPath(t)+'" lang="'+t.language+'">'+({es:'Español',fil:'Filipino',ceb:'Cebuano'}[t.language]||t.language)+'</a>').join(' · ')+'</nav></main>');}if(r||variants.length)return new Response(request.method==='HEAD'?null:html,{headers});}return null;}
