import {q,hash,id,response,str,audit} from './editorial-common';
export async function rememberBrowser(request:Request,env:any,a:any){const now=Date.now();await q(env,"DELETE FROM label_settings WHERE key LIKE ? AND json_extract(value,'$.expiresAt')<=?",'known-device:'+a.id+':%',now).run();const raw=request.headers.get('cookie')?.match(/(?:^|;\s*)bb_known_device=([^;]+)/)?.[1]||id()+id(),digest=await hash(raw),key='known-device:'+a.id+':'+digest,old=await q(env,'SELECT value FROM label_settings WHERE key=?',key).first(),record=old?JSON.parse(old.value):{id:digest,name:(request.headers.get('user-agent')||'Browser').slice(0,120),createdAt:now};record.lastSeen=now;record.expiresAt=now+90*86400000;await q(env,'INSERT INTO label_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,JSON.stringify(record)).run();return {cookie:'bb_known_device='+raw+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=7776000'};}
export async function knownDevices(request:Request,env:any,a:any,d:any,fresh:boolean){const prefix='known-device:'+a.id+':';
 if(request.method==='GET'){const raw=request.headers.get('cookie')?.match(/(?:^|;\s*)bb_known_device=([^;]+)/)?.[1],current=raw?await hash(raw):'';const rows=(await q(env,'SELECT value FROM label_settings WHERE key LIKE ? ORDER BY key LIMIT 100',prefix+'%').all()).results;return response({devices:rows.map((r:any)=>JSON.parse(r.value)).filter((r:any)=>r.expiresAt>Date.now()).map((r:any)=>({...r,current:r.id===current}))});}
 if(request.method!=='POST')return response({error:'Method not allowed.'},405);
 if(!fresh)return response({error:'Verify your identity to continue.',verificationRequired:true},403);
 if(!/^[a-f0-9]{64}$/.test(d.id||''))return response({error:'Device not found.'},404);const key=prefix+d.id,row=await q(env,'SELECT value FROM label_settings WHERE key=?',key).first();if(!row)return response({error:'Device not found.'},404);
 if(d.action==='forget'){await q(env,'DELETE FROM label_settings WHERE key=?',key).run();await audit(env,a.id,'security.browser_forgotten',d.id).run();return response({ok:true});}
 if(d.action==='rename'){try{const value=JSON.parse(row.value);value.name=str(d.name,120);await q(env,'UPDATE label_settings SET value=? WHERE key=?',JSON.stringify(value),key).run();return response({ok:true});}catch{return response({error:'Enter a browser name of up to 120 characters.'},400);}}
 return response({error:'Choose rename or forget.'},400);
}
