import {stripeClient} from './payments';
import {clerkIdentity} from './clerk-auth';
export const TIERS=[{amount:1,name:'Listener'},{amount:5,name:'Backstage'},{amount:10,name:'Creator'},{amount:15,name:'Insider'},{amount:20,name:'Champion'}];
const purpose='blindbandit-membership-v1';
const origin='https://mrblindbandit.net';
const json=(d:any,status=200)=>new Response(JSON.stringify(d),{status,headers:{'content-type':'application/json','cache-control':'private, no-store','x-robots-tag':'noindex, nofollow','referrer-policy':'no-referrer'}});
const q=(env:any,sql:string,...args:any[])=>env.DB.prepare(sql).bind(...args);
const read=async(env:any,key:string)=>{const r=await q(env,'SELECT value FROM label_settings WHERE key=?',key).first();return r?JSON.parse(r.value):null;};
async function write(env:any,key:string,value:any){await q(env,'INSERT INTO label_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,JSON.stringify(value)).run();}
async function rate(env:any,id:string,max=25){const window=Math.floor(Date.now()/60000);const r=await q(env,'INSERT INTO community_limits(key,window,hits) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET window=excluded.window,hits=CASE WHEN community_limits.window=excluded.window THEN community_limits.hits+1 ELSE 1 END WHERE community_limits.window<>excluded.window OR community_limits.hits<? RETURNING hits','membership:'+id,window,max).first();if(!r)throw Error('Please wait a minute before trying again.');}
export function membershipLevel(subscriptions:any[]):number{return Math.max(0,...subscriptions.filter(s=>s.status==='active'&&s.metadata?.purpose===purpose).map(s=>{const p=s.items?.data?.[0]?.price;const amount=(p?.unit_amount||0)/100;return p?.currency==='usd'&&p?.recurring?.interval==='month'&&p?.recurring?.interval_count===1&&p?.lookup_key==='bb-member-'+amount+'-monthly-v1'&&TIERS.some(t=>t.amount===amount)?amount:0;}));}
async function state(env:any,identity:any,stripe:any){const id=await read(env,'stripe-customer:'+identity.clerkUserId);if(!id)return {customer:null,level:0,subscriptions:[]};const c=await stripe.customers.retrieve(id);if(c.deleted||c.metadata?.clerk_user_id!==identity.clerkUserId)throw Error('Account mapping could not be verified.');const list=await stripe.subscriptions.list({customer:id,status:'all',limit:100});return {customer:id,level:membershipLevel(list.data),subscriptions:list.data.filter((s:any)=>s.metadata?.purpose===purpose)};}
async function price(env:any,stripe:any,amount:number){const lookup='bb-member-'+amount+'-monthly-v1';const found=await stripe.prices.list({lookup_keys:[lookup],active:true,limit:1});if(found.data[0]){const p=found.data[0];if(p.unit_amount!==amount*100||p.currency!=='usd'||p.recurring?.interval!=='month'||p.recurring?.interval_count!==1)throw Error('This membership price needs administrator review.');return p;}
 const tier=TIERS.find(t=>t.amount===amount)!;const productId='bb_member_'+amount+'_v1';try{await stripe.products.retrieve(productId);}catch(e:any){if(e.statusCode!==404)throw e;await stripe.products.create({id:productId,name:'Mr. Blindbandit '+tier.name+' Membership',metadata:{purpose,tier:String(amount)}},{idempotencyKey:productId});}
 return stripe.prices.create({product:productId,unit_amount:amount*100,currency:'usd',recurring:{interval:'month'},lookup_key:lookup,metadata:{purpose,tier:String(amount)}},{idempotencyKey:lookup});
}
async function customer(env:any,stripe:any,identity:any){let id=await read(env,'stripe-customer:'+identity.clerkUserId);if(id)return id;const c=await stripe.customers.create({email:identity.email,metadata:{clerk_user_id:identity.clerkUserId,purpose}},{idempotencyKey:'bb-customer-'+identity.clerkUserId});await write(env,'stripe-customer:'+identity.clerkUserId,c.id);return c.id;}
const starterUpdates=[{title:'Welcome to the members room',body:'Your membership supports independent music and accessible creator tools. Use the member hub to manage billing and find the features in your level. Your public fan account remains separate from private label access.'},{title:'A practical release checklist',body:'Keep a lossless master and a separate listening copy. Confirm the recording title, contributor names and artwork rights. Review your final export on more than one device before submitting it to a distributor.'}];
export async function membershipAPI(request:Request,env:any){
 const u=new URL(request.url);if(![origin,'https://www.mrblindbandit.net','https://mr-blind-bandit.mrblindbandit.chatgpt.site'].includes(u.origin))return json({error:'Use the public artist website.'},403);
 const identity=await clerkIdentity(request,env).catch(()=>null);if(!identity)return json({error:'Sign in with Clerk to use your membership.',signIn:'/sign-in?redirect_url=%2Fmembers%2F'},401);
 if(request.method!=='GET'&&request.headers.get('origin')!==u.origin)return json({error:'Submit from this website.'},403);
 try{
  await rate(env,identity.clerkUserId);const stripe=stripeClient(env),s=await state(env,identity,stripe);let d:any={};if(request.method!=='GET'){const raw=await request.text();if(raw.length>12000)return json({error:'Keep the request under 12,000 characters.'},413);try{d=JSON.parse(raw);}catch{return json({error:'Invalid request.'},400);}}
  const path=u.pathname;
  if(path==='/api/members/me'&&request.method==='GET')return json({level:s.level,name:TIERS.find(t=>t.amount===s.level)?.name||null,subscriptions:s.subscriptions.map((x:any)=>({id:x.id,status:x.status,cancelsAtPeriodEnd:x.cancel_at_period_end,periodEnd:x.items?.data?.[0]?.current_period_end})),updates:s.level?await read(env,'member-updates')||starterUpdates:[]});
  if(path==='/api/members/checkout'&&request.method==='POST'){
   const amount=Number(d.tier);if(!TIERS.some(t=>t.amount===amount)||d.agree!==true)return json({error:'Choose a membership and accept the monthly renewal terms.'},400);
   if(s.subscriptions.some((x:any)=>!['canceled','incomplete_expired'].includes(x.status)))return json({error:'You already have a membership or unfinished subscription. Manage it from your member hub before starting another.'},409);
   const pending=await read(env,'stripe-pending:'+identity.clerkUserId);if(pending?.id){const previous=await stripe.checkout.sessions.retrieve(pending.id);if(previous.status==='open')return json({url:previous.url,reused:true});}
   const account=await stripe.accounts.retrieve();if(!account.charges_enabled)return json({error:'Stripe payments are not enabled on this account yet.'},503);
   const c=await customer(env,stripe,identity),p=await price(env,stripe,amount);
   // A single deterministic hourly key per account prevents double-clicks from
   // creating simultaneous subscriptions; a conflicting tier gets a safe error.
   const checkout=await stripe.checkout.sessions.create({mode:'subscription',customer:c,line_items:[{price:p.id,quantity:1}],integration_identifier:'blindbandit_members_vqmcptaz',metadata:{purpose,clerk_user_id:identity.clerkUserId},subscription_data:{metadata:{purpose,clerk_user_id:identity.clerkUserId}},success_url:origin+'/members/',cancel_url:origin+'/membership/',custom_text:{submit:{message:'Renews monthly in USD until canceled. Cancel in the member hub before renewal. Terms: https://mrblindbandit.net/membership/terms/'}}},{idempotencyKey:'bb-membership-'+identity.clerkUserId+'-'+Math.floor(Date.now()/3600000)});
   await write(env,'stripe-pending:'+identity.clerkUserId,{id:checkout.id});return json({url:checkout.url});
  }
  if(path==='/api/members/billing'&&request.method==='POST'){
   if(!s.customer)return json({error:'No billing account yet.'},404);
   let config=await read(env,'stripe-member-portal');if(!config){const c=await stripe.billingPortal.configurations.create({business_profile:{headline:'Mr. Blindbandit membership billing',privacy_policy_url:origin+'/privacy/',terms_of_service_url:origin+'/membership/terms/'},features:{invoice_history:{enabled:true},payment_method_update:{enabled:true},subscription_cancel:{enabled:true,mode:'at_period_end'}}},{idempotencyKey:'bb-member-portal-v1'});config=c.id;await write(env,'stripe-member-portal',config);}
   const session=await stripe.billingPortal.sessions.create({customer:s.customer,configuration:config,return_url:origin+'/members/'});return json({url:session.url});
  }
  if(path==='/api/members/cancel'&&request.method==='POST'){
   if(d.confirm!==true)return json({error:'Confirm cancellation.'},400);const sub=s.subscriptions.find((x:any)=>x.id===d.subscription);if(!sub||sub.status==='canceled')return json({error:'Active subscription not found.'},404);await stripe.subscriptions.update(sub.id,{cancel_at_period_end:true});return json({ok:true,message:'Renewal canceled. Access remains until the paid period ends.'});
  }
  if(path==='/api/members/templates'&&request.method==='GET'){
   if(s.level<5)return json({error:'Backstage membership or higher required.'},403);
   const content='BLINDBANDIT RECORDS — MEMBER CREATOR PACK\n\nRELEASE CHECKLIST\n1. Confirm master and composition rights.\n2. Check contributor spelling, title and version.\n3. Export and retain a lossless master.\n4. Verify artwork permissions and distributor dimensions.\n5. Review release date, credits and identifiers.\n6. Listen to the final delivered files.\n\nPRESS PITCH TEMPLATE\nSubject: [Artist] — [Release title] for [publication]\nHello [name],\nI am sharing [release] because [specific fit].\nThe release arrives [date]. Listen: [private link].\nCredits and press materials: [link].\nThank you, [name and contact].\n\nCOLLABORATION BRIEF\nProject:\nDeliverables:\nReference tracks:\nTimeline:\nBudget:\nRights and credits to agree in writing:\nApproval contact:\n\nThese templates support planning; they do not replace an agreement or guarantee coverage.\n';return new Response(content,{headers:{'content-type':'text/plain; charset=utf-8','content-disposition':'attachment; filename="blindbandit-member-creator-pack.txt"','cache-control':'private, no-store'}});
  }
  if(path==='/api/members/planner'){
   if(s.level<10)return json({error:'Creator membership or higher required.'},403);const key='member-planner:'+identity.clerkUserId;const previous=await read(env,key)||{revision:0,text:''};if(request.method==='GET')return json(previous);
   if(request.method!=='POST'||typeof d.text!=='string'||d.text.length>8000||d.revision!==previous.revision)return json({error:'The plan changed or exceeds 8,000 characters. Reload before saving.'},409);
   const next={revision:previous.revision+1,text:d.text};const changed=previous.revision?await q(env,'UPDATE label_settings SET value=? WHERE key=? AND value=? RETURNING key',JSON.stringify(next),key,JSON.stringify(previous)).first():await q(env,'INSERT INTO label_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO NOTHING RETURNING key',key,JSON.stringify(next)).first();return changed?json(next):json({error:'Another edit was saved first. Reload your plan.'},409);
  }
  if(path==='/api/members/message'&&request.method==='POST'){
   if(s.level<15)return json({error:'Insider membership or higher required.'},403);if(typeof d.message!=='string'||!d.message.trim()||d.message.length>3000)return json({error:'Write a message up to 3,000 characters.'},400);await rate(env,'message:'+identity.clerkUserId,2);const id=crypto.randomUUID(),now=Date.now();await env.DB.batch([q(env,'INSERT INTO site_requests(id,kind,name,email,details,created_at) VALUES(?,?,?,?,?,?)',id,'inquiry','Member',identity.email,JSON.stringify({category:'Member desk',message:d.message,tier:String(s.level)}),now),q(env,'INSERT INTO inbox_threads(id,department,updated_at) VALUES(?,?,?)',id,'Member desk',now)]);return json({ok:true,reference:id,message:'Your message is in the private label inbox. A response or review time is not guaranteed.'});
  }
  if(path==='/api/members/card'&&request.method==='GET'){
   if(s.level<20)return json({error:'Champion membership required.'},403);const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720"><rect width="1200" height="720" fill="#102323"/><rect x="30" y="30" width="1140" height="660" rx="24" fill="none" stroke="#dcc28c" stroke-width="4"/><text x="80" y="150" fill="#faf6e8" font-family="sans-serif" font-size="54">MR. BLINDBANDIT</text><text x="80" y="225" fill="#dcc28c" font-family="sans-serif" font-size="32">BLINDBANDIT RECORDS</text><text x="80" y="420" fill="#faf6e8" font-family="sans-serif" font-size="70">CHAMPION SUPPORTER</text><text x="80" y="540" fill="#dcc28c" font-family="sans-serif" font-size="28">Independent music. Accessible creation.</text><text x="80" y="620" fill="#faf6e8" font-family="sans-serif" font-size="20">Commemorative artwork — not proof of account access or ownership.</text></svg>';return new Response(svg,{headers:{'content-type':'image/svg+xml','content-disposition':'attachment; filename="blindbandit-champion-card.svg"','cache-control':'private, no-store'}});
  }
  return json({error:'Feature not found.'},404);
 }catch{return json({error:'Membership service could not complete this action. Please try again. Billing and access are checked directly with Stripe.'},503);}
}
