import {betterAuth} from 'better-auth';
import {drizzleAdapter} from '@better-auth/drizzle-adapter';
import {drizzle} from 'drizzle-orm/d1';
import {labelUser,labelSession,labelAccount,labelVerification} from '../db/portal-schema';
export type PortalEnv={DB:any;BUCKET:any;ASSETS:any;COMMUNITY_MODERATOR_EMAIL?:string;CLERK_ADMIN_EMAIL?:string;RESEND_API_KEY?:string;PORTAL_AUTH_SECRET?:string;PORTAL_SETUP_TOKEN?:string;PORTAL_EMAIL_FROM?:string;PORTAL_OWNER_LINK_SECRET?:string;GOOGLE_CLIENT_ID?:string;GOOGLE_CLIENT_SECRET?:string;APPLE_CLIENT_ID?:string;APPLE_CLIENT_SECRET?:string;NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?:string;CLERK_PUBLISHABLE_KEY?:string;CLERK_SECRET_KEY?:string};
export function portalProviders(env:PortalEnv){
 let apple=false;try{const jwt=env.APPLE_CLIENT_SECRET?.split('.')[1];apple=!!env.APPLE_CLIENT_ID&&!!jwt&&JSON.parse(atob(jwt.replace(/-/g,'+').replace(/_/g,'/'))).exp>Date.now()/1000+300;}catch{}
 return {google:!!env.GOOGLE_CLIENT_ID&&!!env.GOOGLE_CLIENT_SECRET,apple};
}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function sendPortalMail(env:PortalEnv,user:{id:string;email:string;name:string},url:string,kind='password'){
 const id=crypto.randomUUID(),invitation=kind==='invitation',welcome=kind==='owner_welcome';
 const title=welcome?'Welcome to your Blindbandit Records owner dashboard':invitation?'Your Blindbandit Records portal invitation':'Reset your Blindbandit Records password';
 const action=welcome?'Open your owner dashboard':invitation?'Create your password':'Reset your password';
 const paragraphs=[`Hello ${user.name},`,welcome?'Welcome to your private Blindbandit Records owner workspace. This message confirms a test of the label’s account-email service. Sign in through the secure dashboard link below to manage your label.':invitation?'You have been invited to the private Blindbandit Records label portal. Create your own password using the secure link below to activate your account.':'We received a request to reset the password for your Blindbandit Records label account. Use the secure link below to choose a new password.',
 welcome?'From your owner dashboard, you can invite clients and team members, assign roles, manage private messages and submissions, review contracts and earnings records, and coordinate releases, campaigns, and label operations. Your personal email receiving this test does not change the email used for your label login.':invitation?'Your workspace is tailored to your assigned role. Clients can review their own earnings records, contract documents, messages, and tasks. Authorized team members can coordinate label work, while administrators manage invitations and access.':'After a successful password reset, existing label portal sessions are signed out. Sign in again using your account email and new password.',
 welcome?'This is an account-service test, not a password reset. The dashboard requires sign-in; this email does not grant access or change your password.':`Account email: ${user.email}. Choose a unique password of at least 12 characters. The password link expires in one hour and can be used only once. If it expires, request another from the portal sign-in page.`,
 'Keep account-action links private. Blindbandit Records will never ask you to email your password. If you did not expect this message, contact business@mrblindbandit.net; do not share account details in the public community.',
 'Fan community profiles and invited label accounts are separate. Label financial records are maintained by authorized staff; they are not live bank balances or automatic royalty payments. Contract-review acknowledgments do not constitute electronic signatures.',
 'Thank you,\nBlindbandit Records · Account Services\nOn behalf of Kaeleb Savon Heck / Mr. Blindbandit\nbusiness@mrblindbandit.net\nPhilippines: +63 962 695 4905 · United States: +1 540 926 9791',
 'Confidentiality notice: This account-service message is intended for the named recipient and may contain private account information. If received in error, please notify the sender and delete it. Do not forward password links. This notice does not create legal privilege or override applicable rights.',
 'Legal notice: This email does not create a recording, employment, licensing, payment, or other commercial agreement. Any such commitment requires a separate authorized agreement. Applicable rights and signed agreements remain unaffected.'
 ];
 const footer='Purok 6-A, Mabuhay, Barangay Capungagan, Davao del Norte 8113, Philippines';
 const text=paragraphs.slice(0,2).join('\n\n')+'\n\n'+action+': '+url+'\n\n'+paragraphs.slice(2).join('\n\n')+'\n\n'+footer+'\nPortal privacy: https://mrblindbandit.net/portal/privacy/\nWebsite terms: https://mrblindbandit.net/terms/\n© '+new Date().getUTCFullYear()+' Blindbandit Records. All rights reserved.';
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;background:#111310;color:#f4f5ed;font:16px/1.65 Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#1b1f17;border-top:5px solid #ddfa67"><tr><td style="padding:32px;color:#f4f5ed"><a href="https://mrblindbandit.net/" style="display:block;margin-bottom:24px"><img src="https://mrblindbandit.net/assets/blindbandit-records-gold.jpeg" width="360" alt="Mr. Blindbandit — Blindbandit Records" style="display:block;width:100%;max-width:360px;height:auto;border:0;background:#111b16"></a><div style="font-size:26px;font-weight:900;letter-spacing:1px;color:#ddfa67">MR. BLINDBANDIT.</div><p style="font-size:13px;letter-spacing:2px;color:#c9d5b6">BLINDBANDIT RECORDS · ACCOUNT SERVICES</p><h1 style="font-size:28px;line-height:1.25">${escape(title)}</h1>${paragraphs.slice(0,2).map(p=>'<p style="color:#e2e8dc">'+escape(p)+'</p>').join('')}<p style="margin:30px 0"><a href="${escape(url)}" style="background:#ddfa67;color:#111310;padding:16px 24px;display:inline-block;font-weight:bold;text-decoration:none;border-radius:6px">${escape(action)}</a></p>${paragraphs.slice(2,6).map(p=>'<p style="color:#e2e8dc">'+escape(p).replace(/\n/g,'<br>')+'</p>').join('')}<p style="font-size:14px;word-break:break-all">If the button does not open, copy this address into your browser:<br><a href="${escape(url)}" style="color:#ddfa67">${escape(url)}</a></p><hr style="border:0;border-top:1px solid #4b5340">${paragraphs.slice(6).map(p=>'<p style="font-size:14px;line-height:1.6">'+escape(p).replace(/\n/g,'<br>')+'</p>').join('')}<p style="font-size:14px">${escape(footer)}</p><p style="font-size:14px">© ${new Date().getUTCFullYear()} Blindbandit Records. All rights reserved.<br><a href="https://mrblindbandit.net/portal/privacy/" style="color:#ddfa67">Portal privacy</a> · <a href="https://mrblindbandit.net/terms/" style="color:#ddfa67">Website terms</a> · <a href="https://mrblindbandit.net/" style="color:#ddfa67">Official website</a></p><p style="color:#e2e8dc"><a style="color:#ddfa67" href="mailto:business@mrblindbandit.net">Email the label</a> · <a style="color:#ddfa67" href="tel:+639626954905">Philippines: +63 962 695 4905</a> · <a style="color:#ddfa67" href="tel:+15409269791">US: +1 540 926 9791</a><br><a style="color:#ddfa67" href="https://www.google.com/maps/search/?api=1&amp;query=Purok%206-A%20Mabuhay%20Capungagan%20Davao%20del%20Norte%20Philippines">View the public business area on a map</a></p></td></tr></table></td></tr></table></body></html>`;
 await env.DB.prepare('INSERT INTO label_mail (id,user_id,kind,status,created_at) VALUES (?,?,?,?,?)').bind(id,user.id,kind,'pending',Date.now()).run();
 try{
  if(!env.RESEND_API_KEY)throw new Error('No sender configured');
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+env.RESEND_API_KEY,'content-type':'application/json','idempotency-key':id},body:JSON.stringify({from:env.PORTAL_EMAIL_FROM||'Blindbandit Records <accounts@mrblindbandit.com>',to:[user.email],reply_to:'business@mrblindbandit.net',subject:title,html,text}),signal:AbortSignal.timeout(15000)});
  const data:any=await response.json();
  if(!response.ok||!data.id){const providerMessage=String(data.message||'').replace(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g,'[email]').replace(/https?:\/\/\S+/g,'[URL]').replace(/\bre_[A-Za-z0-9_-]+\b/g,'[redacted]').slice(0,300);console.error(JSON.stringify({event:'label.email',requestId:id,status:'rejected',kind,httpStatus:response.status,providerCode:typeof data.name==='string'?data.name.slice(0,60):'unknown',providerMessage}));throw new Error('Email provider rejected delivery');}
  await env.DB.prepare('UPDATE label_mail SET status=?,provider_id=? WHERE id=?').bind('accepted',data.id,id).run();
  console.info(JSON.stringify({event:'label.email',requestId:id,status:'accepted',kind,providerId:data.id}));
  return {id,providerId:data.id};
 }catch{await env.DB.prepare('UPDATE label_mail SET status=? WHERE id=?').bind('failed',id).run();console.error(JSON.stringify({event:'label.email',requestId:id,status:'failed',kind}));throw new Error('Email could not be sent. Check the verified sending domain and email configuration.');}
}
export function portalAuth(env:PortalEnv,origin:string,invitation=false,reportDelivery?:(status:string)=>void,captureOwnerLink?:(url:string)=>void){
 const providers=portalProviders(env);
 return betterAuth({appName:'Blindbandit Records',baseURL:origin,basePath:'/api/label-auth',secret:env.PORTAL_AUTH_SECRET,
 database:drizzleAdapter(drizzle(env.DB),{provider:'sqlite',schema:{user:labelUser,session:labelSession,account:labelAccount,verification:labelVerification},transaction:false}),
 emailAndPassword:{enabled:true,autoSignIn:false,minPasswordLength:12,maxPasswordLength:128,resetPasswordTokenExpiresIn:3600,revokeSessionsOnPasswordReset:true,onPasswordReset:async({user})=>{await env.DB.batch([env.DB.prepare('UPDATE label_user SET email_verified=1,updated_at=? WHERE id=?').bind(Date.now(),user.id),env.DB.prepare('DELETE FROM label_verification WHERE value=?').bind(user.id),env.DB.prepare('INSERT INTO label_audit (id,actor_id,action,target_id,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),user.id,'password.reset',user.id,Date.now())]);},sendResetPassword:async({user,token})=>{if(captureOwnerLink){if(user.email!=='business@mrblindbandit.net')throw new Error('Owner setup only');captureOwnerLink(origin+'/portal/reset/#token='+encodeURIComponent(token));return;}try{await sendPortalMail(env,user,origin+'/portal/reset/#token='+encodeURIComponent(token),invitation||!user.emailVerified?'invitation':'password');reportDelivery?.('accepted');}catch{reportDelivery?.('failed');}}},
 socialProviders:{...(providers.google?{google:{clientId:env.GOOGLE_CLIENT_ID!,clientSecret:env.GOOGLE_CLIENT_SECRET!,disableSignUp:true,prompt:'select_account' as const}}:{}),...(providers.apple?{apple:{clientId:env.APPLE_CLIENT_ID!,clientSecret:env.APPLE_CLIENT_SECRET!,disableSignUp:true}}:{})},
 // A matching provider email never grants label access. Link while signed in first.
 account:{encryptOAuthTokens:true,accountLinking:{enabled:true,disableImplicitLinking:true,allowDifferentEmails:true}},
 databaseHooks:{session:{create:{before:async(session)=>{const m=await env.DB.prepare('SELECT status FROM label_members WHERE id=?').bind(session.userId).first();if(!m||m.status!=='active')return false;return {data:session};}}}},
 onAPIError:{errorURL:origin+'/portal/login/'},
 session:{expiresIn:60*60*12,updateAge:60*60,cookieCache:{enabled:false}},
 advanced:{useSecureCookies:true,cookiePrefix:'blindbandit_label',defaultCookieAttributes:{httpOnly:true,secure:true,sameSite:'lax'},database:{generateId:()=>crypto.randomUUID()}},
 trustedOrigins:['https://mrblindbandit.net','https://mr-blind-bandit.mrblindbandit.chatgpt.site','https://portal.mrblindbandit.net',...(providers.apple?['https://appleid.apple.com']:[])],
 rateLimit:{enabled:false}, // Every public auth POST is guarded by shared D1 counters in portal.ts.
 logger:{level:'error'}
 });
}
